### DISCUSSION TITLE
Issue with multiple nodes in k8s

### DISCUSSION THREAD

**Discussion by cferrera** [emqx/emqx#10370] [Q&A] [answered]
Hello, I'm struggling to make 2+ nodes to work together in kubernetes. A single node works perfectly.

_tried to search in discussions without luck_ 

### Error on EMQX-0 when EMQX-1 starts
```
error: {"time":1681222901230799,"pid":"<0.2821.0>","msg":"event=connect_to_remote_server peer=\"emqx@emqx-1.emqx-headless.mqtt-stg.svc.cluster.local\" result=failure reason=\"nxdomain\"","level":"error"}
{"time":1681222901231132,"pid":"<0.2821.0>","msg":"crasher: initial call: gen_rpc_client:init/1, pid: <0.2821.0>, registered_name: [], exit: {{badrpc,nxdomain},[{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,407}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}, ancestors: [gen_rpc_client_sup,gen_rpc_sup,<0.1817.0>], message_queue_len: 0, messages: [], links: [<0.1823.0>], dictionary: [], trap_exit: true, status: running, heap_size: 2586, stack_size: 29, reductions: 30587; neighbours: ","logger_formatter":{"title":"CRASH REPORT"},"line":525,"level":"error","error_logger":{"type":"crash_report","tag":"error_report"},"domain":["otp","sasl"],"mfa":"proc_lib:crash_report/4"}
```

### Error on EMQX-1 when it starts
```
*** prints all envs without warnings ***
{"time":1681222901321255,"pid":"<0.2088.0>","msg":"crasher: initial call: application_master:init/4, pid: <0.2088.0>, registered_name: [], exit: {{bad_return,{{emqx_conf_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,eacces}},[{emqx_conf_app,sync_data_from_node,1,[{file,\"emqx_conf_app.erl\"},{line,198}]},{emqx_conf_app,copy_override_conf_from_core_node,0,[{file,\"emqx_conf_app.erl\"},{line,170}]},{emqx_conf_app,init_conf,0,[{file,\"emqx_conf_app.erl\"},{line,85}]},{emqx_conf_app,start,2,[{file,\"emqx_conf_app.erl\"},{line,31}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,293}]}]}}}},[{application_master,init,4,[{file,\"application_master.erl\"},{line,142}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}, ancestors: [<0.2087.0>], message_queue_len: 1, messages: [{'EXIT',<0.2089.0>,normal}], links: [<0.2087.0>,<0.1689.0>], dictionary: [], trap_exit: true, status: running, heap_size: 610, stack_size: 29, reductions: 199; neighbours: ","logger_formatter":{"title":"CRASH REPORT"},"line":525,"level":"error","error_logger":{"type":"crash_report","tag":"error_report"},"domain":["otp","sasl"],"mfa":"proc_lib:crash_report/4"}
emqx-1 emqx 2023-04-11T14:21:41.322306+00:00 critical: {"time":1681222901322306,"reason":"{emqx_conf,{bad_return,{{emqx_conf_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,eacces}},[{emqx_conf_app,sync_data_from_node,1,[{file,\"emqx_conf_app.erl\"},{line,198}]},{emqx_conf_app,copy_override_conf_from_core_node,0,[{file,\"emqx_conf_app.erl\"},{line,170}]},{emqx_conf_app,init_conf,0,[{file,\"emqx_conf_app.erl\"},{line,85}]},{emqx_conf_app,start,2,[{file,\"emqx_conf_app.erl\"},{line,31}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,293}]}]}}}}}","pid":"<0.2085.0>","msg":"failed_to_start_app","line":88,"level":"critical","app":"emqx_conf","mfa":"emqx_machine_boot:start_one_app/1"}
{"time":1681222901322641,"pid":"<0.2085.0>","msg":"Supervisor: {local,emqx_machine_sup}. Context: start_error. Reason: {'EXIT',{{failed_to_start_app,emqx_conf,{emqx_conf,{bad_return,{{emqx_conf_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,eacces}},[{emqx_conf_app,sync_data_from_node,1,[{file,\"emqx_conf_app.erl\"},{line,198}]},{emqx_conf_app,copy_override_conf_from_core_node,0,[{file,\"emqx_conf_app.erl\"},{line,170}]},{emqx_conf_app,init_conf,0,[{file,\"emqx_conf_app.erl\"},{line,85}]},{emqx_conf_app,start,2,[{file,\"emqx_conf_app.erl\"},{line,31}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,293}]}]}}}}}},[{emqx_machine_boot,start_one_app,1,[{file,\"emqx_machine_boot.erl\"},{line,89}]},{lists,foreach,2,[{file,\"lists.erl\"},{line,1342}]},{emqx_machine_boot,post_boot,0,[{file,\"emqx_machine_boot.erl\"},{line,38}]},{supervisor,do_start_child_i,3,[{file,\"supervisor.erl\"},{line,414}]},{supervisor,do_start_child,2,[{file,\"supervisor.erl\"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,\"supervisor.erl\"},{line,384}]},{supervisor,children_map,4,[{file,\"supervisor.erl\"},{line,1250}]},{supervisor,init_children,2,[{file,\"supervisor.erl\"},{line,350}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,423}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}}. Offender: id=emqx_machine_boot,pid=undefined.","logger_formatter":{"title":"SUPERVISOR REPORT"},"line":392,"level":"error","error_logger":{"type":"supervisor_report","tag":"error_report","report_cb":"fun supervisor:format_log/1"},"domain":["otp","sasl"],"mfa":"supervisor:start_children/2"}
error: {"time":1681222901323385,"pid":"<0.2034.0>","msg":"crasher: initial call: application_master:init/4, pid: <0.2034.0>, registered_name: [], exit: {{{shutdown,{failed_to_start_child,emqx_machine_boot,{'EXIT',{{failed_to_start_app,emqx_conf,{emqx_conf,{bad_return,{{emqx_conf_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,eacces}},[{emqx_conf_app,sync_data_from_node,1,[{file,\"emqx_conf_app.erl\"},{line,198}]},{emqx_conf_app,copy_override_conf_from_core_node,0,[{file,\"emqx_conf_app.erl\"},{line,170}]},{emqx_conf_app,init_conf,0,[{file,\"emqx_conf_app.erl\"},{line,85}]},{emqx_conf_app,start,2,[{file,\"emqx_conf_app.erl\"},{line,31}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,293}]}]}}}}}},[{emqx_machine_boot,start_one_app,1,[{file,\"emqx_machine_boot.erl\"},{line,89}]},{lists,foreach,2,[{file,\"lists.erl\"},{line,1342}]},{emqx_machine_boot,post_boot,0,[{file,\"emqx_machine_boot.erl\"},{line,38}]},{supervisor,do_start_child_i,3,[{file,\"supervisor.erl\"},{line,414}]},{supervisor,do_start_child,2,[{file,\"supervisor.erl\"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,\"supervisor.erl\"},{line,384}]},{supervisor,children_map,4,[{file,\"supervisor.erl\"},{line,1250}]},{supervisor,init_children,2,[{file,\"supervisor.erl\"},{line,350}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,423}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}}}},{emqx_machine_app,start,[normal,[]]}},[{application_master,init,4,[{file,\"application_master.erl\"},{line,142}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}, ancestors: [<0.2033.0>], message_queue_len: 1, messages: [{'EXIT',<0.2035.0>,normal}], links: [<0.2033.0>,<0.1689.0>], dictionary: [], trap_exit: true, status: running, heap_size: 1598, stack_size: 29, reductions: 254; neighbours: ","logger_formatter":{"title":"CRASH REPORT"},"line":525,"level":"error","error_logger":{"type":"crash_report","tag":"error_report"},"domain":["otp","sasl"],"mfa":"proc_lib:crash_report/4"}
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,emqx_machine,{{shutdown,{failed_to_start_child,emqx_machine_boot,{'EXIT',{{failed_to_start_app,emqx_conf,{emqx_conf,{bad_return,{{emqx_conf_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,eacces}},[{emqx_conf_app,sync_data_from_node,1,[{file,\"emqx_conf_app.erl\"},{line,198}]},{emqx_conf_app,copy_override_conf_from_core_node,0,[{file,\"emqx_conf_app.erl\"},{line,170}]},{emqx_conf_app,init_conf,0,[{file,\"emqx_conf_app.erl\"},{line,85}]},{emqx_conf_app,start,2,[{file,\"emqx_conf_app.erl\"},{line,31}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,293}]}]}}}}}},[{emqx_machine_boot,start_one_app,1,[{file,\"emqx_machine_boot.erl\"},{line,89}]},{lists,foreach,2,[{file,\"lists.erl\"},{line,1342}]},{emqx_machine_boot,post_boot,0,[{file,\"emqx_machine_boot.erl\"},{line,38}]},{supervisor,do_start_child_i,3,[{file,\"supervisor.erl\"},{line,414}]},{supervisor,do_start_child,2,[{file,\"supervisor.erl\"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,\"supervisor.erl\"},{line,384}]},{supervisor,children_map,4,[{file,\"supervisor.erl\"},{line,1250}]},{supervisor,init_children,2,[{file,\"supervisor.erl\"},{line,350}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,423}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}}}},{emqx_machine_app,start,[normal,[]]}}}"}
emqx-1 emqx Kernel pid terminated (application_controller) ({application_start_failure,emqx_machine,{{shutdown,{failed_to_start_child,emqx_machine_boot,{'EXIT',{{failed_to_start_app,emqx_conf,{emqx_conf,{bad_return,{{emqx_conf_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,eacces}},[{emqx_conf_app,sync_data_from_node,1,[{file,"emqx_conf_app.erl"},{line,198}]},{emqx_conf_app,copy_override_conf_from_core_node,0,[{file,"emqx_conf_app.erl"},{line,170}]},{emqx_conf_app,init_conf,0,[{file,"emqx_conf_app.erl"},{line,85}]},{emqx_conf_app,start,2,[{file,"emqx_conf_app.erl"},{line,31}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,293}]}]}}}}}},[{emqx_machine_boot,start_one_app,1,[{file,"emqx_machine_boot.erl"},{line,89}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{emqx_machine_boot,post_boot,0,[{file,"emqx_machine_boot.erl"},{line,38}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start
```

### My Env
```
EMQX 5.0.11
AWS EKS
Kubernetes 1.21
Pod with 29Gi and 7cpu
```

### My EMQX Config
```
emqxConfig:
# https://www.emqx.io/docs/en/v5.0/admin/cfg.html#broker-mqtt
  EMQX_MQTT__IDLE_TIMEOUT: "30s"
  EMQX_MQTT__MAX_PACKET_SIZE: "1MB"
  EMQX_MQTT__MAX_QOS_ALLOWED: "2"
  EMQX_MQTT__RETAIN_AVAILABLE: "true"
  EMQX_MQTT__WILDCARD_SUBSCRIPTION: "true"
  EMQX_MQTT__SHARED_SUBSCRIPTION: "true"
  EMQX_MQTT__EXCLUSIVE_SUBSCRIPTION: "false"
  EMQX_MQTT__USE_USERNAME_AS_CLIENTID: "false"
  EMQX_MQTT__PEER_CERT_AS_USERNAME: "disabled"
  EMQX_MQTT__PEER_CERT_AS_CLIENTID: "cn"

# https://www.emqx.io/docs/en/v5.0/admin/cfg.html#authz-mnesia
  EMQX_AUTHORIZATION__SOURCES__1__ENABLE: "true"

# https://www.emqx.io/docs/en/v5.0/admin/cfg.html#authorization
  EMQX_AUTHORIZATION__NO_MATCH: deny
  EMQX_AUTHORIZATION__DENY_ACTION: "disconnect"

# https://www.emqx.io/docs/en/v5.0/admin/cfg.html#cluster
  EMQX_CLUSTER__DISCOVERY_STRATEGY: "k8s"

# https://www.emqx.io/docs/en/v5.0/admin/cfg.html#cluster-k8s
  EMQX_CLUSTER__K8S__APISERVER: "https://kubernetes.default.svc.cluster.local:443"
  EMQX_CLUSTER__K8S__ADDRESS_TYPE: "hostname"
  EMQX_CLUSTER__K8S__SUFFIX: "svc.cluster.local"
  EMQX_CLUSTER__K8S__SERVICE_NAME: "emqx-headless"
  EMQX_CLUSTER__K8S__NAMESPACE: "mqtt-stg"

# https://www.emqx.io/docs/en/v5.0/admin/cfg.html#broker
  EMQX_BROKER__SESSION_LOCKING_STRATEGY: "quorum"
  EMQX_BROKER__SHARED_SUBSCRIPTION_STRATEGY: "round_robin"
  EMQX_BROKER__SHARED_DISPATCH_ACK_ENABLED: "false"

# https://www.emqx.io/docs/en/v5.0/admin/cfg.html#broker-listener-ssl-opts
  EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__CACERTFILE: /opt/emqx/data/certs/ca.crt
  EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__CERTFILE: /opt/emqx/data/certs/tls.crt
  EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__KEYFILE: /opt/emqx/data/certs/tls.key
  EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__VERIFY: "verify_peer"
  EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__FAIL_IF_NO_PEER_CERT: "true"

# https://www.emqx.io/docs/en/v5.0/admin/cfg.html#broker-mqtt-tcp-listener
  EMQX_LISTENERS__TCP__DEFAULT__ACCEPTORS: "64"
  EMQX_LISTENERS__TCP__DEFAULT__MAX_CONNECTIONS: "5120000"

# https://www.emqx.io/docs/en/v5.0/admin/cfg.html#log
# https://www.emqx.io/docs/en/v5.0/admin/cfg.html#log-file-handler
  EMQX_LOG__FILE_HANDLERS__ERROR__ENABLE: "true"
  EMQX_LOG__FILE_HANDLERS__ERROR__FILE: "errors"
  EMQX_LOG__FILE_HANDLERS__ERROR__LEVEL: "debug"
  EMQX_LOG__FILE_HANDLERS__ERROR__FORMATTER: "json"
  EMQX_LOG__FILE_HANDLERS__ERROR__MAX_SIZE: "50MB"

# https://www.emqx.io/docs/en/v5.0/admin/cfg.html#console-handler
  EMQX_LOG__CONSOLE_HANDLER__ENABLE: "true"
  EMQX_LOG__CONSOLE_HANDLER__LEVEL: "warning"
  EMQX_LOG__CONSOLE_HANDLER__FORMATTER: "json"
  
# https://www.emqx.io/docs/en/v5.0/admin/cfg.html#node
  EMQX_NODE__COOKIE: "******"
  EMQX_NODE__PROCESS_LIMIT: "2097152"
  EMQX_NODE__MAX_PORTS: "2097152"
  
# https://www.emqx.io/docs/en/v5.0/admin/cfg.html#prometheus
  EMQX_PROMETHEUS__ENABLE: true
  EMQX_PROMETHEUS__INTERVAL: "30s"
  EMQX_PROMETHEUS__PUSH_GATEWAY_SERVER: "******"
```

> error: {"time":1681222901230799,"pid":"<0.2821.0>","msg":"event=connect_to_remote_server peer=\"emqx@emqx-1.emqx-headless.mqtt-stg.svc.cluster.local\" result=failure reason=\"nxdomain\"","level":"error"}

This one seems a really good lead but I'm I cannot spot any errors in the config.

Anyone have any ideas?

Thank you!!
