### DISCUSSION TITLE
http authentication config in helm

### DISCUSSION THREAD

**Discussion by Tuxzx** [emqx/emqx#10601] [Q&A] [answered]
I want to add HTTP authentication in Helm installation using emqx_config.

According to the documentation on [auth](https://www.emqx.io/docs/en/v5.0/configuration/configuration-manual.html#authentication), the parameter authn-http:post.url should be used. How can I write this in YAML?

The variable EMQX_AUTHN_HTTP__POST__URL is not working.

helm chart values: https://github.com/emqx/emqx/blob/master/deploy/charts/emqx/values.yaml
auth doc: https://www.emqx.io/docs/en/v5.0/configuration/configuration-manual.html#authentication

Thanks!

**Comment by Tuxzx** [comment, marked as answer]
This works.


```yaml
  EMQX_AUTHENTICATION__1__ENABLE: "true"
  EMQX_AUTHENTICATION__1__BACKEND: "http"
  EMQX_AUTHENTICATION__1__BODY: {"password": "${password}","username": "${username}"}
  EMQX_AUTHENTICATION__1__MECHANISM: "password_based"
  EMQX_AUTHENTICATION__1__METHOD: "post"
  EMQX_AUTHENTICATION__1__URL: "auth url"
```
