### DISCUSSION TITLE
EMQX with redis/memorydb authentication user configuration

### DISCUSSION THREAD

**Discussion by cnukwas** [emqx/emqx#10691] [Q&A]
We have deployed EMQX using [this](https://github.com/emqx/emqx/tree/master/deploy/charts/emqx-enterprise) Helm chart and configured the following EMQX configuration in the configmap to use redis (AWS MemoryDB offering) but seeing issues with redis connectivity as it's not clear how and where to configure the redis user in the configuration with 5.0.x version.
Any idea on how to configure redis user here?

```
data:
  EMQX_AUTHENTICATION__1__BACKEND: redis
  EMQX_AUTHENTICATION__1__ENABLE: "true"
  EMQX_AUTHENTICATION__1__MECHANISM: password_based
  EMQX_AUTHENTICATION__1__PASSWORD: blah123!
```
