### DISCUSSION TITLE
Separate Kubernetes Services for dashboard and MQTT with EMQX Helm Chart

### DISCUSSION THREAD

**Discussion by cnukwas** [emqx/emqx#10745] [Q&A] [answered]
Hi,

We have deployed EMQX 5.x using latest Helm charts and noticed that dashboard, mqtt, mqttssl, ws and wss ports are defined under the same Kubernetes service configuration. Is it possible to configure separate services for the dashboard, mqtt and others since we're using AWS LoadBalancer Ingress Controller and would like to enable TLS for dashboard access only and configure mqtt port without SSL/TLS termination at the LoadBalancer?

From emqx-enterprise chart [values](https://github.com/emqx/emqx/blob/master/deploy/charts/emqx-enterprise/values.yaml)

```
service:
  ## Service type
  ## for external access
  type: LoadBalancer
  ## Port for MQTT
  ##
  mqtt: 1883
  ## Port for MQTT(SSL)
  ##
  mqttssl: 8883
  ## Port for WebSocket/HTTP
  ##
  ws: 8083
  ## Port for WSS/HTTPS
  ##
  wss: 8084
  ## Port for dashboard and API
  ##
  dashboard: 18083
  ## Port for dashboard and API over HTTPS
  ##
  # dashboardtls: 18084
```

The Ingress configuration refers to HAProxy annotations which appears to support non-http protocols as well, that may not be the case with AWS version Ingress Controller since it creates an ALB which is for http/https traffic only, at least I am not aware of ways to use an Ingress resource for mqtt protocol.

It's certainly possible to manually create a LoadBalancer service for the mqtt protocol without SSL/TLS termination at the LB for dev environments and configure mqttssl for production environments later. Wondering if anyone ran into this situation and how to get around this by not making manual changes.

Thanks
