### DISCUSSION TITLE
Configure verify_claims using environment variables

### DISCUSSION THREAD

**Discussion by freol35241** [emqx/emqx#10771] [Q&A] [answered]
Hi, I am having trouble configuring verify_claims for the JWT auth using environment variables.

I am aware of #9880 and what seems to be the solution proposed there but I just can get it to work.

Relevant part of my docker-compose.yml:
```yaml
version: "3.8"

services:
  emqx:
    image: emqx/emqx:5.0.20
    environment:
      - EMQX_LISTENERS__WS__DEFAULT__AUTHENTICATION__1__VERIFY_CLAIMS='{sub:"$${username}"}'
```

Note: Double `$$` to escape docker compose env var substitution
Note: Auth provider is only configured for the default websocket listener

Error from emqx log:
```
2023-05-22T11:50:28.893505+00:00 [error] failed_to_check_schema: emqx_conf_schema
2023-05-22T11:50:28.895981+00:00 [error] #{exception => {error,{badmap,"'{sub:\"${username}\"}'"}},kind => validation_error,matched_type => "authn-jwt:hmac-based",path => "listeners.ws.default.authentication.1.verify_claims",reason => converter_crashed,stacktrace => [{maps,to_list,["'{sub:\"${username}\"}'"],[{file,"maps.erl"},{line,517},{error_info,#{module => erl_stdlib_errors}}]},{emqx_authn_jwt,'-verify_claims/1-fun-2-',1,[{file,"emqx_authn_jwt.erl"},{line,145}]},{hocon_tconf,map_field_maybe_convert,5,[{file,"hocon_tconf.erl"},{line,523}]},{hocon_tconf,map_one_field,4,[{file,"hocon_tconf.erl"},{line,487}]},{hocon_tconf,map_fields_cont,4,[{file,"hocon_tconf.erl"},{line,451}]},{hocon_tconf,do_map_union,4,[{file,"hocon_tconf.erl"},{line,779}]},{hocon_tconf,map_field,4,[{file,"hocon_tconf.erl"},{line,594}]},{hocon_tconf,map_one_field,4,[{file,"hocon_tconf.erl"},{line,487}]}]}
```

Can anyone shed some light on this and help me figure out how to solve this?

**Comment by freol35241** [comment, marked as answer]
Ahh, after trying every permutation I could come up with at least twice (obviously not...) the following worked:

```yaml
version: "3.8"

services:
  emqx:
    image: emqx/emqx:5.0.20
    environment:
      - EMQX_LISTENERS__WS__DEFAULT__AUTHENTICATION__1__VERIFY_CLAIMS={sub:"$${username}"}
```

Note the removed single quotes!!
