### DISCUSSION TITLE
Replicants not coming up with emqx operator

### DISCUSSION THREAD

**Discussion by alexa22013** [emqx/emqx#11343] [Q&A]
I am using emqx operator v2.2.0 and emqx v5.1.1, the replicants are not coming up
I also see this error in operator logs:
```
{"level":"error","ts":"2023-07-24T15:56:49Z","msg":"Reconciler error","controller":"emqx","controllerGroup":"apps.emqx.io","controllerKind":"EMQX","eMQX":{"name":"emqx","namespace":"emqx"},"namespace":"emqx","name":"emqx","reconcileID":"53a79b53-0da4-489b-9662-1b1c92cdafc9","error":"failed to get emqx config: failed to get API http://10.121.211.91:18083/api/v5/configs: failed to request API: Get \"http://10.121.211.91:18083/api/v5/configs\": dial tcp 10.121.211.91:18083: connect: connection refused","errorVerbose":"Get \"http://10.121.211.91:18083/api/v5/configs\": dial tcp 10.121.211.91:18083: connect: connection refused\nfailed to request API\ngithub.com/emqx/emqx-operator/internal/requester.(*Requester).Request\n\t/workspace/internal/requester/requester.go:89\ngithub.com/emqx/emqx-operator/controllers/apps/v2alpha2.getEMQXConfigsByAPI\n\t/workspace/controllers/apps/v2alpha2/sync_emqx_config.go:79\ngithub.com/emqx/emqx-operator/controllers/apps/v2alpha2.(*syncConfig).reconcile\n\t/workspace/controllers/apps/v2alpha2/sync_emqx_config.go:46\ngithub.com/emqx/emqx-operator/controllers/apps/v2alpha2.(*EMQXReconciler).Reconcile\n\t/workspace/controllers/apps/v2alpha2/emqx_controller.go:125\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598\nfailed to get API http://10.121.211.91:18083/api/v5/configs\ngithub.com/emqx/emqx-operator/controllers/apps/v2alpha2.getEMQXConfigsByAPI\n\t/workspace/controllers/apps/v2alpha2/sync_emqx_config.go:83\ngithub.com/emqx/emqx-operator/controllers/apps/v2alpha2.(*syncConfig).reconcile\n\t/workspace/controllers/apps/v2alpha2/sync_emqx_config.go:46\ngithub.com/emqx/emqx-operator/controllers/apps/v2alpha2.(*EMQXReconciler).Reconcile\n\t/workspace/controllers/apps/v2alpha2/emqx_controller.go:125\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598\nfailed to get emqx config\ngithub.com/emqx/emqx-operator/controllers/apps/v2alpha2.(*syncConfig).reconcile\n\t/workspace/controllers/apps/v2alpha2/sync_emqx_config.go:48\ngithub.com/emqx/emqx-operator/controllers/apps/v2alpha2.(*EMQXReconciler).Reconcile\n\t/workspace/controllers/apps/v2alpha2/emqx_controller.go:125\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"}
``` 

Anyway to resolve this?

Thanks in advance.

**Comment by id** [comment]
@alexa22013 could you attach logs from emqx pods?

**Reply by alexa22013** [reply]
logs from core nodes

```
WARNING: Default (insecure) Erlang cookie is in use.
WARNING: Configure node.cookie in /opt/emqx/etc/emqx.conf or override from environment variable EMQX_NODE__COOKIE
WARNING: NOTE: Use the same cookie for all nodes in the cluster.
EMQX_API_KEY__BOOTSTRAP_FILE [api_key.bootstrap_file]: /opt/emqx/data/bootstrap_api_key
EMQX_RPC__PORT_DISCOVERY [rpc.port_discovery]: manual
EMQX_CLUSTER__DNS__RECORD_TYPE [cluster.dns.record_type]: srv
EMQX_CLUSTER__DNS__NAME [cluster.dns.name]: emqx-headless.emqx.svc.cluster.local
EMQX_CLUSTER__DISCOVERY_STRATEGY [cluster.discovery_strategy]: dns
Listener ssl:default on 0.0.0.0:8883 started.
Listener ssl:mqtt-device on 0.0.0.0:8886 started.
Listener ssl:mqtt-mobile on 0.0.0.0:8885 started.
Listener tcp:default on 0.0.0.0:1883 started.
Listener ws:default on 0.0.0.0:8083 started.
Listener wss:default on 0.0.0.0:8084 started.
Listener http:dashboard on :18083 started.
EMQX 5.1.1 is running now!
2023-07-24T19:15:46.737676+00:00 [warning] msg: Stopping mria, mfa: mria:stop/1, line: 133, reason: join
Stop listener http:dashboard on :18083 successfully.
Listener ssl:default on 0.0.0.0:8883 stopped.
Listener ssl:mqtt-device on 0.0.0.0:8886 stopped.
Listener ssl:mqtt-mobile on 0.0.0.0:8885 stopped.
Listener tcp:default on 0.0.0.0:1883 stopped.
Listener ws:default on 0.0.0.0:8083 stopped.
Listener wss:default on 0.0.0.0:8084 stopped.
Listener ssl:default on 0.0.0.0:8883 started.
Listener ssl:mqtt-device on 0.0.0.0:8886 started.
Listener ssl:mqtt-mobile on 0.0.0.0:8885 started.
Listener tcp:default on 0.0.0.0:1883 started.
Listener ws:default on 0.0.0.0:8083 started.
Listener wss:default on 0.0.0.0:8084 started.
2023-07-24T19:15:47.148828+00:00 [warning] msg: CMD_overridden, mfa: emqx_ctl:handle_call/3, line: 254, cmd: observer, mf: {emqx_observer_cli,cmd}
2023-07-24T19:15:47.148960+00:00 [warning] msg: CMD_overridden, mfa: emqx_ctl:handle_call/3, line: 254, cmd: cluster_call, mf: {emqx_conf_cli,admins}
2023-07-24T19:15:47.149076+00:00 [warning] msg: CMD_overridden, mfa: emqx_ctl:handle_call/3, line: 254, cmd: conf, mf: {emqx_conf_cli,conf}
Listener http:dashboard on :18083 started.
```

**Reply by id** [reply]
Could you also post your yaml file(s) for deploying emqx? I'll try to reproduce the issue.

**Reply by alexa22013** [reply]
for operator iam using the emqx operator helm chart

emqx ymal (referance taken from git sample): 
```
data:
- apiVersion: apps.emqx.io/v2alpha2
  kind: EMQX
  metadata:
    name: emqx
    labels:
      app: emqx
  spec:
    image: "emqx/emqx:5.1.1"
    imagePullPolicy: IfNotPresent
    config:
      data: |
        node {
          cookie = emqxsecretcookie
          data_dir = "data"
          etc_dir = "etc"
        }

        log {
          file_handlers.default {
            level = warning
            file = "log/emqx.log"
          }
        }

        cluster {
          discovery_strategy = dns
          dns {
            record_type = srv
            name:"emqx-headless.emqx.svc.cluster.local"
          }
        }

        dashboard {
          listeners.http {
              bind: 18083
          }
          default_username: "admin"
          default_password: "public"
        }

        listeners.ssl.mqtt-device {
          bind = "0.0.0.0:8886"
          max_connections = 1024000

          ssl_options {
            keyfile = "etc/certs/key.pem"
            certfile = "etc/certs/cert.pem"
            cacertfile = "etc/certs/cacert.pem"
            verify = verify_peer
            fail_if_no_peer_cert = false
          }
        }

        broker {
          shared_subscription_group {
            service.strategy = sticky
          }

          # peer_cert_as_clientid = cn
        }

        sysmon.vm.long_schedule = disabled
      
    coreTemplate:
      metadata:
        name: emqx-core
        labels:
          apps.emqx.io/instance: emqx
          apps.emqx.io/db-role: core
      spec:
        replicas: 2
        # volumeClaimTemplates:
        #   storageClassName: ssd
        #   resources:
        #     requests:
        #       storage: 100Mi
        #   accessModes:
        #   - ReadWriteOnce
        # toleRations:
        #   - key: "nodepool"
        #     operator: "Equal"
        #     value: "emqx"
        #     effect: "NoSchedule"
        # nodeSelector:
        #   nodepool: emqx
        command:
          - "/usr/bin/docker-entrypoint.sh"
        args:
          - "/opt/emqx/bin/emqx"
          - "foreground"
        ports:
          - name: mqtt-tcp
            containerPort: 1883
          - name: mqtt-http
            containerPort: 18083
          - name: mqtt-device
            containerPort: 8886
        # envFrom:
        #   - configMapRef:
        #       name: fake-configmap
        resources:
          requests:
            memory: "100Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        extraVolumes:
          - name: certs
            secret:
              secretName: emqx-certs
        extraVolumeMounts:
          - name: certs
            mountPath: /opt/emqx/etc/certs/key.pem
            subPath: tls.key
          - name: certs
            mountPath: /opt/emqx/etc/certs/cert.pem
            subPath: tls.crt
          - name: certs
            mountPath: /opt/emqx/etc/certs/cacert.pem
            subPath: ca.crt
        livenessProbe:
          httpGet:
            path: /status
            port: 18083
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /status
            port: 18083
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 12
        startupProbe:
          httpGet:
            path: /status
            port: 18083
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 12
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","emqx ctl cluster leave"]
    replicantTemplate:
      metadata:
        name: emqx-replicant
        labels:
          apps.emqx.io/instance: emqx
          apps.emqx.io/db-role: replicant
      spec:
        replicas: 3
        # toleRations:
        #   - key: "nodepool"
        #     operator: "Equal"
        #     value: "emqx"
        #     effect: "NoSchedule"
        # nodeSelector:
        #   nodepool: emqx
        command:
          - "/usr/bin/docker-entrypoint.sh"
        args:
          - "/opt/emqx/bin/emqx"
          - "foreground"
        ports:
          - name: mqtt-tcp
            containerPort: 1883
          - name: mqtt-http
            containerPort: 18083
          - name: mqtt-device
            containerPort: 8886
        resources:
          requests:
            memory: "100Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        extraVolumes:
          - name: certs
            secret:
              secretName: emqx-certs
        extraVolumeMounts:
          - name: certs
            mountPath: /opt/emqx/etc/certs/key.pem
            subPath: tls.key
          - name: certs
            mountPath: /opt/emqx/etc/certs/cert.pem
            subPath: tls.crt
          - name: certs
            mountPath: /opt/emqx/etc/certs/cacert.pem
            subPath: ca.crt
        livenessProbe:
          httpGet:
            path: /status
            port: 18083
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /status
            port: 18083
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 12
        startupProbe:
          httpGet:
            path: /status
            port: 18083
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 12
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","emqx ctl cluster leave"]
    dashboardServiceTemplate:
      metadata:
        name: emqx-dashboard
        labels:
          apps.emqx.io/instance: emqx
      spec:
        selector:
          apps.emqx.io/db-role: core
        ports:
        - name: dashboard-listeners-http-bind
          protocol: TCP
          port: 18083
          targetPort: mqtt-http
        - name: mqtt-tcp
          protocol: TCP
          port: 1883
          targetPort: mqtt-tcp
        type: ClusterIP
        clusterIP: None
    listenersServiceTemplate:
      metadata:
        name: emqx-lb
        labels:
          apps.emqx.io/instance: emqx
      spec:
        selector:
          apps.emqx.io/instance: emqx
        ports:
        - port: 8886
          targetPort: mqtt-device
          protocol: TCP
          name: mqtt-device
        type: LoadBalancer
        externalTrafficPolicy: Local

```

**Reply by id** [reply]
@alexa22013 trying to reproduce, failing with `emqx-certs` secret. Could you adivise how to initialize it correctly? I just used development .pem files.

```
$ kubectl create secret generic emqx-certs \
  --from-file=./cert.pem \
  --from-file=./key.pem \
  --from-file=./cacert.pem
secret/emqx-certs created

$ kubectl apply -f emqx.yaml
emqx.apps.emqx.io/emqx created

$ kubectl describe pod emqx-core-78ccbdf49f-0
...
Events:
  Type     Reason     Age              From               Message
  ----     ------     ----             ----               -------
  Normal   Scheduled  6s               default-scheduler  Successfully assigned default/emqx-core-78ccbdf49f-0 to minikube
  Normal   Pulled     5s (x2 over 6s)  kubelet            Container image "emqx/emqx:5.1.1" already present on machine
  Normal   Created    5s (x2 over 6s)  kubelet            Created container emqx
  Warning  Failed     5s (x2 over 6s)  kubelet            Error: failed to start container "emqx": Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/var/lib/kubelet/pods/1d707fb6-c124-4145-adb7-ab42155cd595/volume-subpaths/certs/emqx/6" to rootfs at "/opt/emqx/etc/certs/cacert.pem": mount /var/lib/kubelet/pods/1d707fb6-c124-4145-adb7-ab42155cd595/volume-subpaths/certs/emqx/6:/opt/emqx/etc/certs/cacert.pem (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
  Warning  BackOff    1s               kubelet            Back-off restarting failed container
```

**Reply by alexa22013** [reply]
can u try this? without any certs

```
apiVersion: apps.emqx.io/v2alpha2
kind: EMQX
metadata:
  name: emqx
  labels:
    app: emqx
spec:
  image: "emqx/emqx:5.1.1"
  imagePullPolicy: IfNotPresent
  config:
    data: |
      node {
        cookie = emqxsecretcookie
        data_dir = "data"
        etc_dir = "etc"
      }

      log {
        file_handlers.default {
          level = warning
          file = "log/emqx.log"
        }
      }

      cluster {
        discovery_strategy = dns
        dns {
          record_type = srv
          name:"emqx-headless.emqx.svc.cluster.local"
        }
      }

      dashboard {
        listeners.http {
            bind: 18083
        }
        default_username: "admin"
        default_password: "public"
      }

      listeners.ssl.mqtt-mobile {
        bind = "0.0.0.0:8885"
        max_connections = 1024000

        ssl_options {
          verify = verify_none
          fail_if_no_peer_cert = false
        }
      }

      broker {
        shared_subscription_group {
          shadowService.strategy = sticky
          appsync.strategy = sticky
        }

        # peer_cert_as_clientid = cn
      }

      sysmon.vm.long_schedule = disabled
    
  coreTemplate:
    metadata:
      name: emqx-core
      labels:
        apps.emqx.io/instance: emqx
        apps.emqx.io/db-role: core
    spec:
      replicas: 2
      # volumeClaimTemplates:
      #   storageClassName: ssd
      #   resources:
      #     requests:
      #       storage: 100Mi
      #   accessModes:
      #   - ReadWriteOnce
      # toleRations:
      #   - key: "nodepool"
      #     operator: "Equal"
      #     value: "emqx"
      #     effect: "NoSchedule"
      # nodeSelector:
      #   nodepool: emqx
      command:
        - "/usr/bin/docker-entrypoint.sh"
      args:
        - "/opt/emqx/bin/emqx"
        - "foreground"
      ports:
        - name: mqtt-tcp
          containerPort: 1883
        - name: mqtt-http
          containerPort: 18083
        - name: mqtt-mobile
          containerPort: 8885
      # envFrom:
      #   - configMapRef:
      #       name: fake-configmap
      resources:
        requests:
          memory: "100Mi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "1000m"
      livenessProbe:
        httpGet:
          path: /status
          port: 18083
        initialDelaySeconds: 60
        periodSeconds: 30
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /status
          port: 18083
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 12
      startupProbe:
        httpGet:
          path: /status
          port: 18083
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 12
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh","-c","emqx ctl cluster leave"]
  replicantTemplate:
    metadata:
      name: emqx-replicant
      labels:
        apps.emqx.io/instance: emqx
        apps.emqx.io/db-role: replicant
    spec:
      replicas: 3
      # toleRations:
      #   - key: "nodepool"
      #     operator: "Equal"
      #     value: "emqx"
      #     effect: "NoSchedule"
      # nodeSelector:
      #   nodepool: emqx
      command:
        - "/usr/bin/docker-entrypoint.sh"
      args:
        - "/opt/emqx/bin/emqx"
        - "foreground"
      ports:
        - name: mqtt-tcp
          containerPort: 1883
        - name: mqtt-http
          containerPort: 18083
        - name: mqtt-mobile
          containerPort: 8885
      resources:
        requests:
          memory: "100Mi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "1000m"
      livenessProbe:
        httpGet:
          path: /status
          port: 18083
        initialDelaySeconds: 60
        periodSeconds: 30
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /status
          port: 18083
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 12
      startupProbe:
        httpGet:
          path: /status
          port: 18083
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 12
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh","-c","emqx ctl cluster leave"]
  dashboardServiceTemplate:
    metadata:
      name: emqx-dashboard
      labels:
        apps.emqx.io/instance: emqx
    spec:
      selector:
        apps.emqx.io/db-role: core
      ports:
      - name: dashboard-listeners-http-bind
        protocol: TCP
        port: 18083
        targetPort: mqtt-http
      - name: mqtt-tcp
        protocol: TCP
        port: 1883
        targetPort: mqtt-tcp
      type: ClusterIP
      clusterIP: None
  listenersServiceTemplate:
    metadata:
      name: emqx-lb
      labels:
        apps.emqx.io/instance: emqx
    spec:
      selector:
        apps.emqx.io/instance: emqx
      ports:
      - port: 8885
        targetPort: mqtt-mobile
        protocol: TCP
        name: mqtt-mobile
      type: LoadBalancer
      externalTrafficPolicy: Local

```
