### DISCUSSION TITLE
how to keep the configuration data of emqx

### DISCUSSION THREAD

**Discussion by homonto** [emqx/emqx#11443] [Q&A]
Hi,

I just deployed the emqx as docker container with following compose file:
```

  init-emqx:
    image: emqx/emqx:latest
    container_name: init-emqx
    entrypoint: sh -c
    volumes:
      # We mount this in the container as `/emqx_etc` to not conflict with built-in files
      # at `/opt/emqx/emqx_etc`
      - /srv/docker/emqx/etc:/emqx_etc
    command:
      # Seed the files from the image to our /emqx_etc if marker file not present, skip
      # if the marker file exists (and implicitly exit cleanly with status code 0)
      - |
        if [ ! -f /emqx_etc/.emqx-seed-complete ]; then
          mkdir /emqx_etc ;
          touch /emqx_etc/.emqx-seed-complete ;
          cp -dpR /opt/emqx/etc/* /emqx_etc/ ;
        fi


  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    restart: unless-stopped
    depends_on:
      init-emqx:
        condition: service_completed_successfully
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    volumes:
      - /srv/docker/emqx/data:/opt/emqx/data
      - /srv/docker/emqx/log:/opt/emqx/log
      - /srv/docker/emqx/etc:/opt/emqx/etc

```

and all is working ok except that, when I remove /var/lib/docker/* folder I am losing the configuration data of emqx such as:
- usernames
- passwords
- configuration of backends etc

What am I doing incorrectly?

thx for help
