### DISCUSSION TITLE
high CPU usage with only a few clients and messages.. v5.3.0

### DISCUSSION THREAD

**Discussion by slaesh** [emqx/emqx#11774] [Q&A]
![image](https://github.com/emqx/emqx/assets/55546823/d462ec83-ed85-448e-8ad8-e8db54f53bc6)

I would assume that it would idle most of the time. but the CPU seems pretty high for nearly "nothing to do" :)

Is this normal?

**Comment by slaesh** [comment]
lens screenshot: 
![image](https://github.com/emqx/emqx/assets/55546823/f5ffda62-b941-41ad-aab9-c397dd6c6564)

it went even more up as I browsed into the dashboard..

**Comment by slaesh** [comment]
logs are quiet: 
![image](https://github.com/emqx/emqx/assets/55546823/856cf664-4965-4726-96e9-0e05b6b9eb22)

**Comment by myhaleha** [comment]
Additional to @slaesh screenshots, this is the CPU usage of moment when we upgraded from v5.0.20 (magenta line) to v5.3 (orange line). Basically the usage increased even more.
![image](https://github.com/emqx/emqx/assets/122281249/48749e96-ac9e-4639-bb0c-d75a042e8280)

**Comment by thalesmg** [comment]
Hi, can you provide more information about your setup?
- Available CPU and memory in the pods.
- Are there any integrations/data bridges being used?
- Are wildcard topics being used in the subscriptions?
- Increasing the log level to `debug` might be helpful as well, if possible.

Also, you could try logging into a shell into the pod and running the following:
1. `emqx ctl observer status`
2. After it starts, press `r` then `enter` to sort the processes by CPU usage, and please share the findings.

**Reply by myhaleha** [reply]
Sure! We use e2-medium machines with 1 shared core and 4Gb of memory.

I downgraded from the version 5.3 to 5.0.2 and the resources usage decreased, but still seems quite demanding.

Metrics of the emqx-pod:
![image](https://github.com/emqx/emqx/assets/122281249/1c7a66f4-c53e-42bf-9a5d-072d71946aa3)

Metrics of the node where the emqx-pod is running:
![image](https://github.com/emqx/emqx/assets/122281249/67a37f45-17ef-46e6-b797-1f8f2a4cdc86)

- Are there any integrations/data bridges being used? 
  - None
- Are wildcard topics being used in the subscriptions? 
  - Yes, a couple
  
     ![image](https://github.com/emqx/emqx/assets/122281249/187fbc43-6f3f-47da-bc60-711dc803ec24)

  
  
shell output:
![image](https://github.com/emqx/emqx/assets/122281249/f50d164a-fb76-4bf2-b416-1e216f167314)

Additionally: We don't use k8s operator.

**Reply by thalesmg** [reply]
Thanks for the info.  Was the problem occurring when those screenshots were taken (including the observer output)?  The CPU usage in the observer image (`ps -o cpu`) seems to be low (1.6 %).

**Reply by thalesmg** [reply]
Also, you mentioned you are not using k8s operator, and I see that apparently OTP 24 is being used from the output of observer.

Are you using a custom built image?

**Reply by myhaleha** [reply]
Yes, these are the data of approximately same moment of time. I updated some of the info in the previous reply too.

**Reply by thalesmg** [reply]
Can you run the observer command in 5.3.0 and while the problem is happening?

Since it's showing OTP 24, it suggests that the version being used when the screenshot was taken was 5.0.20.

**Reply by thalesmg** [reply]
Also, if you could also capture the observer output after pressing `rr` then `enter` (not just `r + enter`), it might be helpful as well.

**Reply by myhaleha** [reply]
Just rolled out 5.3

These are the metrics so far:
![image](https://github.com/emqx/emqx/assets/122281249/74f13f9a-a122-42c2-b6cf-8b8ae02fb5fc)

r: 
![image](https://github.com/emqx/emqx/assets/122281249/dbd0135b-df20-4f16-b0f6-ae49a358f1a9)

and rr, but stats here change quite fast:

![image](https://github.com/emqx/emqx/assets/122281249/bf58315a-4ce0-420d-aa72-50fff6056c00)

![image](https://github.com/emqx/emqx/assets/122281249/f0f9c13c-364d-4e2c-8edc-7e98ecfd2408)

![image](https://github.com/emqx/emqx/assets/122281249/ff5ce894-8e8c-43ea-9042-2a9c51ca3ac2)

**Reply by slaesh** [reply]
EMQX dashboard: 
![image](https://github.com/emqx/emqx/assets/55546823/f2abc9d2-6115-4ed1-a0e3-39a0b038ad8d)

**Reply by thalesmg** [reply]
Thanks for the info.  Odd, `ps -o pcpu` seems to report ~ 2 % CPU usage in the last 4 screenshots.

You also mentioned that there's an additional `mqtt-init` container inside the pod.  Is it running some code that could be contributing to the pod CPU usage as a whole?  Is it possible to test the deployment without this extra container?

**Reply by slaesh** [reply]
yeah, we already removed that piece too. no changes. it just starts a shell script which does some http-calls to configure the emqx and then sleeps. anyways, we removed it. :)

**Reply by thalesmg** [reply]
I'm still trying to reproduce/investigate.  Using docker locally (v5.3.0), I observe about ~ 20 % CPU usage when "at rest" (no clients), and then ~ 30 % CPU usage with 20 subscribers and 20 publishers, at 20 msgs / s (CPU reported by observer).

`top` indicates more CPU than observer when there are clients (50 %), and `docker stats` varies quite wildly, from 30 % to 70 % when there is traffic, which could be why the metrics you observed are higher than observer reports.

Also, running `emqx ctl status` periodically does incur in large peaks reported by `docker stats`, which are probably due to the script/Erlang VM frequent startup.

**Reply by slaesh** [reply]
thanks for your help! we really do appreciate that! 🙏

we were just wondering if we did something wrong setting it up, or is it usual.
so the conclusion.. this "high" CPU usage seems "normal"?

20% on rest sounds like 19.99% too much for an event driven system :)

adding "a few" clients, sending "a few" messages.. and it climbs 10% more?
I am wondering how can it then achieve millions of clients? =)
due to clustering?! there is no asterisk on these metrics ;))

on what count of clients do we need to start clustering and adding nodes? 😊

is there some sort of guideline?

**Reply by thalesmg** [reply]
I've asked the team, and there are a couple things that might help.

One is an improvement that will help reduce the CPU usage due to calling `emqx ctl status` too often (this is yet to be released): https://github.com/emqx/emqx/pull/11787

Another suggestion is to try reducing the maximum number of ports and processes in your setup, since it has such low CPU and memory resources.  You can try the following:

```
EMQX_NODE__MAX_PORTS=2048
```

**Comment by myhaleha** [comment]
> Also, you mentioned you are not using k8s operator, and I see that apparently OTP 24 is being used from the output of observer.
> 
> Are you using a custom built image?

We use also additional init container:

![image](https://github.com/emqx/emqx/assets/122281249/ad98d1eb-b43f-43d8-a134-c58d251e3797)

**Reply by slaesh** [reply]
no custom image, this is the deployment:


```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  labels:
    app: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
        type: customer-infra
    spec:
      containers:
        - name: mqtt
          image: emqx/emqx:5.0.20
          ports:
            - containerPort: 1883
              name: mqtt-port
            - containerPort: 8083
              name: websocket-port
            - containerPort: 18083
              name: http-dashboard
          env:
            - name: EMQX_NODE__COOKIE
              valueFrom:
                secretKeyRef:
                  name: project
                  key: EMQX_NODE__COOKIE
            - name: EMQX_DASHBOARD__DEFAULT_USERNAME
              value: "username"
            - name: EMQX_DASHBOARD__DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: project
                  key: EMQX_DASHBOARD__DEFAULT_PASSWORD
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - /opt/emqx/bin/emqx_ctl
                - status
            timeoutSeconds: 10
            initialDelaySeconds: 240 # check why this needs to be so high?
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - /opt/emqx/bin/emqx_ctl
                - status
            timeoutSeconds: 15
            initialDelaySeconds: 240 # check why this needs to be so high?
            periodSeconds: 20
            failureThreshold: 15
            successThreshold: 1
```
