### DISCUSSION TITLE
Issue with hostname in k8s

### DISCUSSION THREAD

**Discussion by JimmyBjorklund** [emqx/emqx#11856] [Q&A] [answered]
Hi I dont seam to get the emqx 5.3.0 to start using hostnames.

Startup log:
```
EMQX_CLUSTER__K8S__SUFFIX [cluster.k8s.suffix]: svc.cluster.local
EMQX_CLUSTER__K8S__NAMESPACE [cluster.k8s.namespace]: default
EMQX_CLUSTER__K8S__ADDRESS_TYPE [cluster.k8s.address_type]: hostname
EMQX_CLUSTER__K8S__SERVICE_NAME [cluster.k8s.service_name]: emqx-headless
EMQX_CLUSTER__K8S__APISERVER [cluster.k8s.apiserver]: https://kubernetes.default.svc:443
EMQX_NODE__NAME [node.name]: emqx@192.168.62.131
2023-10-31T15:55:31.016829+00:00 [warning] mria_mnesia: still waiting for table(s): ['$mria_rlog_sync'] mfa: undefined
2023-10-31T15:55:31.017227+00:00 [warning] Check down_nodes should get [] but got ['emqx@192.168.108.226'], Table '$mria_rlog_sync' is waiting for one of the nodes: ['emqx@192.168.108.226'] , mfa: undefined
```
Expected  EMQX_NODE__NAME [node.name]: emqx@192.168.62.131 to be something simular to emqx-0.emqx-headless.default.svc.cluster.local
Any one have any ide ? 

emqx.conf
```
cluster {
  name = emqxdev
  discovery_strategy = k8s
  k8s {
    address_type = hostname    
    namespace = "default"
    service_name = "emqx-headless"
    suffix = "svc.cluster.local"
  }
}
```

deployment

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: default
  name: emqx
spec:
  serviceName: emqx-headless
  replicas: 2
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      securityContext:
        fsGroup: 1000
      serviceAccountName: emqx
      containers:
      - name: emqx
        image: emqx/emqx:5.3.0
        ports:
        - name: mqtt
          containerPort: 1883
          hostPort: 1883
        - name: mqtts
          containerPort: 8883
          hostPort: 8883
        - name: mgmt
          containerPort: 8081
          hostPort: 8081
        - name: emqx-dashboard
          containerPort: 18083
          hostPort: 18083
        env:
        - name: EMQX_NAME
          value: emqx
        - name: EMQX_CLUSTER__K8S__APISERVER
          value: https://kubernetes.default.svc:443
        - name: EMQX_CLUSTER__K8S__NAMESPACE
          value: default
        - name: EMQX_CLUSTER__K8S__SERVICE_NAME
          value: emqx-headless
        - name: EMQX_CLUSTER__K8S__ADDRESS_TYPE
          value: hostname
        - name: EMQX_CLUSTER__K8S__SUFFIX
          value: svc.cluster.local
        tty: true
        volumeMounts:
            - mountPath: /opt/emqx/etc/emqx.conf
              subPath: emqx.conf
              name: emqx-conf
              readOnly: true
            - mountPath: /opt/emqx/etc/acl.conf
              subPath: acl.conf
              name: emqx-conf
              readOnly: true
            - mountPath: /opt/emqx/etc/certs/netmore
              name: certs
              readOnly: true  
            - name: persistent-storage
              mountPath: "/opt/emqx/data/mnesia"
      volumes:
        - name: "emqx-conf"
          secret:
            secretName: "emqx.conf"
            items:
              - key: "emqx.conf"
                path: "emqx.conf"
              - key: "acl.conf"
                path: "acl.conf"
        - name: "certs"
          secret:
            secretName: "emqx-netmore.certs"
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: emqx-pvc
```

Server:         10.100.0.10
Address:        10.100.0.10#53

Name:   emqx-0.emqx-headless.default.svc.cluster.local
Address: 192.168.99.184

root@app:/# nslookup emqx-1.emqx-headless.default.svc.cluster.local
Server:         10.100.0.10
Address:        10.100.0.10#53

Name:   emqx-1.emqx-headless.default.svc.cluster.local
Address: 192.168.62.131
