### DISCUSSION TITLE
Setting up EMQX with docker and SSL via Let's Encrypt

### DISCUSSION THREAD

**Discussion by oscgonfer** [emqx/emqx#12094] [Q&A] [answered]
Hello,

I am setting up an Ubuntu machine with a EMQX broker. I am running it with docker, following the following docker-compose file:

```
services:
  emqx:
    image: emqx:latest
    container_name: emqx
    environment:
      - "EMQX_MQTT__UPGRADE_QOS=true"
      - "EMQX_MQTT__MQUEUE_STORE_QOS0=true"
      - "EMQX_MQTT__SESSION_EXPIRY_INTERVAL=960h"
      - "EMQX_MQTT__MAX_MQUEUE_LEN=10000000"
      - "EMQX_NODE__COOKIE=sc_emqx"
      - "EMQX_ALLOW_ANONYMOUS=false"
      - "EMQX_LISTENER__SSL__KEYFILE=/opt/emqx/etc/certs/privkey.pem"
      - "EMQX_LISTENER__SSL__CERTFILE=/opt/emqx/etc/certs/fullchain.pem"
      - "EMQX_LISTENER__WSS__KEYFILE=/opt/emqx/etc/certs/privkey.pem"
      - "EMQX_LISTENER__WSS__CERTFILE=/opt/emqx/etc/certs/fullchain.pem"
      - "EMQX_DASHBOARD__LISTENERS__HTTP__ENABLE=true"
      - "EMQX_DASHBOARD__LISTENERS__HTTP__BIND=18083"
      - "EMQX_DASHBOARD__LISTENERS__HTTP__MAX_CONNECTIONS=5"
      - "EMQX_DASHBOARD__LISTENERS__HTTPS__ENABLE=true"
      - "EMQX_DASHBOARD__LISTENERS__HTTPS__BIND=18084"
      - "EMQX_DASHBOARD__LISTENERS__HTTPS__MAX_CONNECTIONS=5"
      - "EMQX_DASHBOARD__LISTENERS__HTTPS__KEYFILE=/opt/emqx/etc/certs/privkey.pem"
      - "EMQX_DASHBOARD__LISTENERS__HTTPS__CERTFILE=/opt/emqx/etc/certs/fullchain.pem"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 3g
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
      - 18084:18084
    volumes:
      - "/etc/letsencrypt/live/$DOMAIN/fullchain.pem:/opt/emqx/etc/certs/fullchain.pem"
      - "/etc/letsencrypt/live/$DOMAIN/privkey.pem:/opt/emqx/etc/certs/privkey.pem"
      - "/root/emqx/etc/acl.conf:/opt/emqx/etc/acl.conf"
      - "/root/emqx/log:/opt/emqx/log"
```

I am using Let's encrypt `certbot` to manage my certificates. Both fullchain and privkey pems are in the live/archive of letsencrypt:

```
lrwxrwxrwx 1 root root   52 Dec  4 14:36 cert.pem -> ../../archive/<DOMAIN>/cert3.pem
lrwxrwxrwx 1 root root   53 Dec  4 14:36 chain.pem -> ../../archive/<DOMAIN>/chain3.pem
lrwxrwxrwx 1 root root   57 Dec  4 14:36 fullchain.pem -> ../../archive/<DOMAIN>/fullchain3.pem
lrwxrwxrwx 1 root root   55 Dec  4 14:36 privkey.pem -> ../../archive/<DOMAIN>/privkey3.pem
```

And after [following this answer](https://github.com/emqx/emqx/issues/2335#issuecomment-632210773), I made a script that makes those files readable by emqx:

```
-rw-r--r-- 1 emqx emqx 1801 Dec  4 14:36 cert3.pem
-rw-r--r-- 1 emqx emqx 3750 Dec  4 14:36 chain3.pem
-rw-r--r-- 1 emqx emqx 5551 Dec  4 14:36 fullchain3.pem
-rw-r----- 1 emqx emqx 1708 Dec  4 14:36 privkey3.pem
```

This is the script I used:

```
#!/bin/bash
DOMAIN=<DOMAIN>
USER='emqx'
user_exists(){ id "$1" &>/dev/null; } # silent, it just sets the exit code
if user_exists $USER; code=$?; then  # use the function, save the code
    echo "$USER exists. Skipping" 
else
    echo 'user not found' >&2  # error messages should go to stderr
    useradd emqx
fi

echo 'chmods...'
chmod 0755 /etc/letsencrypt/{live,archive}
chgrp $USER /etc/letsencrypt/live/$DOMAIN/privkey.pem
chgrp $USER /etc/letsencrypt/archive/$DOMAIN/privkey1.pem
chmod 0640 /etc/letsencrypt/live/$DOMAIN/privkey.pem
chmod 0640 /etc/letsencrypt/archive/$DOMAIN/privkey1.pem

echo 'chown to EMQX...'
chown emqx:emqx /etc/letsencrypt/live/$DOMAIN/*.pem
echo 'Done'
```

I also set up a post renewal-hook for let's encrypt that calls that script and restarts the docker so that certificates are reloaded.

Now, the issue is that I get a `PR_END_OF_FILE_ERROR` and I can't set visit the dashboard on 18084 nor send data via 8883.
Logs show nothing out of the ordinary:

```
$ docker logs emqx --follow
EMQX_DASHBOARD__LISTENERS__HTTP__MAX_CONNECTIONS [dashboard.listeners.http.max_connections]: 5
EMQX_DASHBOARD__LISTENERS__HTTP__BIND [dashboard.listeners.http.bind]: 18083
EMQX_RPC__PORT_DISCOVERY [rpc.port_discovery]: manual
EMQX_NODE__COOKIE [node.cookie]: ******
EMQX_NODE__NAME [node.name]: emqx@172.18.0.2
Listener ssl:default on 0.0.0.0:8883 started.
Listener tcp:default on 0.0.0.0:1883 started.
Listener ws:default on 0.0.0.0:8083 started.
Listener wss:default on 0.0.0.0:8084 started.
Listener http:dashboard on :18083 started.
Listener https:dashboard on :18084 started.
EMQX 5.3.2 is running now!
```

And interestingly, in the container, these are the permissions:

```
drwxrwxr-x 1 emqx emqx 4096 Dec  4 14:57 .
drwxrwxr-x 1 emqx emqx 4096 Nov 30 17:11 ..
-rw-rw-r-- 1 emqx emqx   38 Nov 30 17:07 README
-rw-rw-r-- 1 emqx emqx 1212 Nov 30 17:07 cacert.pem
-rw-rw-r-- 1 emqx emqx 1127 Nov 30 17:07 cert.pem
-rw-rw-r-- 1 emqx emqx 1127 Nov 30 17:07 client-cert.pem
-rw-rw-r-- 1 emqx emqx 1679 Nov 30 17:07 client-key.pem
-rw-r--r-- 1  111  115 5551 Dec  4 14:36 fullchain.pem
-rw-rw-r-- 1 emqx emqx 1675 Nov 30 17:07 key.pem
-rw-r----- 1  111  115 1708 Dec  4 14:36 privkey.pem
```

So the questions are:

* what I am missing?
* is it necessary to do a `docker restart emqx` in the let's encrypt post renewal hook?

Thank you in advance for

**Comment by id** [comment, marked as answer]
It looks like you have `emqx` user on the host with different id than what is in container.
In `emqx:latest` id of `emqx` user is 1000:

```
docker run -it --rm emqx:latest id
uid=1000(emqx) gid=1000(emqx) groups=1000(emqx)
```

The simplest way to solve it is to delete emqx user and group on your host, and create it again with id=1000.

**Reply by oscgonfer** [reply]
aha! That did it:

```
deluser emqx
```

```
useradd emqx -u 1000
```

Then run the script above to chown again of certificates.

Last question:
* do we need to restart the container everytime we renew the certificates?

**Reply by id** [reply]
No, this should not require restart.

**Reply by oscgonfer** [reply]
I am then missing something. I did the test by forcing the renewal of the SSL Certificate.

BEFORE renewal:

```
certbot certificates
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Found the following certs:
  Certificate Name: mqtt-staging.smartcitizen.me
    Domains: mqtt-staging.smartcitizen.me
    Expiry Date: 2024-03-03 13:36:17+00:00 (VALID: 89 days)
    Certificate Path: /etc/letsencrypt/live/mqtt-staging.smartcitizen.me/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/mqtt-staging.smartcitizen.me/privkey.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

This coincides with the certificate you get when you visit https://mqtt-staging.smartcitizen.me:18084/

Renewal:

```
certbot renew --force-renewal
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/mqtt-staging.smartcitizen.me.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Plugins selected: Authenticator manual, Installer None
Renewing an existing certificate

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
new certificate deployed without reload, fullchain is
/etc/letsencrypt/live/mqtt-staging.smartcitizen.me/fullchain.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/mqtt-staging.smartcitizen.me/fullchain.pem (success)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Running post-hook command: /etc/letsencrypt/renewal-hooks/post/setCerts.sh
Output from post-hook command setCerts.sh:
emqx exists. Skipping
chmods...
uid=1000(emqx) gid=1000(emqx) groups=1000(emqx)
chown to EMQX...
Done
```

The time of this new certificate:

```
certbot certificates
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Found the following certs:
  Certificate Name: mqtt-staging.smartcitizen.me
    Domains: mqtt-staging.smartcitizen.me
    Expiry Date: 2024-03-03 15:14:41+00:00 (VALID: 89 days)
    Certificate Path: /etc/letsencrypt/live/mqtt-staging.smartcitizen.me/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/mqtt-staging.smartcitizen.me/privkey.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

Which is still not picked up

**Reply by id** [reply]
Could you check that the `/opt/emqx/etc/certs/fullchain.pem` inside the container is indeed the new one?

**Reply by oscgonfer** [reply]
Hi,

They are. This is what I did:

```
docker cp emqx:/opt/emqx/etc/certs/fullchain.pem .
```

First I compare the renewed file, then the old file:

```
root@mqtt:~# cmp --silent fullchain.pem /etc/letsencrypt/archive/mqtt-staging.smartcitizen.me/fullchain4.pem || echo "files are different"
root@mqtt:~# cmp --silent fullchain.pem /etc/letsencrypt/archive/mqtt-staging.smartcitizen.me/fullchain3.pem || echo "files are different"
files are different
```

**Reply by id** [reply]
Weird. I'll try to test this tomorrow.

**Reply by id** [reply]
@oscgonfer sorry it took a little longer than "tomorrow".

I've tested this on a fresh Ubuntu 22.04 and EMQX 5.3.2. New certificates were picked up by emqx within 30 seconds.

I created `/etc/emqx/certs` manually on the host machine:
```
mkdir -p /etc/emqx/certs
chown -R 1000 /etc/emqx
```

docker-compose.yaml:
```
services:
  emqx:
    image: emqx:latest
    container_name: emqx
    environment:
      - "EMQX_LISTENERS__SSL__DEFAULT__BIND=8883"
      - "EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__KEYFILE=/etc/emqx/certs/privkey.pem"
      - "EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__CERTFILE=/etc/emqx/certs/fullchain.pem"
      - "EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__CACERTFILE=/etc/emqx/certs/fullchain.pem"
      - "EMQX_LISTENERS__WSS__DEFAULT__SSL_OPTIONS__KEYFILE=/etc/emqx/certs/privkey.pem"
      - "EMQX_LISTENERS__WSS__DEFAULT__SSL_OPTIONS__CERTFILE=/etc/emqx/certs/fullchain.pem"
      - "EMQX_LISTENERS__WSS__DEFAULT__SSL_OPTIONS__CACERTFILE=/etc/emqx/certs/fullchain.pem"
      - "EMQX_DASHBOARD__LISTENERS__HTTP__ENABLE=true"
      - "EMQX_DASHBOARD__LISTENERS__HTTP__BIND=18083"
      - "EMQX_DASHBOARD__LISTENERS__HTTPS__ENABLE=true"
      - "EMQX_DASHBOARD__LISTENERS__HTTPS__BIND=18084"
      - "EMQX_DASHBOARD__LISTENERS__HTTPS__SSL_OPTIONS__KEYFILE=/etc/emqx/certs/privkey.pem"
      - "EMQX_DASHBOARD__LISTENERS__HTTPS__SSL_OPTIONS__CERTFILE=/etc/emqx/certs/fullchain.pem"
      - "EMQX_DASHBOARD__LISTENERS__HTTPS__SSL_OPTIONS__CACERTFILE=/etc/emqx/certs/fullchain.pem"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
      - 18084:18084
    volumes:
      - "/etc/emqx/certs:/etc/emqx/certs:ro"
```

/etc/letsencrypt/renewal-hooks/post/emqx.sh:
```
#!/usr/bin/env bash

set -eou pipefail

DOMAIN=<domain>
cp -L /etc/letsencrypt/live/$DOMAIN/*.pem /etc/emqx/certs/
chown 1000 /etc/emqx/certs/*.pem
```
