### DISCUSSION TITLE
Support for User Credentials authentication via Environment Variables for V5

### DISCUSSION THREAD

**Discussion by amoscatelli** [emqx/emqx#12496] [Ideas]
It seems currently is not possible to have an outofthebox/easy way to create a container of EMQX v5 with predefined credentials :
https://github.com/emqx/emqx/discussions/9142
https://www.emqx.io/forum/t/configurations-missing-in-version-5/417

This prevents applications to migrate to V5, since V4 simply supported this :

```
version: '3'
services:
  service:
    image: emqx/emqx:4.4.19
    restart: always
    network_mode: host
    environment:
      - EMQX_ALLOW_ANONYMOUS=false
      - EMQX_AUTH__MNESIA__PASSWORD_HASH=plain
      - EMQX_AUTH__USER__1__USERNAME=XXX
      - EMQX_AUTH__USER__1__PASSWORD=YYY
      - EMQX_AUTH__USER__2__USERNAME=ZZZ
      - EMQX_AUTH__USER__2__PASSWORD=WWW
      - EMQX_LOADED_PLUGINS=emqx_auth_mnesia
```

Is this ever going to be supported again ? Or already in roadmap ?

Thank you
