### DISCUSSION TITLE
EMQX 5.7.0 Official Docker Image

### DISCUSSION THREAD

**Discussion by ennc0d3** [emqx/emqx#13142] [General]
I am using Kubernetes EMQX Operator to install 5.7.0 (OpenSource) version of EMQX with the following EMQX CRD,

```
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
  namespace: emqx
spec:
  image: "emqx:5.7.0"
  imagePullPolicy: IfNotPresent
  revisionHistoryLimit: 3
  updateStrategy:
    type: Recreate        
  # Configuration Reference: https://www.emqx.io/docs/en/v5.6.1/hocon/
  config:
    data: |
 ....
```

The EMQX nodes doesn't come up as the official docker images are not published under library/emqx:5.7.0 where as I see under emqx/emqx:5.7.0.

The question which is the correct repo to use? 

Note: For example for v5.4.1 (CE) I see the version published in docker official repo and emqx organisation repo are different.

Please let me know, Thanks Naga
