### DISCUSSION TITLE
Update EMQx

### DISCUSSION THREAD

**Discussion by arcarmona** [emqx/emqx#13228] [Q&A] [answered]
Hello,

Just a quick question, when using EMQx in Kubernetes with EMQx Operator, if I wanted to run some updates on a runnning cluster like:

- Increase replicas from 2 to 3
- Increase cpu resources to 2 for example
- Finally update to the latest version of emqx

What would be the best way to achieve this? I have been testing with kubectl patch doing each update separately but only managed to update to the latest version of emqx, the remaining two patches ended up crashing. Specifically the replicas update seemed to work as a new statefulset was created with 3 replicas but after a while some of the nodes just crashed leaving the third one as the only functional.

Steps to reproduce would be creating a simple cluster, I set up the blue green deployment as in the docs and ran the below patch:

```
updateStrategy:
    evacuationStrategy:
      connEvictRate: 1000
      sessEvictRate: 1000
      waitTakeover: 10
    initialDelaySeconds: 10
    type: Recreate
```

`kubectl patch emqx emqx --type=merge -p '{"spec": {"coreTemplate": {"spec": {"replicas": 3}}}}'`

Thanks
