### DISCUSSION TITLE
OpenTelemetry integration with Uptrace

### DISCUSSION THREAD

**Discussion by nsteinmetz** [emqx/emqx#13325] [Q&A]
Using EMX 5.4.1, I added the required configuration to enable OpenTelemetry integration

```
opentelemetry {
  exporter { endpoint = "http://localhost:4317" }
  metrics {
    enable = true
    interval = "10s"
  }
  logs {
    enable = true
    level = warning
  }
}
```

On opentelemetry-collector side, I have:

```yaml
exporters:
  debug: null
  otlp/uptrace:
    endpoint: https://otlp.uptrace.dev:4317
    headers:
      uptrace-dsn: https://<TOKEN>@api.uptrace.dev?grpc=4317
    tls:
      insecure: false
processors:
  batch:
    send_batch_size: 10000
    timeout: 10s
  cumulativetodelta: null
  resourcedetection:
    detectors:
    - env
    - system
receivers:
  hostmetrics:
    scrapers:
      cpu: null
      disk: null
      filesystem: null
      load: null
      memory: null
      network: null
      paging: null
      processes: null
  otlp:
    protocols:
      grpc: null
      http: null
service:
  pipelines:
    logs:
      exporters:
      - otlp/uptrace
      - debug
      processors:
      - batch
      receivers:
      - otlp
    metrics:
      exporters:
      - otlp/uptrace
      - debug
      processors:
      - cumulativetodelta
      - batch
      receivers:
      - otlp
    metrics/host:
      exporters:
      - otlp/uptrace
      - debug
      processors:
      - cumulativetodelta
      - batch
      - resourcedetection
      receivers:
      - hostmetrics
    traces:
      exporters:
      - otlp/uptrace
      - debug
      processors:
      - batch
      receivers:
      - otlp
```

But it seems that nothing goes up to uptrace : no metrics, nor logs from emqx whereas hostmetrics are correctly sent to uptrace.

From my understanding, EMQX should push its metrics to otel-collector  on port 4137 and then it should be sent to uptrace.

Any idea of what is missing ?

Thanks !
