### DISCUSSION TITLE
Conditional envs using helm

### DISCUSSION THREAD

**Discussion by dargolith** [emqx/emqx#13364] [Q&A]
Hello,

I'm using EMQX as a sub-chart (dependency) to the umbrella chart for my microservice stack.

I wish to enable authentication methods for my EMQX instance. My two problems are:
1) I wish to conditionally add configuration for auth methods, only if `global.auth.enabled` in my chart is `true`.
2) I need to inject the release-name or namespace (same in my case) for that particular deployment for the JWKS-endpoint and http-endpoint.

The variables I want to add to the ConfigMap are:

```yaml
emqx:
  emqxConfig:
    EMQX_AUTHENTICATION__1__ENABLE: "true"
    EMQX_AUTHENTICATION__1__ENDPOINT: https://keycloak.mydomain.com/realms/{{ .Release.Name }}/protocol/openid-connect/certs
    EMQX_AUTHENTICATION__1__FROM: password
    EMQX_AUTHENTICATION__1__MECHANISM: jwt
    EMQX_AUTHENTICATION__1__POOL_SIZE: "8"
    EMQX_AUTHENTICATION__1__REFRESH_INTERVAL: "300"
    EMQX_AUTHENTICATION__1__USE_JWKS: "true"
    EMQX_AUTHENTICATION__2__BACKEND: http
    EMQX_AUTHENTICATION__2__BODY: '{"id":"${username}","token":"${password}"}'
    EMQX_AUTHENTICATION__2__ENABLE: "true"
    EMQX_AUTHENTICATION__2__MECHANISM: password_based
    EMQX_AUTHENTICATION__2__METHOD: post
    EMQX_AUTHENTICATION__2__URL: http://{{ .Release.Name }}-authenticator/validateMqttCredentials
```

Note the two places where I have `{{ .Release.Name }}` placeholders above. It works fine if I hard-code these values into my `values.yaml`.

So I both need to inject those values at deploy-time and I want to be able to inactivate all authentication methods (not load any) if `global.auth.enabled` is set to `false`. With templating it would be easy, but I see no possibility in the chart to provide a custom ConfigMap.

Any suggestions on how I can conditionally override these values?

**------------ UPDATE ------------**

To try to be even more clear, the config below is a quite common approach, which would have worked if the EMQX-chart allowed providing your own existing ConfigMap for additional envs.

ConfigMap
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: emqx-additional-envs
  namespace: {{ .Release.Namespace }}
  labels: {{ include "app.labels" . | nindent 4 }}
data:
  ...
  {{- if .Values.global.auth.enabled }}
  EMQX_AUTHENTICATION__1__ENABLE: "true"
  EMQX_AUTHENTICATION__1__ENDPOINT: https://keycloak.mydomain.com/realms/{{ .Release.Names }}/protocol/openid-connect/certs
  EMQX_AUTHENTICATION__1__FROM: password
  EMQX_AUTHENTICATION__1__MECHANISM: jwt
  EMQX_AUTHENTICATION__1__POOL_SIZE: "8"
  EMQX_AUTHENTICATION__1__REFRESH_INTERVAL: "300"
  EMQX_AUTHENTICATION__1__USE_JWKS: "true"
  EMQX_AUTHENTICATION__2__BACKEND: http
  EMQX_AUTHENTICATION__2__BODY: '{"id":"${username}","token":"${password}"}'
  EMQX_AUTHENTICATION__2__ENABLE: "true"
  EMQX_AUTHENTICATION__2__MECHANISM: password_based
  EMQX_AUTHENTICATION__2__METHOD: post
  EMQX_AUTHENTICATION__2__URL: http://{{ .Release.Names }}-authenticator/validateMqttCredentials
  {{- end }}
```

values.yaml
```yaml
global:
  auth:
    enabled: true
...

emqx:
  existingConfigMap: emqx-additional-envs
...
```

In the current EMQX chart it only seems to be possible to set envs via `values.yaml`, however, which doesn't allow for conditional values or logic.

**Comment by zmstone** [comment]
Do you want to  have `EMQX_global__auth__enabled=true|false` to control other `EMQX_AUTHENTICATION__*` overrides (note, it's more accurate as 'overrides' than 'injections'). 
This is not quite easy to support, there is no built-in conditioning for overrides.

You can try this maybe try to put all configs in one environment variable like below:
```
EMQX_AUTHENTICATION: "[{enable=true,mechanism=jwt,...},{enable=true,mechanism=http,...}]"
```

edit:
I mean, `EMQX_AUTHENTICATION: {{ Release.authentication }}` and `authentication` in values.yaml can be `[{enable=true,mechanism=jwt,...},{enable=true,mechanism=http,...}]`

**Reply by dargolith** [reply]
@zmstone Not 100% sure what you mean, but when I talk about `global.auth.enabled` I mean in my own chart. I.e. I need to be able to control if I want to run my stack with auth enabled or not. And since I handle the MQTT-auth in EMQX (using jwks and http), I need to be able to switch these plugins on when my chart is configured for auth and off when it is not.

If there is a better way of enabling auth-plugins in EMQX than setting the envs I have set I'm interested in that, since I'm not totally sure how it is supposed to be done.

My problem is that I can't conditionally enable the plugins / auth methods in EMQX depending on values in my chart.

One way of supporting this would be if EMQX would provide an option to specify your own ConfigMap for additional envs / configuration, because then I would be able to build that ConfigMap with conditional values. Right now I can only statically set envs in my own values.yaml file for the EMQX subchart to use, which is quite limiting.

So, short recap. I want to set a variable in my chart to disable auth for my whole stack, and I would like to load auth methods in EMQX depending on that variable in my chart, plus use the release-name in the endpoints for that auth config.

**Reply by dargolith** [reply]
Updated my question with an example how this could have been solved using a custom, existing, ConfigMap (which is quite common).

That might provide a better view of what I'm trying to accomplish.

**Reply by id** [reply]
ping @Rory-Z

**Comment by zmstone** [comment]
> but when I talk about global.auth.enabled I mean in my own chart. 

Sorry I misunderstood.

Thank you for the clarification.
To extend values.yaml, I need help from @Rory-Z

**Comment by dargolith** [comment]
Here is an update.

After inspecting the StatefulSet of the EMQX-chart further I found that you can actually provide your own Secret to set envs from.

This is a little hacky and not so nice, but you can actually utilize that to inject your config. The reason it is ugly is that Secrets are made for, well, secrets and all the values need to be base64 encoded.

This actually works for me right now however:

emqx-secret.yaml
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: emqx-extra-envs
  namespace: {{ .Release.Namespace }}
  labels: {{ include "app.labels" . | nindent 4 }}
data:
  {{- if .Values.global.auth.enabled }}
  EMQX_AUTHENTICATION__1__ENABLE: {{ "true" | b64enc }}
  EMQX_AUTHENTICATION__1__ENDPOINT: {{ (printf "%s/realms/%s/protocol/openid-connect/certs" .Values.authProviderUrl .Release.Name) | b64enc }}
  EMQX_AUTHENTICATION__1__FROM: {{ "password" | b64enc }}
  EMQX_AUTHENTICATION__1__MECHANISM: {{ "jwt" | b64enc }}
  EMQX_AUTHENTICATION__1__POOL_SIZE: {{ "8" | b64enc }}
  EMQX_AUTHENTICATION__1__REFRESH_INTERVAL: {{ "300" | b64enc }}
  EMQX_AUTHENTICATION__1__USE_JWKS: {{ "true" | b64enc }}
  EMQX_AUTHENTICATION__2__BACKEND: {{ "http" | b64enc }}
  EMQX_AUTHENTICATION__2__BODY: {{ "{\"id\":\"${username}\",\"token\":\"${password}\"}" | b64enc }}
  EMQX_AUTHENTICATION__2__ENABLE: {{ "true" | b64enc }}
  EMQX_AUTHENTICATION__2__MECHANISM: {{ "password_based" | b64enc }}
  EMQX_AUTHENTICATION__2__METHOD: {{ "post" | b64enc }}
  EMQX_AUTHENTICATION__2__URL: {{ (printf "http://%s-authenticator/validateMqttCredentials" .Release.Name) | b64enc }}
  {{- end }}
```

values.yaml
```yaml
...
emqx:
  envFromSecret: emqx-extra-envs
...
```

So, as stated, the only problem with this approach is:
1) It is not secrets I store in the Secret
2) I have to base64 encode all values

A ConfigMap would have been more correct and nicer, perhaps that is something you should consider to add to the chart as a way of providing additional configuration.
