### DISCUSSION TITLE
eaddrinuse error while using docker compose with emqx.conf

### DISCUSSION THREAD

**Discussion by rsemihkoca** [emqx/emqx#13465] [Q&A] [answered]
**Issue Description:**
I'm trying to create a secure example of EMQX with SSL and HTTPS using Docker Compose. Below, I'm sharing my Docker Compose file and `emqx.conf` file.

**Problem:**
I'm consistently encountering the error:
```
emqx | Failed to start listener ssl:my_ssl_listener_name on 127.0.0.1:8883: {{shutdown,{failed_to_start_child,listener,eaddrinuse}},...}
```

**docker-compose.yml:**
```yaml
services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    restart: always
    ports:
      - "8883:8883"    # MQTT over SSL/TLS Port
      - "18084:18084"  # Dashboard HTTPS Port
    # environment: (commented out for brevity)
    networks:
      emqx_net:
        aliases:
          - emqx.local
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
      - emqx_etc:/opt/emqx/etc
      - ./emqx_conf/emqx.conf:/opt/emqx/etc/emqx.conf
      - ./certs:/opt/emqx/etc/certs

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: Europe/Istanbul
      WEBPASSWORD: admin
      FTLCONF_LOCAL_IPV4: 192.168.1.61
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - emqx_net

volumes:
  emqx_data:
  emqx_log:
  emqx_etc:

networks:
  emqx_net:
    driver: bridge
```

**emqx.conf:**
```conf
node {
    name = "emqx@node1.emqx.io"
    cookie = "Yzc0NGExM2Rj"
    role = core
    process_limit = 2097152
    max_ports = 1048576
    dist_buffer_size = 8192
    data_dir = "data"
    global_gc_interval = 15m
}

dashboard {
    token_expired_time = 60m
    cors = false
    listeners.https {
        bind = "0.0.0.0:18084"
        ssl_options {
            certfile = "${EMQX_ETC_DIR}/certs/cert.pem"
            keyfile = "${EMQX_ETC_DIR}/certs/key.pem"
            cacertfile = "${EMQX_ETC_DIR}/certs/cacert.pem"
        }
        num_acceptors = 8
        max_connections = 512
        backlog = 1024
        send_timeout = 10s
        inet6 = false
        ipv6_v6only = false
        proxy_header = false
    }
}

listeners.ssl.my_ssl_listener_name {
    bind = "127.0.0.1:8883"
    enabled = true
    acceptors = 16
    enable_authn = true
    max_connections = infinity
    tcp_options {
        active_n = 100
        backlog = 1024
        buffer = 4KB
        high_watermark = 1MB
        keepalive = none
        nodelay = true
        reuseaddr = true
        send_timeout = 15s
        send_timeout_close = true
    }
    ssl_options {
        cacertfile = "${EMQX_ETC_DIR}/certs/cacert.pem"
        certfile = "${EMQX_ETC_DIR}/certs/cert.pem"
        keyfile = "${EMQX_ETC_DIR}/certs/key.pem"
        verify = verify_peer
        fail_if_no_peer_cert = true
        reuse_sessions = true
        depth = 10
        versions = [tlsv1.3, tlsv1.2]
        ciphers = "TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,ECDHE-RSA-AES256-GCM-SHA384"
        secure_renegotiate = true
        log_level = all
        hibernate_after = 5s
        honor_cipher_order = true
        client_renegotiation = true
        handshake_timeout = 15s
    }
    access_rules = [
        "allow 192.168.1.0/24",
        "deny all"
    ]
}

log.file {
    enable = false
    level = warning
    formatter = text
    time_offset = system
    rotation_count = 10
    rotation_size = 50MB
}

log.console {
    enable = true
    level = debug
    formatter = text
}
```

*As a base, I examined the emqx examples on github. I want the broker to be accessed only from the same network, so I added an extra allow rule.

*I would appreciate any assistance or insights regarding the `eaddrinuse` error in my setup.*
