### DISCUSSION TITLE
Prometheus: Scrape Topic Messages

### DISCUSSION THREAD

**Discussion by marvin-steinke** [emqx/emqx#13585] [Q&A] [answered]
Is it possible for prometheus to scrape messages from a specific topic? I have deployed the emqx operator on kubernetes according to your guide and am running the open source version 5 like this:
<details>
<summary>eqmx.yaml</summary>

```
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
  namespace: emqx-operator-system
spec:
  image: emqx:5
  config:
    data: |
      prometheus {
        push_gateway_server = "http://prometheus-pushgateway:9091"
        interval = 500ms
        headers {}
        job_name = "${name}/instance/${name}~${host}"
      }
  dashboardServiceTemplate:
    enabled: true
    metadata:
      name: emqx-dashboard
    spec:
      type: LoadBalancer
      selector:
        app: emqx-dashboard
      ports:
        - name: dashboard-listeners-http-bind
          protocol: TCP
          port: 18083
          targetPort: 18083
  listenersServiceTemplate:
    metadata:
      name: emqx-listeners
    spec:
      type: LoadBalancer
      ports:
        - name: tcp-default
          protocol: TCP
          port: 1883
          targetPort: 1883

```
</details>

Alternatively I could write a prometheus exporter myself that subscribes to the specific topic but if emqx already supports this, I wouldn't want to reinvent the wheel.

In #5866 a similiar topic about the metrics of a topic was discussed, but I don't think these metrics include the messages...
