### DISCUSSION TITLE
Q&A EMQX Configuration in Docker and Integrating ACL with MongoDB in Version 5

### DISCUSSION THREAD

**Discussion by d4ndres** [emqx/emqx#13709] [Q&A]
# Docker Environment EMQX:5 Q&A

First of all, I want to congratulate you on the incredible work you’ve done with this project. I deeply admire the effort and dedication behind each new version. I firmly believe in the potential of version 5 over version 4, and I’m excited about what the future holds.

While exploring version 5, I’ve encountered some challenges that I’d like to discuss and clarify. Specifically, I need more information on how to optimize EMQX configuration directly from Docker and how to integrate ACL rules with MongoDB.

## 1. Docker Environment
How can I configure the cluster.hocon and acl.conf files directly within docker-compose? I understand this is closely related to the environment settings, but how can I achieve this initial configuration without using the frontend? Is it possible to fully configure this from Docker?

### docker-compose
``` 
services:

  mongodb:
    container_name: mongoDB
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - 27017:27017  
    volumes:
      - ./mongoDB/db:/data/db
      - ./mongoDB/configdb:/data/configdb
    environment:
      TZ: "America/Bogota"
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass


  emqx:
    depends_on:
      - mongodb
    container_name: ${nameproject}
    image: emqx:5.7.2
    restart: always
    ports:
      - ${emqxdashport}:18083
      - 8083:8083
    volumes:
      - ./emqx-data:/opt/emqx/data
      - ./emqx-log:/opt/emqx/log
    environment:
      TZ: "America/Bogota"
      EMQX_DASHBOARD__DEFAULT_PASSWORD: superAdmin
      EMQX_NODE__NAME: foo_emqx@${nameproject}
```
### cluster.hocon
```
authentication = [
  {
    backend = mongodb
    collection = mqtt_user
    database = emqx_auth
    enable = true
    filter {
      username = "${username}"
    }
    is_superuser_field = is_superuser
    mechanism = password_based
    mongo_type = single
    password = pass
    password_hash_algorithm {name = plain, salt_position = disable}
    password_hash_field = password
    pool_size = 8
    salt_field = salt
    server = "mongoDB:27017"
    srv_record = false
    ssl {
      ciphers = []
      depth = 10
      enable = false
      hibernate_after = "5s"
      log_level = notice
      reuse_sessions = true
      secure_renegotiate = true
      verify = verify_peer
      versions = [
        "tlsv1.3",
        "tlsv1.2"
      ]
    }
    topology {
      connect_timeout_ms = "20s"
      heartbeat_frequency_ms = "200s"
      max_overflow = 0
    }
    use_legacy_protocol = "false"
    username = user
  }
]
authorization {
  cache {
    enable = true
    excludes = []
    max_size = 32
    ttl = "1m"
  }
  deny_action = ignore
  no_match = allow
  sources = [
    {
      enable = true
      path = "data/authz/acl.conf"
      type = file
    }
  ]
}
```
### acl.conf
``` 
{allow, all, all, ["${username}/#"]}.
{deny, all, all, ["#"]}.
```

## 2. MongoDB and acl.conf
How can I configure acl.conf to read user records from MongoDB? For example, I would love to enforce subscription and publishing topics based on each record in the collection. What would be the step-by-step process? How do we achieve this in the frontend? Is it possible to do it from docker-compose?

### MongoMqttUser
```
{
  "_id": {
    "$oid": "66cd7ea716491fa12b9a5389"
  },
  "username": "turing",
  "password_hash": "e99a18c428cb38d5f260853678922e03",
  "salt": "",
  "is_superuser": false,
  "password": "turing",
  "acl": [
    {
      "permission": "allow",
      "action": "subscribe",
      "topic": "device/monitor/1"
    },
    {
      "permission": "allow",
      "action": "publish",
      "topic": "device/control/1"
    }
  ]
}
```
These challenges weren’t an issue in version 4, but I’ve decided to move forward and take on version 5. Although I’m new to this, I’m eager to learn and actively share what I discover.

**Comment by id** [comment]
@d4ndres the first one is simple, create `./emqx-data/configs` and put your `cluster.hocon` there.
For the second one, you don't use acl.conf to manage mongodb authorization, you need to add MongoDB in authorization sources: https://docs.emqx.com/en/emqx/latest/access-control/authz/mongodb.html

**Reply by d4ndres** [reply]
Thank you, @id. You've given me good pointers. I've achieved my objectives.

What I needed was to understand how authentication and authorization could be affected through Docker Compose. I just need to follow the instructions in the two links, although it's not entirely clear how to implement this in Docker Compose by following the documentation.

[https://docs.emqx.com/en/emqx/latest/access-control/authz/mongodb.html](https://docs.emqx.com/en/emqx/latest/access-control/authz/mongodb.html)
[https://docs.emqx.com/en/emqx/latest/configuration/configuration.html#configuration-files](https://docs.emqx.com/en/emqx/latest/configuration/configuration.html#configuration-files)

I'm sharing my Docker Compose file.

```
services:

  mongodb:
    container_name: mongoDB
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: always
    ports:
      - 27017:27017  
    volumes:
      - ./mongoDB/db:/data/db
      - ./mongoDB/configdb:/data/configdb
    environment:
      TZ: "America/Bogota"
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass


  emqx:
    depends_on:
      - mongodb
    container_name: ${nameproject}
    image: emqx:5.7.2
    restart: always
    ports:
      - ${emqxdashport}:18083
      - 8083:8083
    # volumes:
    #   - ./emqx-data:/opt/emqx/data
    #   - ./emqx-log:/opt/emqx/log
    environment:
      TZ: "America/Bogota"
      EMQX_DASHBOARD__DEFAULT_PASSWORD: superAdmin
      
      # authtentication
      EMQX_AUTHENTICATION__1__BACKEND: mongodb
      EMQX_AUTHENTICATION__1__COLLECTION: mqtt_user
      EMQX_AUTHENTICATION__1__DATABASE: emqx_auth
      EMQX_AUTHENTICATION__1__ENABLE: true
      EMQX_AUTHENTICATION__1__FILTER: '{ "username": "$${username}" }'
      EMQX_AUTHENTICATION__1__IS_SUPERUSER_FIELD: is_superuser
      EMQX_AUTHENTICATION__1__MECHANISM: password_based
      EMQX_AUTHENTICATION__1__MONGO_TYPE: single
      EMQX_AUTHENTICATION__1__PASSWORD: pass
      EMQX_AUTHENTICATION__1__USERNAME: user
      EMQX_AUTHENTICATION__1__PASSWORD_HASH_ALGORITHM__NAME: plain
      EMQX_AUTHENTICATION__1__PASSWORD_HASH_ALGORITHM__SALT_POSITION: disable
      EMQX_AUTHENTICATION__1__PASSWORD_HASH_FIELD: password
      EMQX_AUTHENTICATION__1__POOL_SIZE: 8
      EMQX_AUTHENTICATION__1__SALT_FIELD: salt
      EMQX_AUTHENTICATION__1__SERVER: "mongoDB:27017"
      EMQX_AUTHENTICATION__1__SRV_RECORD: false
      EMQX_AUTHENTICATION__1__SSL__ENABLE: false
      EMQX_AUTHENTICATION__1__TOPOLOGY__CONNECT_TIMEOUT_MS: "20s"
      EMQX_AUTHENTICATION__1__TOPOLOGY__HEARTBEAT_FREQUENCY_MS: "200s"
      EMQX_AUTHENTICATION__1__TOPOLOGY__MAX_OVERFLOW: 0
      EMQX_AUTHENTICATION__1__USE_LEGACY_PROTOCOL: "false"
      
      # authorization
      EMQX_AUTHORIZATION__NO_MATCH: deny
      EMQX_AUTHORIZATION__SOURCES__1__COLLECTION: mqtt_acl
      EMQX_AUTHORIZATION__SOURCES__1__DATABASE: emqx_auth
      EMQX_AUTHORIZATION__SOURCES__1__ENABLE: true
      EMQX_AUTHORIZATION__SOURCES__1__FILTER: '{ "username": "$${username}" }'
      EMQX_AUTHORIZATION__SOURCES__1__MONGO_TYPE: single
      EMQX_AUTHORIZATION__SOURCES__1__PASSWORD: pass
      EMQX_AUTHORIZATION__SOURCES__1__POOL_SIZE: 8
      EMQX_AUTHORIZATION__SOURCES__1__SERVER: "mongoDB:27017"
      EMQX_AUTHORIZATION__SOURCES__1__SRV_RECORD: false
      EMQX_AUTHORIZATION__SOURCES__1__SSL__ENABLE: false
      EMQX_AUTHORIZATION__SOURCES__1__TOPOLOGY__CONNECT_TIMEOUT_MS: "20s"
      EMQX_AUTHORIZATION__SOURCES__1__TOPOLOGY__HEARTBEAT_FREQUENCY_MS: "200s"
      EMQX_AUTHORIZATION__SOURCES__1__TOPOLOGY__MAX_OVERFLOW: 0
      EMQX_AUTHORIZATION__SOURCES__1__TYPE: mongodb
      EMQX_AUTHORIZATION__SOURCES__1__USE_LEGACY_PROTOCOL: auto
      EMQX_AUTHORIZATION__SOURCES__1__USERNAME: user
```
