### DISCUSSION TITLE
Environment Variables Not Replacing Config Values in EMQX

### DISCUSSION THREAD

**Discussion by hinahalani19** [emqx/emqx#14866] [Q&A] [answered]
Hello EMQX Community,

I’m facing an issue where environment variables in my EMQX StatefulSet configuration are not being replaced in the emqx.conf file, including the cookie and other settings.

To set the EMQX node cookie, use the following environment variable configuration:

```yaml
env:
  - name: EMQX_NODE__COOKIE
    value: testemqxsecretcookie
```

The relevant part of my emqx.conf file is as follows:
```
node {
  name = "emqx@127.0.0.1"
  cookie = "emqxsecretcookie"
  data_dir = "/var/lib/emqx"
}
```
Despite setting the environment variable, the value does not appear when I check in config file by ssh or run:
`kubectl exec <pod-name> -- emqx_ctl conf show node
`

As a workaround, I considered using the sed command in my entrypoint to replace the cookie value:
`sed -i "s/{{EMQX_NODE__COOKIE}}/$EMQX_NODE__COOKIE/g" /etc/emqx/emqx.conf
`

However, I expected the environment variables to be applied automatically, as mentioned in the EMQX documentation [here](https://docs.emqx.com/en/emqx/latest/configuration/configuration.html#environment-variables).

Here’s a brief overview of my Kubernetes configuration for the EMQX StatefulSet:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emqx-exp-sts
  labels:
    app: emqx-exp
spec:
  #spec
  selector:
    matchLabels:
      app: emqx-exp
  template:
    metadata:
      labels:
        app: emqx-exp
    spec:
      volumes:
      #volumes
      containers:
      - name: emqx-exp
       #image and mount volume details
        env:
        - name: EMQX_NAME
          value: emqx-exp
        - name: EMQX_NODE__COOKIE
          value: testemqxsecretcookie
        # other important env variables
        ports:
        # ports
```

I’m using EMQX open-source version 5.8.4, and I previously faced similar issues with version 5.5.0. Any insights on how to resolve this issue would be greatly appreciated!

Thank you!
