### DISCUSSION TITLE
Persisting Bridge Buffer Messages to Disk

### DISCUSSION THREAD

**Discussion by atx-skn** [emqx/emqx#15028] [Q&A] [answered]
Hi everyone

I'm currently using an EMQX broker (v5.1.1, open source) with a bridge connection to AWS. In the event of a disconnect, the bridge buffers messages until the connection is re-established.

I'm wondering: Is it possible to persist these buffered messages to disk, so that in the event of a broker restart, the messages are not lost and can still be delivered once the connection resumes?

In earlier versions, I believe this was handled using the `bridge.mqtt.aws.queue.replayq_dir` configuration. The [documentation](https://docs.emqx.com/en/emqx/latest/getting-started/new-features.html#overload-protection-limiter-and-buffer-queue-for-bridges) suggests that it's still possible to choose between memory and disk storage for the buffer:

> A generic buffer queue is also added for all bridges, allowing buffer messages generated under stressful conditions. _**This buffer can be configured to store messages in either memory or disk cache when external resources are unavailable**_, such as during network fluctuations or service downtime. Buffered messages will be sent once the service is restored. However, requests in the buffer may expire, which is a big difference compared to version 4. If the amount of buffered data exceeds the limit, it will be discarded following the First In First Out (FIFO) rule.

If disk persistence is still supported in v5.1.1, could anyone provide guidance on how to configure it properly?
Any examples or pointers would be greatly appreciated.

Thanks for your help!

**Comment by id** [comment]
https://docs.emqx.com/en/emqx/v5.8/changes/data-integration-4.4-to-5.1-incompatibility.html#mqtt

> disk_cache = on (in EMQX 4.4) can be considered somewhat equivalent to setting resource_opts.buffer_mode = volatile_offload, but the latter is a hidden configuration option that defaults to memory_only.

**Reply by atx-skn** [reply]
Thanks @id !
I had tested that configuration option earlier, but in my case, all messages appeared to be lost. I created a firewall rule to block all outbound traffic, then sent a few hundred messages. After a short wait, I restarted the computer. Once it came back up, the message queue showed 0 messages, and after re-enabling outbound traffic, I didn’t see any messages arriving in AWS's IOT Core.

Could I be misunderstanding how this configuration is intended to work?

**Reply by id** [reply]
How do you run EMQX? Is it a docker container?

**Reply by atx-skn** [reply]
Using AWS greengrass (aws.greengrass.clientdevices.mqtt.EMQX)

**Reply by id** [reply]
Hard to say what exactly is going on there. AWS is not using our official builds, they have their own fork. It could be they are ignoring this config, or just do not persist directory where EMQX stores this buffer.

**Reply by atx-skn** [reply]
Where would emqx store this buffer? I haven't noticed any changes in the filesystem.

**Reply by id** [reply]
In the `data` directory, same where you have the database.
Most likely then AWS version of EMQX ignores this config.

**Reply by atx-skn** [reply]
Do you create a separate folder for this within the data directory, or are the files stored directly in the database? I ask because the database is functioning and appears to be persistent in the /data/mnesia folder

**Reply by id** [reply]
it's `/data/bufs` directory

**Reply by id** [reply]
but the subdirectory is created after node name, which is constructed from short name + node IP by default. If you get new IP each time EMQX restarts, the data will be effectively lost.

E.g. if I do not override `EMQX_NODE__NAME`, then the directory for buffer on disk will be `/data/bufs/emqx@127.0.0.1/`

**Reply by atx-skn** [reply]
Thanks for your input - it's possible that the AWS fork ignores this configuration or the folder entirely. I wasn't able to locate it anywhere in my filesystem.

To test the setup anyway, I created a simple Docker environment with two EMQX services. The bridge works properly: messages were sent from one broker to the other. When I stopped the second service, the first EMQX instance began buffering messages as expected and even created directories like /data/bufs/emqx@127.21.0.3/....

I let the buffer accumulate around 1000 messages and waited for about 5 minutes before restarting the first (buffering) EMQX broker.  However, after the restart, all buffered messages appeared to be missing and were not delivered to broker2 after it was started.

Am I misunderstanding how buffering and recovery are supposed to work in this setup?

Here's the Docker Compose file I used for testing:
```yml
version: '3.8'
services:
  emqxold:
    container_name: emqxold
    image: emqx/emqx:5.1.1
    ports:
      - "1883:1883"
      - "8083:8083"
      - "18083:18083"
      - "9469:9469"
    volumes:
      - ./data/data:/opt/emqx/data
      - ./data/log:/opt/emqx/log
#     - ./data/etc:/opt/emqx/etc
    environment:
      EMQX_NODE__COOKIE: "your-secret-cookie"
      EMQX_BRIDGES__MQTT__TEST__ENABLE: "true"
      EMQX_BRIDGES__MQTT__TEST__SERVER: "172.21.0.3:1883"
      EMQX_BRIDGES__MQTT__TEST__KEEPALIVE: "50s"
      EMQX_BRIDGES__MQTT__TEST__RETRY_INTERVAL: "15s"
      EMQX_BRIDGES__MQTT__TEST__CLEAN_START: "true"
      EMQX_BRIDGES__MQTT__TEST__BRIDGE_MODE: "false"
      EMQX_BRIDGES__MQTT__TEST__EGRESS__LOCAL__TOPIC: "#"
      EMQX_BRIDGES__MQTT__TEST__EGRESS__POOL_SIZE: "8"
      EMQX_BRIDGES__MQTT__TEST__EGRESS__REMOTE__PAYLOAD: "$${payload}"
      EMQX_BRIDGES__MQTT__TEST__EGRESS__REMOTE__QOS: "1"
      EMQX_BRIDGES__MQTT__TEST__EGRESS__REMOTE__RETAIN: "false"
      EMQX_BRIDGES__MQTT__TEST__EGRESS__REMOTE__TOPIC: "$${topic}"
      EMQX_BRIDGES__MQTT__TEST__MAX_INFLIGHT: "32"
      EMQX_BRIDGES__MQTT__TEST__MODE: "cluster_shareload"
      EMQX_BRIDGES__MQTT__TEST__PROTO_VER: "v5"
      EMQX_BRIDGES__MQTT__TEST__RESOURCE_OPTS__HEALTH_CHECK_INTERVAL: "15s"
      EMQX_BRIDGES__MQTT__TEST__RESOURCE_OPTS__INFLIGHT_WINDOW: "1"
      EMQX_BRIDGES__MQTT__TEST__RESOURCE_OPTS__MAX_BUFFER_BYTES: "4GB"
      EMQX_BRIDGES__MQTT__TEST__RESOURCE_OPTS__QUERY_MODE: "async"
      EMQX_BRIDGES__MQTT__TEST__RESOURCE_OPTS__REQUEST_TTL: "72h"
      EMQX_BRIDGES__MQTT__TEST__RESOURCE_OPTS__START_AFTER_CREATED: "true"
      EMQX_BRIDGES__MQTT__TEST__RESOURCE_OPTS__START_TIMEOUT: "5s"
      EMQX_BRIDGES__MQTT__TEST__RESOURCE_OPTS__WORKER_POOL_SIZE: "4"
      EMQX_BRIDGES__MQTT__TEST__RESOURCE_OPTS__BUFFER_MODE: "volatile_offload"
    networks:
      - emqx-net

  emqxold2:
    container_name: emqxold2
    image: emqx/emqx:5.1.1
    ports:
      - "1884:1883"
      - "8084:8083"
      - "18084:18083"
      - "9468:9469"
    volumes:
        - ./data/data2:/opt/emqx/data
        - ./data/log2:/opt/emqx/log
#       - ./data/etc:/opt/emqx/etc
    environment:
      EMQX_NODE__COOKIE: "your-secret-cookie"
    networks:
      - emqx-net

networks:
  emqx-net:
    driver: bridge
```

The only files that were created in the buffer directory were COMMIT files, and each just contained something like: `#{id => 145702, segno => 1}.`
![grafik](https://github.com/user-attachments/assets/a51b0f87-6780-4f54-938c-857a96bd9161)

**Reply by id** [reply]
As I mentioned above, you need static `EMQX_NODE__NAME`. Try to follow docker compose example from the documentation https://docs.emqx.com/en/emqx/latest/deploy/install-docker-ce.html#use-docker-compose-to-build-an-emqx-cluster.

**Reply by atx-skn** [reply]
I tried using both EMQX_NODE__NAME and EMQX_NODE_NAME as shown in the example. It didn’t change the test result, except that the folder is now named `emqxold@172.21.0.2`.

```yaml
version: '3.8'
services:
  emqxold:
    container_name: emqxold
    image: emqx/emqx:5.1.1
    ports:
      - "1883:1883"
      - "8083:8083"
      - "18083:18083"
      - "9469:9469"
    volumes:
      - ./data/data:/opt/emqx/data
      - ./data/log:/opt/emqx/log
#          - ./data/etc:/opt/emqx/etc
    environment:
      EMQX_NODE__COOKIE: "your-secret-cookie"
      EMQX_BRIDGES__MQTT__TEST__ENABLE: "true"
      EMQX_BRIDGES__MQTT__TEST__SERVER: "172.21.0.3:1883"
      EMQX_BRIDGES__MQTT__TEST__KEEPALIVE: "50s"
      EMQX_BRIDGES__MQTT__TEST__RETRY_INTERVAL: "15s"
      EMQX_BRIDGES__MQTT__TEST__CLEAN_START: "true"
      EMQX_BRIDGES__MQTT__TEST__BRIDGE_MODE: "false"
      EMQX_BRIDGES__MQTT__TEST__EGRESS__LOCAL__TOPIC: "#"
      EMQX_BRIDGES__MQTT__TEST__EGRESS__POOL_SIZE: "8"
      EMQX_BRIDGES__MQTT__TEST__EGRESS__REMOTE__PAYLOAD: "$${payload}"
      EMQX_BRIDGES__MQTT__TEST__EGRESS__REMOTE__QOS: "1"
      EMQX_BRIDGES__MQTT__TEST__EGRESS__REMOTE__RETAIN: "false"
      EMQX_BRIDGES__MQTT__TEST__EGRESS__REMOTE__TOPIC: "$${topic}"
      EMQX_BRIDGES__MQTT__TEST__MAX_INFLIGHT: "32"
      EMQX_BRIDGES__MQTT__TEST__MODE: "cluster_shareload"
      EMQX_BRIDGES__MQTT__TEST__PROTO_VER: "v5"
      EMQX_BRIDGES__MQTT__TEST__RESOURCE_OPTS__HEALTH_CHECK_INTERVAL: "15s"
      EMQX_BRIDGES__MQTT__TEST__RESOURCE_OPTS__INFLIGHT_WINDOW: "1"
      EMQX_BRIDGES__MQTT__TEST__RESOURCE_OPTS__MAX_BUFFER_BYTES: "4GB"
      EMQX_BRIDGES__MQTT__TEST__RESOURCE_OPTS__QUERY_MODE: "async"
      EMQX_BRIDGES__MQTT__TEST__RESOURCE_OPTS__REQUEST_TTL: "72h"
      EMQX_BRIDGES__MQTT__TEST__RESOURCE_OPTS__START_AFTER_CREATED: "true"
      EMQX_BRIDGES__MQTT__TEST__RESOURCE_OPTS__START_TIMEOUT: "5s"
      EMQX_BRIDGES__MQTT__TEST__RESOURCE_OPTS__WORKER_POOL_SIZE: "4"
      EMQX_BRIDGES__MQTT__TEST__RESOURCE_OPTS__BUFFER_MODE: "volatile_offload"
      EMQX_NODE__NAME: "emqxold@172.21.0.2"
    networks:
      - emqx-net

  emqxold2:
    container_name: emqxold2
    image: emqx/emqx:5.1.1
    ports:
      - "1884:1883"
      - "8084:8083"
      - "18084:18083"
      - "9468:9469"
    volumes:
        - ./data/data2:/opt/emqx/data
        - ./data/log2:/opt/emqx/log
#        - ./data/etc:/opt/emqx/etc
    environment:
      EMQX_NODE__COOKIE: "your-secret-cookie"
      EMQX_NODE__NAME: "emqxold2@172.21.0.3"
    networks:
      - emqx-net

networks:
  emqx-net:
    driver: bridge

```
