### DISCUSSION TITLE
How to pre-warm EMQX broker during vertical scaling to prevent dropped messages?

### DISCUSSION THREAD

**Discussion by knut-bw** [emqx/emqx#15103] [Q&A]
I am using an EMQX broker and observing its performance by tracing two specific span types: process_message and send_publish_message.
I conducted an experiment where sending messages at a high rate per second with a payload size of 20KB caused a significant increase in the EMQX broker's CPU utilization. To address this, I performed vertical scaling by patching the Pod's CPU resource limit from 500m to 1 core. This successfully reduced the duration time for both process_message and send_publish_message spans.
However, I encountered a critical issue during the vertical scaling process: some messages were dropped. This seems to happen because the new Pod (with increased resources) is still in the process of starting up and isn't fully ready when the old Pod is terminated as part of the scaling operation.
I would like to know how I can properly "pre-warm" the broker during this vertical scaling process to prevent messages from being dropped.
Below is my current EMQX broker YAML configuration file
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emqx
  namespace: exp
spec:
  serviceName: emqx-headless
  replicas: 1
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: emqx
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - worknode2
      serviceAccountName: emqx
      securityContext:
        fsGroup: 0
        runAsUser: 0
        runAsNonRoot: false
      containers:
        - name: emqx
          resizePolicy:
          - resourceName: cpu
            restartPolicy: NotRequired
          - resourceName: memory
            restartPolicy: RestartContainer
          resources:
            requests:
              cpu: 300m
            limits:
              cpu: 1
              memory: 400Mi
          image: emqx/emqx:5.7.0
          volumeMounts:
            - name: config
              mountPath: /opt/emqx/data/configs/cluster.hocon
              subPath: log.conf
            - name: config
              mountPath: /opt/emqx/etc/emqx.conf
              subPath: log3.conf
          env:
            - name: EMQX_DEFAULT_LOG_HANDLER
              value: "file"
            - name: EMQX_NAME
              value: emqx
            - name: EMQX_CLUSTER_DISCOVERY
              value: k8s
            - name: EMQX_CLUSTER__K8S__SERVICE_NAME
              value: emqx-headless
            - name: EMQX_CLUSTER__K8S__APISERVER
              value: "https://10.1.0.1:6443"
            - name: EMQX_CLUSTER__K8S__NAMESPACE
              value: exp
            - name: EMQX_NODE__COOKIE
              value: "emqxsecretcookie"
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - |
                emqx_ctl status | grep "5.7.0 is started" >/dev/null 2>&1
                      initialDelaySeconds: 15
          lifecycle:
            preStop:
              exec:
                command:
                - sh
                - -c
                - |
                  echo ">> 停止接收新 MQTT 連線…"
                  emqx_ctl listener stop mqtt:1883
                  sleep 5
                  echo ">> 斷開現有連線並移除集群會員…"
                  emqx_ctl clients disconnect all
                  emqx_ctl cluster leave
                  sleep 30
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 5
      volumes:
        - name: data
          hostPath:
            path: /opt/data
        - name: config
          configMap:
            name: emqx-config
        - name: log
          hostPath:
            path: /var/log
        - name: api-key
          configMap:
            name: emqx-api-key
        - name: conf
          configMap:
            name: emqx-conf
      imagePullSecrets:
      - name: regcred
```
