### DISCUSSION TITLE
Can't get Mnesia authentication to work

### DISCUSSION THREAD

**Discussion by ycsin** [emqx/emqx#5668] [Q&A]
Hi,

I'm trying to change the admin password of an emqx node running in docker, but somehow it doesn't work.
I'm trying to follow this tutorial: https://docs.emqx.io/en/broker/v4.3/advanced/auth-mnesia.html

My `docker-compose.yaml` file:

```yaml
version: '3'

volumes:
  vol-emqx-data:
    name: emqx-data
  vol-emqx-etc:
    name: emqx-etc
  vol-emqx-log:
    name: emqx-log

services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    restart: always
    environment:
      EMQX_NAME: emqxs
      EMQX_HOST: 127.0.0.1
    ports:
      - "1884:1883"
      - "8884:8883"
      - "18084:18083"
    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log
```

I've edited the `emqx.conf` file:

```conf
##--------------------------------------------------------------------
## Authentication/Access Control
##--------------------------------------------------------------------

## Allow anonymous authentication by default if no auth plugins loaded.
## Notice: Disable the option in production deployment!
##
## Value: true | false
allow_anonymous = false
```

I have edited the following file:
```
/opt/emqx/etc/plugins/emqx_auth_mnesia.conf
```

to:

```conf
## Password hash.
##
## Value: plain | md5 | sha | sha256 | sha512
auth.mnesia.password_hash = sha256

##--------------------------------------------------------------------
## ClientId Authentication
##--------------------------------------------------------------------

## Examples
##auth.client.1.clientid = client
##auth.client.1.password = passwd

##--------------------------------------------------------------------
## Username Authentication
##--------------------------------------------------------------------

## Examples:
auth.user.1.username = admin
auth.user.1.password = testingpassword
```

I've tried toggling the plugin in the dashboard:
![image](https://user-images.githubusercontent.com/1563974/132282254-d831d30d-b792-492d-994d-30d241deb687.png)

And also restart the docker container by

```shell
docker-compose down
docker-compose up -d
```

But the password for `admin` remains at the default `public`, any idea please?
