### DISCUSSION TITLE
Web Dashboard for static cluster

### DISCUSSION THREAD

**Discussion by seksity** [emqx/emqx#6398] [Q&A] [answered]
I would like to test static cluster by follows:-
[https://docs.emqx.io/en/broker/v4.3/getting-started/install.html#create-a-simple-static-cluster-by-docker-compose](url)

but in static cluster I cannot find any information how to access web dashboard to setting any parameter and plug-ins.

Could you please to provide the information how can I access web dashboard?

**Comment by thalesmg** [comment, marked as answer]
Hi @seksity !

Starting from the example `docker-compose.yaml` config from the docs, you only have to expose the web dashboard port `18083` on one of the nodes.

So, for instance:

```yaml
version: '3'

services:
  emqx1:
    image: emqx/emqx:4.3.10
    ports:
      - 18083:18083
    # the rest is the same
    # ...
```
After starting up your local cluster, you can simply visit `localhost:18083` and access the dashboard.
