### DISCUSSION TITLE
Emqx Cluster Setup

### DISCUSSION THREAD

**Discussion by Suryaobulareddy** [emqx/emqx#6542] [Q&A]
Hi Guys,

I'm trying to setup the emqx cluster with docker by using the below docker-compose.yaml file. I'm unable to do the clustering using the below code.

If any one have idea about this Please help me

Thank You

**docker-compose.yaml**
```yaml
version: '3'
services:
  emqx1:
    image: emqx/emqx:latest
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node1.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io, emqx@node2.emqx.io]"
    networks:
      emqx-bridge:
        aliases:
        - node1.emqx.io

  emqx2:
    image: emqx/emqx:latest
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node2.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io, emqx@node2.emqx.io]"
    networks:
      emqx-bridge:
        aliases:
        - node2.emqx.io

networks:
  emqx-bridge:
    driver: bridge
```

```console
CONTAINER ID   IMAGE              COMMAND                  CREATED              STATUS              PORTS                                                                                                       NAMES
e3d44af49e41   emqx/emqx:latest   "/usr/bin/docker-ent…"   About a minute ago   Up About a minute   1883/tcp, 4369-4370/tcp, 5369/tcp, 6369-6370/tcp, 8081/tcp, 8083-8084/tcp, 8883/tcp, 11883/tcp, 18083/tcp   emqx_emqx2_1
70ad4dd6d318   emqx/emqx:latest   "/usr/bin/docker-ent…"   About a minute ago   Up About a minute   1883/tcp, 4369-4370/tcp, 5369/tcp, 6369-6370/tcp, 8081/tcp, 8083-8084/tcp, 8883/tcp, 11883/tcp, 18083/tcp   emqx_emqx1_1
6d25813d4eb4   rancher/rancher    "entrypoint.sh"          11 days ago          Up About an hour    0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                                                                    naughty_bhaskara
surya@LAPTOP-67BD0R2S:~$ docker exec -it emqx_emqx1_1 sh -c "emqx_ctl cluster status"
Cluster status: #{running_nodes => ['emqx@node1.emqx.io'],stopped_nodes => []}
surya@LAPTOP-67BD0R2S:~$ docker exec -it emqx_emqx2_1 sh -c "emqx_ctl cluster status"
Cluster status: #{running_nodes => ['emqx@node2.emqx.io'],stopped_nodes => []}
surya@LAPTOP-67BD0R2S:~$

**Comment by k32** [comment]
Naming and parsing of some parameters is different in different versions of EMQX. For 4.3 the docker-compose file should look like this:
```
version: '3'
services:
  emqx1:
    image: emqx/emqx:4.3.11
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node1.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io,emqx@node2.emqx.io"
    networks:
      emqx-bridge:
        aliases:
        - node1.emqx.io

  emqx2:
    image: emqx/emqx:4.3.11
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node2.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io,emqx@node2.emqx.io"
    networks:
      emqx-bridge:
        aliases:
        - node2.emqx.io

networks:
  emqx-bridge:
    driver: bridge
```
Please note that `EMQX_CLUSTER__DISCOVERY_STRATEGY` was changed to `EMQX_CLUSTER__DISCOVERY`  and square brackets were removed from STATIC_SEEDS' values.
