### DISCUSSION TITLE
auth http timeout with docker-compose setup

### DISCUSSION THREAD

**Discussion by fabifink** [emqx/emqx#6707] [Q&A] [answered]
Hey,

I'm trying to add `emqx_auth_http` plugin to my broker. Unfortunately in my local docker-compose setup the Authentication request always runs into a timeout:

`[Auth http] Request auth path: /mqtt/auth, error: timeout`

Does Docker DNS resolving work within the `emqx_auth_http` plugin?

For reference here is my `docker-compose.yml`:

```
version: '2.4'
services:
    ########################################################################################
    ## Third party images
    ########################################################################################
    sql-main:
        container_name: solar-sql
        image: mariadb
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: main
        volumes:
            - ./tools/sql/schema.sql:/docker-entrypoint-initdb.d/01.sql
        ports:
            - '3309:3306'
    mqtt-broker:
        container_name: solar-mqtt-broker
        image: emqx/emqx
        environment:
            EMQX_LOADED_PLUGINS: emqx_auth_http
            EMQX_AUTH__HTTP__REQUEST__RETRY_TIMES: 3
            EMQX_AUTH__HTTP__REQUEST__RETRY_INTERVAL: 1s
            EMQX_AUTH__HTTP__REQUEST__RETRY_BACKOFF: 2.0
            EMQX_ALLOW_ANONYMOUS: 'false'
            EMQX_AUTH__HTTP__AUTH_REQ: http://solar-service:8080/mqtt/auth
            EMQX_AUTH__HTTP__AUTH_REQ__METHOD: post
            EMQX_AUTH__HTTP__AUTH_REQ__PARAMS: clientId=%c,username=%u,password=%P
            EMQX_AUTH__HTTP__AUTH_REQ__CONTENT-TYPE: json
        ports:
            - '18083:18083'
            - '1883:1883'
        depends_on:
            - solar-service
    ########################################################################################
    ## Service
    ########################################################################################
    solar-service:
        container_name: solar-service
        command: /bin/sh -c "cd /app/ && npm start"
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            NODE_ENV: 'local'
        volumes:
            - ./:/app
        ports:
            - '8080:8080'
        depends_on:
            - sql-main
```

**Comment by Rory-Z** [comment]
Hi, @fabifink 
I notice you are using the docker compose version for `2.4`, I am not sure if it is too old, I suggest you retry with `3.9`
I also noticed that the compose file you provided is missing the network configuration, so I suggest you create a bridge type network, like the following
```
version: '3.9'

services:
    sql-main:
        container_name: solar-sql
        ...
        networks:
          - emqx_bridge
    mqtt-broker:
        container_name: solar-mqtt-broker
        ...
        networks:
          - emqx_bridge
    solar-service:
        container_name: solar-service
        ...
        networks:
          - emqx_bridge

networks:
  emqx_bridge:
    driver: bridge
```

**Reply by fabifink** [reply]
Hi @Rory-Z,

thanks for taking the time to respond to my question 👍 I do not think that a specific network is needed, as per [docker-compose documentation](https://docs.docker.com/compose/networking/) a default network is created, if none is explicitly specified. The full docker-compose file has an additional service that was able to find the `solar-service` via DNS with no network explicitly defined.

But just to be sure I have tried both of your suggestions (Increasing version number and adding a specific network), but neither of those worked. I'm still running into the mentioned timeout. 

For the matter of completion: I have tried to curl the` solar-service` from an additional simple `node` service with `curl`. Here is the docker-compose definition of this service:

```
    inverter-mock:
        container_name: inverter-mock
        command: /bin/sh -c "cd /app/tools/inverter-mock && npm start"
        image: node:14.6
        environment:
            NODE_ENV: 'local'
        volumes:
            - ./:/app
```

and here is the curl response:
<img width="1012" alt="Screenshot 2022-01-12 at 09 26 15" src="https://user-images.githubusercontent.com/10923693/149091228-2a583c6f-9e4f-4003-8494-66621e9e0dd5.png">

Do you have any other suggestions?
