### DISCUSSION TITLE
emqx_ctl license reload: "Node not responding to pings."

### DISCUSSION THREAD

**Discussion by bwyx** [emqx/emqx#7255] [Q&A]
I've deployed Emqx docker on raspberry pi, everything runs perfectly but I failed to reload my trial license with the following error.

![20220309_20h30m13s_grim](https://user-images.githubusercontent.com/37757388/157451359-ef062578-1628-4de2-b073-58a2893ea87d.png)

The license files are properly mounted.

![20220309_20h31m44s_grim](https://user-images.githubusercontent.com/37757388/157451592-119a5694-3095-4568-8ebc-ef511c168722.png)

this is my docker-compose config

```yml
services:
  emqx:
    container_name: emqx-trial
    image: emqx/emqx:4.3.8
    restart: unless-stopped
    volumes:
      - ./license/emqx.lic:/opt/emqx/etc/emqx.lic
      - ./license/emqx.key:/opt/emqx/etc/emqx.key
```

Nowhere to find a similar issue
