### DISCUSSION TITLE
JWT plugin, deactivate auth.jwt.secret = emqxsecret

### DISCUSSION THREAD

**Discussion by Dimoniq** [emqx/emqx#7579] [Q&A]
Dear emqx community,

I want to use the JWT plugin to validate the token with exclusively JWKS validation.

Is there a way to disable the `auth.jwt.secret` via ENV variables? This setting is ON by default and set to "emqxsecret".  Any trick like using some other env variable to disable it, or setting `EMQX_AUTH__JWT__SECRET` variable to something invalid to skip the secret check and directly validate the token via the JWKS ?

Just do not want to leave the door open for any malicious tokens, whose signatures might match the auth.jwt.secret, if someone finds out the hardcoded key.

## My setup 

I am configuring the broker via environment variables, like:
```yaml
apiVersion: apps.emqx.io/v1beta2
kind: EmqxBroker
metadata:
  name: emqx
  namespace: mqtt
spec:
  image: emqx/emqx:4.4.0
  replicas: 3
  env:
    - name: EMQX_ALLOW_ANONYMOUS
      value: "false"
    - name: EMQX_AUTH__JWT__JWKS
      value: "https://<my domain>/.well-known/jwks.json"
    - name: EMQX_AUTH__JWT__FROM
      value: "password"
    - name: EMQX_AUTH__JWT__VERIFY_CLAIMS
      value: "on"
    - name: EMQX_AUTH__JWT__VERIFY_CLAIMS__SUB
      value: "%u"
```
