### DISCUSSION TITLE
Problem with clustering in k8s with headlessService and DNS discovery

### DISCUSSION THREAD

**Discussion by bbkgh** [emqx/emqx#8158] [Q&A] [answered]
Hi. I am running emqx as a Deployment with 2 replicas. I've created a Headless SVC pointing to this pods and i want to use dns discovery for clustering but that doesn't works. I've set this ENVs in emqx's pods:
`EMQX_CLUSTER__DISCOVERY: dns`
`EMQX_CLUSTER__DNS__NAME: emqx-headless.namespace.svc.cluster.local`
`EMQX_CLUSTER__DNS__APP: emqx`

one of pods's logs:
```
kubectl logs emqx-clustering-debug-7f6487bfb7-58xfb 
cluster.discovery = "dns"
cluster.dns.app = "emqx"
cluster.dns.name = "emqx-headless.namespace.svc.cluster.local"
listener.ssl.external.acceptors = "32"
listener.ssl.external.max_connections = "102400"
listener.tcp.external.acceptors = "64"
listener.tcp.external.max_connections = "1024000"
listener.ws.external.acceptors = "16"
listener.ws.external.max_connections = "102400"
listener.wss.external.acceptors = "16"
listener.wss.external.max_connections = "102400"
log.to = "console"
node.max_ets_tables = "2097152"
node.max_ports = "1048576"
node.name = "emqx-clustering-debug-7f6487bfb7-58xfb@10.0.23.254"
node.process_limit = "2097152"
rpc.port_discovery = "manual"
Exec: /usr/lib/emqx/erts-11.1.8/bin/erlexec -noshell -noinput +Bd -boot /usr/lib/emqx/releases/4.3.5/start -mode embedded -boot_var ERTS_LIB_DIR /usr/lib/emqx/erts-11.1.8/../lib -mnesia dir "/var/lib/emqx/mnesia/emqx-clustering-debug-7f6487bfb7-58xfb@10.0.23.254" -config /var/lib/emqx/configs/app.2022.06.08.09.54.22.config -args_file /var/lib/emqx/configs/vm.2022.06.08.09.54.22.args -vm_args /var/lib/emqx/configs/vm.2022.06.08.09.54.22.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- foreground
Root: /usr/lib/emqx
Starting emqx on node emqx-clustering-debug-7f6487bfb7-58xfb@10.0.23.254
Start http:management listener on 8081 successfully.
Start http:dashboard listener on 18083 successfully.
Start mqtt:tcp:internal listener on 127.0.0.1:11883 successfully.
Start mqtt:tcp:external listener on 0.0.0.0:1883 successfully.
Start mqtt:ws:external listener on 0.0.0.0:8083 successfully.
Start mqtt:ssl:external listener on 0.0.0.0:8883 successfully.
Start mqtt:wss:external listener on 0.0.0.0:8084 successfully.
EMQ X Broker 4.3.5 is running now!
2022-06-08T09:54:45.769942+00:00 [error] ** Cannot get connection id for node 'emqx-clustering-debug-7f6487bfb7-58xfb@10.0.23.254'
2022-06-08T09:55:23.678558+00:00 [error] ** Cannot get connection id for node 'emqx-clustering-debug-7f6487bfb7-58xfb@10.0.23.254'
```

Thanks.

**Comment by zmstone** [comment]
Hi @bbkgh 
Does the "Cannot get connection id for node" log persist ?
We've seen such logs before and it seemed to be temporary and succeeds after a few retries.

Could you please execute this command (with `kubctl exec -it`):
`emqx eval '[node() | nodes()].'`
If it prints out all the nodes, then you can simply ignore this error.

**Reply by bbkgh** [reply]
It just shows same node address in result:
```
emqx@emqx-clustering-debug-67cc9d9554-28nhv:/$ emqx eval '[node() | nodes()].'
['emqx-clustering-debug-67cc9d9554-28nhv@10.0.24.128']
```
Do you see any problem in my configurations? (env names or values , ....)
Also i have to say that i refer to this ports in headlessSvc. Is this list complete?
```
  ports:
  - name: htt
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: main
    port: 18083
    protocol: TCP
    targetPort: 18083
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: 1883
  - name: mqtts
    port: 8883
    protocol: TCP
    targetPort: 8883
  - name: ws
    port: 8083
    protocol: TCP
    targetPort: 8083
  - name: wss
    port: 8084
    protocol: TCP
    targetPort: 8084

```
