### DISCUSSION TITLE
EMQX throwing error while using persistent volume for storage on AWS EKS

### DISCUSSION THREAD

**Discussion by giridhar08** [emqx/emqx#9087] [Q&A]
Getting below error while configuring  EMQX pod to use persistent volume for storage on AWS EKS.

```
[error] crasher: initial call: application_master:init/4, pid: <0.1607.0>, registered_name: [], exit: {{{"Cannot create Mnesia dir","/opt/emqx/data/mnesia/emqx--deployment-xxxxxxxx-xxxx@xx.xx.x.xxx",eacces},{emqx_app,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,142}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [<0.1606.0>], message_queue_len: 1, messages: [{'EXIT',<0.1608.0>,normal}], links: [<0.1606.0>,<0.1461.0>], dictionary: [], trap_exit: true, status: running, heap_size: 610, stack_size: 29, reductions: 214; neighbours:
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,emqx,{{\"Cannot create Mnesia dir\",\"/opt/emqx/data/mnesia/emqx-deployment-xxxxxxxx-xxxx@xx.xx.x.xxx\",eacces},{emqx_app,start,[normal,[]]}}}"}
Crash dump is being written to: log/crash.dump...done

```

Below are the deployment and pvc yaml files
```
apiVersion: apps/v1
kind: Deployment
...
spec:
  ...
  template:
    metadata:
      labels:
        app: emqx      
    spec:
      containers:
      - name: emqx
        imagePullPolicy: Always
        image: xxxxxxxxxxxxxx.dkr.ecr.us-west-1.amazonaws.com/emqx:{{ .Values.emqx.version }}     
        ports:
        - name: mqtt
          containerPort: 1883         
        - name: dashboard
          containerPort: 18083
        volumeMounts:
        - name: emqx-data
          mountPath: "/opt/emqx/data/mnesia"  
        securityContext:
          privileged: true    
      volumes:
      - name: emqx-data
        persistentVolumeClaim:
          claimName: emqx-pvc    

```
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-pvc 
  annotations: volume.beta.kubernetes.io/storage-class: gp2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

```
