### DISCUSSION TITLE
SSL Proxy and Peer cert as username problem

### DISCUSSION THREAD

**Discussion by coreyborad** [emqx/emqx#9106] [Q&A] [answered]
EMQX Version 4.4.8

Hi

I set the nginx-ingress and set up EMQX proxy with SSL protocol like below

EMQX helm chart settings
`EMQX_LISTENER__SSL__EXTERNAL__PROXY_PROTOCOL: "on"`
`EMQX_LISTENER__SSL__EXTERNAL__PEER_CERT_AS_USERNAME: "cn"`

nginx-ingress settings
![image](https://user-images.githubusercontent.com/16874516/194205881-cdadd54d-7cf6-40f8-86aa-22a082883e6f.png)

this is nginx.conf you will see after you set
![image](https://user-images.githubusercontent.com/16874516/194206051-e94fb5df-2124-42db-806c-19d0ed73e7ae.png)

Client will login success to EMQX as well with SSL protocol, and also get real client IP too
but, it's seems like EMQX can't resolve cert's common name as username this below this image from EMQX Dashboard
![image](https://user-images.githubusercontent.com/16874516/194206315-f19c539b-c884-451b-9d8a-1e1a8fde63e0.png)

if I set proxt protocol to off, then username can get from my cert's common name, but I can't get real client IP
`EMQX_LISTENER__SSL__EXTERNAL__PROXY_PROTOCOL: "off"`

it's any idea about this problem?
thanks

**Comment by id** [comment, marked as answer]
nginx [does not support](https://trac.nginx.org/nginx/ticket/1639) proxy protocol v2 on writing, only on reading. Which means it cannot forward client certificate information to upstream.

**Comment by coreyborad** [comment]
hi

thanks for your reply

according your comment, I was try the HAProxy in docker environment

this is my docker-compose.yaml
```
version: '3'
networks:
  dashboard:
    driver: bridge
services:
  haproxy:
    restart: always
    image: haproxy:2.4
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "28883:28883"
    networks:
      - dashboard
  emqx:
    image: emqx/emqx:4.4.8
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node.emqx.io"
    - "EMQX_LOG__LEVEL=debug"
    - "EMQX_LISTENER__SSL__EXTERNAL__VERIFY=verify_peer"
    - "EMQX_LISTENER__SSL__EXTERNAL__FAIL_IF_NO_PEER_CERT=true"
    - "EMQX_LISTENER__SSL__EXTERNAL__PEER_CERT_AS_USERNAME=cn"
    - "EMQX_LISTENER__SSL__EXTERNAL__REUSEADDR=true"
    - "EMQX_LISTENER__SSL__EXTERNAL__CERTFILE=/etc/emqx/ssl/cert.pem"
    - "EMQX_LISTENER__SSL__EXTERNAL__CACERTFILE=/etc/emqx/ssl/ca.pem"
    - "EMQX_LISTENER__SSL__EXTERNAL__KEYFILE=/etc/emqx/ssl/key.pem"
    - "EMQX_LISTENER__SSL__EXTERNAL__PROXY_PROTOCOL=on"
    - "EMQX_LISTENER__SSL__EXTERNAL__DEPTH=20"
    - "EMQX_LISTENER__SSL__EXTERNAL__TLS_VERSIONS=tlsv1.3,tlsv1.2"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    volumes:
      - ./nginx/ssl/:/etc/emqx/ssl
    ports:
      - "8883:8883"
      - "18083:18083"
    networks:
      - dashboard
 ```
this is my HAProxy config
```
listen abc
  mode tcp
  bind *:28883
    # Create a stick table for session persistence
  # stick-table type string len 32 size 100k expire 30m

  # Use ClientID / client_identifier as persistence key
  #stick on req.payload(0,0),mqtt_field_value(connect,client_identifier)

  server abc emqx:8883 send-proxy-v2
```

can connect and get real ip, but still see the username is undefined here
![image](https://user-images.githubusercontent.com/16874516/195237971-3a145962-8180-4950-ac48-520d939a9de8.png)

Is this correct on my config?
thanks
