### DISCUSSION TITLE
Running EMQX 5 using Helm. Unable to configure plugins.

### DISCUSSION THREAD

**Discussion by FinitelyFailed** [emqx/emqx#9110] [Q&A]
Hi,

I'm struggling to configure EMQX and plugins which I try to deploy using Helm.
`helm install test-emqx emqx/emqx -f emqx_test.yaml`

My emqx_test.yaml looks like:
```
replicaCount: 3
image:
  repository: emqx/emqx
  pullPolicy: IfNotPresent

persistence:
  enabled: false
  size: 20Mi
  accessMode: ReadWriteOnce

resources: {}
initContainers: {}  
emqxConfig:
  EMQX_CLUSTER__K8S__APISERVER: "https://kubernetes.default.svc:443"
  EMQX_CLUSTER__K8S__ADDRESS_TYPE: "hostname"
  EMQX_CLUSTER__K8S__SUFFIX: "svc.cluster.local"
  EMQX_MQTT__MAX_PACKET_SIZE: '254KB'
  EMQX_ALLOW_ANONYMOUS: false

  EMQX_LISTENER__API__MGMT: 8090

  EMQX_LOADED_MODULES: 'emqx_mod_acl_internal,emqx_mod_presence'
  EMQX_LOADED_PLUGINS: 'emqx_auth_redis,emqx_management,emqx_recon,emqx_retainer,emqx_auth_username,emqx_dashboard'

  # Doesn't work
  #EMQX_DASHBOARD__DEFAULT_USER__LOGIN: 'admin'
  # Doesn't work
  #EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: 'password'
  # Does work
  EMQX_DASHBOARD__DEFAULT_USERNAME: 'admin'
  # Does work
  EMQX_DASHBOARD__DEFAULT_PASSWORD: 'password'
  
  EMQX_AUTH__USER__PASSWORD_HASH: 'plain'
  EMQX_AUTH__USER__1__USERNAME: 'username1'
  EMQX_AUTH__USER__1__PASSWORD: 'test'
  EMQX_AUTH__USER__2__USERNAME: 'username2'
  EMQX_AUTH__USER__2__PASSWORD: 'test'
  
emqxAclConfig: >
  {allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.
  {allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.
  {deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.
  {allow, all}.

emqxLicneseSecretName:

service:
  type: LoadBalancer # Default was ClusterIp
  mqtt: 1883
  mqttssl: 8883
  mgmt: 8090
  ws: 8083
  wss: 8084
  dashboard: 18083
  nodePorts:
    mqtt:
    mqttssl:
    mgmt:
    ws:
    wss:
    dashboard:
  loadBalancerSourceRanges: []
  annotations: {
    }

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  dashboard:
    enabled: false
    annotations: {}
    path: /
    hosts:
    - dashboard.emqx.local
    tls: []

  mgmt:
    enabled: false
    annotations: {}
    path: /
    hosts:
    - api.emqx.local
    tls: []
```

No plugins seems to load. This config worked well with EMQX 4.2.12 and I can't find any documentation how the config works now. I stumbled over a log messages that said that it couldn't find EMQX_DASHBOARD__DEFAULT_USERNAME and EMQX_DASHBOARD__DEFAULT_PASSWORD so default values where used instead. 

From one of the pods:
```
emqx@test-emqx-0:/opt/emqx$ ./bin/emqx_ctl plugins list
{}
emqx@test-emqx-0:/opt/emqx$ ./bin/emqx_ctl plugins reload emqx_auth_username
plugins <command> [Name-Vsn]          # e.g. 'start emqx_plugin_template-5.0-rc.1'
plugins list                          # List all installed plugins
plugins describe  Name-Vsn            # Describe an installed plugins
plugins install   Name-Vsn            # Install a plugin package placed
                                      # in plugin'sinstall_dir
plugins uninstall Name-Vsn            # Uninstall a plugin. NOTE: it deletes
                                      # all files in install_dir/Name-Vsn
plugins start     Name-Vsn            # Start a plugin
plugins stop      Name-Vsn            # Stop a plugin
plugins restart   Name-Vsn            # Stop then start a plugin
plugins disable   Name-Vsn            # Disable auto-boot
plugins enable    Name-Vsn [Position] # Enable auto-boot at Position in the boot list, where Position could be
                                      # 'front', 'rear', or 'before Other-Vsn' to specify a relative position.
                                      # The Position parameter can be used to adjust the boot order.
                                      # If no Position is given, an already configured plugin
                                      # will stay at is old position; a newly plugin is appended to the rear
                                      # e.g. plugins disable foo-0.1.0 front
                                      #      plugins enable bar-0.2.0 before foo-0.1.0
emqx@test-emqx-0:/opt/emqx$ ./bin/emqx_ctl plugins install emqx_auth_username
{
    "action": "ensure_installed",
    "cause": {
        "path": "plugins/emqx_auth_username.tar.gz",
        "reason": "failed_to_extract_plugin_package",
        "return": "not_found"
    },
    "name_vsn": "emqx_auth_username",
    "result": "not_ok"
}
```
