### DISCUSSION TITLE
how to create data bridge and rule in helm chart values.yaml

### DISCUSSION THREAD

**Discussion by Tuxzx** [emqx/emqx#9208] [Q&A] [answered]
I am using chart in version 5.0.8 to install emqx on k8s and I am using its data bridging feature, but it takes some time to configure it. I would like to be able to configure my settings as environment variables in the emqxConfig field in values.yaml.

In my local environment, I used the following configuration, but I was never able to convert it to the correct yaml configuration.

Are there any best practices for configuring k8s for deployment? Thanks!

This is my emqx.conf
```
bridges.mqtt.device_session_bridge {
    connector = {
        server = "localhost:1885"
        username = "device-session"
        password = "device-session"
        keepalive = "5s"
        reconnect_interval = "5s"
        retry_interval = "5s"
        ssl.enable = false
    }

    direction = egress

    remote_topic = "device-session"
    remote_qos = "1"
    payload = ""
    retain = false
}

rule_engine {
    rules.device_session {
        sql = "SELECT * FROM \"$events/client_connected\", \"$events/client_disconnected\"",
        actions = ["mqtt:device_session_bridge"]
    }
}
```

And this is in the emqxConfig of chart values.yaml
```yaml
EMQX_BRIDGES__MQTT__DEVICE_SESSION_BRIDGE__CONNECTOR__SERVER: "localhost:1885"
EMQX_BRIDGES__MQTT__DEVICE_SESSION_BRIDGE__CONNECTOR__USERNAME: "device-session"
EMQX_BRIDGES__MQTT__DEVICE_SESSION_BRIDGE__CONNECTOR__PASSWORD: "device-session"
EMQX_BRIDGES__MQTT__DEVICE_SESSION_BRIDGE__CONNECTOR__SSL__ENABLE: "true"
EMQX_BRIDGES__MQTT__DEVICE_SESSION_BRIDGE__DIRECTION: "egress"
EMQX_BRIDGES__MQTT__DEVICE_SESSION_BRIDGE__REMOTE_TOPIC: "device-session" EMQX_BRIDGES__MQTT__DEVICE_SESSION_BRIDGE__REMOTE_QOS: "1" EMQX_BRIDGES__MQTT__DEVICE_SESSION_BRIDGE__PAYLOAD: ""
EMQX_BRIDGES__MQTT__DEVICE_SESSION_BRIDGE__RETAIN: "false"


EMQX_RULE_ENGINE__RULES__DEVICE_SESSION__SQL: SELECT * FROM '$events/client_connected', '$events/client_disconnected' 
EMQX_RULE_ENGINE__RULES__DEVICE_SESSION__ACTIONS:
  - "mqtt:device_session_bridge"
```

**Comment by lafirest** [comment]
My personal point is to use the emqx.conf directly will be more manageable and better

**Reply by vipa0120** [reply]
Hi @lafirest  
 any idea how achieve this from value.yaml file ?
Actually i got the same request from my BOSS and i want to perform it from Values.yaml. 
 If you know could you please help me out regarding this .

Thanks in advance

**Reply by thalesmg** [reply]
You can check the examples for your emqx-operator version, such as:

https://github.com/emqx/emqx-operator/blob/078293760933ed7b5ce4bad566b33a6030970bca/config/samples/emqx/v2beta1/emqx-full.yaml#L12-L15

https://github.com/emqx/emqx-operator/blob/078293760933ed7b5ce4bad566b33a6030970bca/config/samples/emqx/v2alpha1/emqx-full.yaml#L13-L18

**Reply by vipa0120** [reply]
thanks @thalesmg

**Comment by Tuxzx** [comment, marked as answer]
@vipa0120 If you haven't used Operator and only used Helm Chart, I think this would be helpful for you.

This is work for me, you should reference this [data-bridge](https://www.emqx.io/docs/en/latest/configuration/configuration-manual.html#data-bridge) to write this.

```yaml
emqxConfig:
  EMQX_BRIDGES__MQTT__DEVICE_SESSION__ENABLE: "true"
  EMQX_BRIDGES__MQTT__DEVICE_SESSION__SERVER: "other-mqtt-server:1883"
  EMQX_BRIDGES__MQTT__DEVICE_SESSION__USERNAME: "device-session"
  EMQX_BRIDGES__MQTT__DEVICE_SESSION__PASSWORD: "device-session"
  EMQX_BRIDGES__MQTT__DEVICE_SESSION__CLEAN_START: "true"
  EMQX_BRIDGES__MQTT__DEVICE_SESSION__EGRESS__REMOTE__TOPIC: "device-session"
  EMQX_BRIDGES__MQTT__DEVICE_SESSION__EGRESS__REMOTE__QOS: "1"

  EMQX_RULE_ENGINE__RULES__RULE_SESSION__ENABLE: "true"
  EMQX_RULE_ENGINE__RULES__RULE_SESSION__SQL: SELECT * FROM '$events/client_connected', '$events/client_disconnected'
  EMQX_RULE_ENGINE__RULES__RULE_SESSION__ACTIONS:
    - "mqtt:device_session"

```
