### DISCUSSION TITLE
How to connect via wss on port 443

### DISCUSSION THREAD

**Discussion by srinivaassunil** [emqx/emqx#9216] [Q&A]
I am setting up emqx@5.0.7 using the docker container on my server and i want to connect to emqx via wss on port 443 instead of 8084. I have created a listener for wss to listen on port 443 but getting the following error
`400 BAD_REQUEST:{failed_to_start,"wss:wss-443(:443) : eacces"}`

I tried searching for a solution and I was told to run emqx as root inside the container. How do I do that?
I have nginx running as reverse proxy and i am able to connect to wss via 8084. 

Here is my docker file
```
version: '3'
services:
  emqx:
    image: emqx/emqx:5.0.7
    restart: always
    ports:
      - 18083:18083
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 443:443
    environment:
      EMQX_NAME: foo_emqx
      EMQX_HOST: 127.0.0.1
      EMQX_LISTENER__TCP__EXTERNAL: 1883
    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log
    network_mode: "host"
volumes:
  vol-emqx-data:
  vol-emqx-etc:
  vol-emqx-log:
```
