### DISCUSSION TITLE
Error when using persistent folders

### DISCUSSION THREAD

**Discussion by WouterDN** [emqx/emqx#9503] [Q&A] [answered]
Hi,

I'm trying to deploy an emqx docker container with persistent folders.
I first deployed it without, and it worked fine.
So I created the 3 folders needed on my Synology ('data', 'etc' and 'logs') as mentioned in the documentation on Docker hub.
Then made the links and tried to deploy the conatiner again.

Now, the container tries to start, fails and tries to start again.
This keeps repeating.
This is the log I get:

```
 escript: exception throw: {emqx_conf_schema,[#{kind => validation_error,
                                     path => "node.cookie",
                                      reason => mandatory_required_field,
                                      value => undefined},
                                    #{kind => validation_error,
                                      path => "node.data_dir",
                                      reason => mandatory_required_field,
                                      value => undefined}]}
  in function  hocon_tconf:assert_no_error/2 (hocon_tconf.erl, line 1142)
  in call from hocon_tconf:map/4 (hocon_tconf.erl, line 295)
  in call from hocon_cli:get_values/3 (hocon_cli.erl, line 194)
  in call from hocon_cli:multi_get/2 (hocon_cli.erl, line 182)
  in call from escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
ERROR: call_hocon_failed: -s emqx_conf_schema -c /opt/emqx/etc/emqx.conf multi_get node.data_dir node.name node.cookie node.db_backend cluster.proto_dist
```

I can also mention that the emqx container is deployed on a different subnet then my Synology, using a Macvlan.
Again, works fine without the persistent folders.

I found a similar topic #8594 : The "ERROR" is the same, but the rest is not... 

Would be nice if someone could point me in the good direction.
Thanks!

With kind regards,
Wouter

**Comment by id** [comment]
Looks like you are missing 2 mandatory fields in the configuration:
- `node.cookie`
- `node.data_dir`

**Comment by tyset** [comment]
Excuse me, I have the same problem. Thanks a lot for your answer, but honestly even with the answer I could not get emqx up and running.
When running in docker, it seems those two are not set. I read that you can set $EMQX_NODE__DATA_DIR as an environment variable instead of node.data_dir, but it does not say what value to set. So anyway, I have no idea where to set this variables and to what value. Can anybody give a hint please?

**Comment by id** [comment, marked as answer]
@WouterDN @tyset apologies for the delay. You are correct, instructions are incorrect.

This one worked for me:
```
docker run -it --rm -v $(pwd)/data:/var/lib/emqx/data -v $(pwd)/logs:/var/log/emqx emqx/emqx:latest
```

The main catch is to not mount empty directory to `/opt/emqx/etc` in the container since this would effectively erase default configuration.

**Reply by WouterDN** [reply]
Hi id,

Thanks for that answer.
This works.

But that means that the /etc folder is not persistent?
Do I not have the risk now of losing data?

With kind regards,

**Reply by id** [reply]
I'm gonna have to double check, but as far as I know emqx does not create or change anything in /etc. It's for configuration and configuration related files, like certificates.

**Reply by id** [reply]
If, however, you decide to use custom configuration, then you would need to mount it accordingly.

**Reply by tyset** [reply]
Thank you, once I do not mount /opt/emq/etc it works. However I did this because on the page https://hub.docker.com/r/emqx/emqx in the chapter "Persistence" it is recommended to do so - or at least that is what I understood.
Anyways, thanks for the answer.

**Comment by alex-controlx** [comment]
There is `emqx.conf` in `/opt/emqx/etc` so I think it is a good idea to persist it. So I solved it by copying the `default` content of `/opt/emqx/etc` into the persisted volume path (`init-emqx` in the composer option) before running the main container.

Docker **run** option (this is only init command, you'll need to run the `emqx` docker as mentioned in the docs. Also the temporary created container can be deleted after the completed run):
```bash
docker run -v "$(pwd)/c_data_emqx/etc:/emqx_etc" \
    --entrypoint="/bin/sh" \
    emqx/emqx:5.0.13 \
    -c "if [ ! -f /emqx_etc/.emqx-seed-complete ]; then mkdir /emqx_etc ; touch /emqx_etc/.emqx-seed-complete ; cp -dpR /opt/emqx/etc/* /emqx_etc/ ; fi"
```


Docker **composer** option:
```yaml
version: '3.9'
services:
  init-emqx:
    image: emqx/emqx:5.0.13
    entrypoint: sh -c
    volumes:
      # We mount this in the container as `/emqx_etc` to not conflict with built-in files
      # at `/opt/emqx/emqx_etc`
      - ./c_data_emqx/etc:/emqx_etc
    command:
      # Seed the files from the image to our /emqx_etc if marker file not present, skip
      # if the marker file exists (and implicitly exit cleanly with status code 0)
      - |
        if [ ! -f /emqx_etc/.emqx-seed-complete ]; then
          mkdir /emqx_etc ;
          touch /emqx_etc/.emqx-seed-complete ;
          cp -dpR /opt/emqx/etc/* /emqx_etc/ ;
        fi


  emqx:
    image: emqx/emqx:5.0.13
    depends_on:
      init-emqx:
        condition: service_completed_successfully
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    volumes:
      - ./c_data_emqx/data:/opt/emqx/data
      - ./c_data_emqx/log:/opt/emqx/log
      - ./c_data_emqx/etc:/opt/emqx/etc

```

**Reply by EpicLPer** [reply]
When I try this I simply get the following issue:

```
mqx_etc/.emqx-seed-complete ; cp -dpR /opt/emqx/etc/* /emqx_etc/ ; fi"
mkdir: cannot create directory ‘/emqx_etc’: File exists
touch: cannot touch '/emqx_etc/.emqx-seed-complete': Permission denied
cp: cannot create regular file '/emqx_etc/acl.conf': Permission denied
cp: cannot create directory '/emqx_etc/certs': Permission denied
cp: cannot create regular file '/emqx_etc/emqx.conf': Permission denied
cp: cannot create regular file '/emqx_etc/emqx.conf.example': Permission denied
cp: cannot create directory '/emqx_etc/lwm2m_xml': Permission denied
cp: cannot create regular file '/emqx_etc/ssl_dist.conf': Permission denied
cp: cannot create regular file '/emqx_etc/vm.args': Permission denied
```

It creates the folders as root user for some reason.

**Reply by alex-controlx** [reply]
What OS are you using? Folders `./c_data_emqx/*` on your host should have the same user as the Docker user.

**Reply by EpicLPer** [reply]
> What OS are you using? Folders `./c_data_emqx/*` on your host should have the same user as the Docker user.

Ubuntu 20.04, Docker running as root. The c_data_emqx folder does have root:root.

**Reply by EpicLPer** [reply]
Got it to work now, for some reason whenever Docker created directories that weren't created before it used the root user, despite then later on using a non-root user which obviously results in a "Permission Denied". chowning the directories as my own user and setting the `user: 1000:1000` option in the docker-compose seemed to work.

**Reply by paranjay-patel** [reply]
when i run your compose file, its shows this "no configuration file provided: not found"

**Reply by alex-controlx** [reply]
sounds like you are running the `docker compose` in the directory which doesn't contain the `.yml` config file

**Comment by xbmcnut** [comment]
Thanks @id . This helped me getting EQMX running on my Synology NAS using a docker-compose.yml under the Projects section.

```
version: '3.3'
services:
  emqx:
    container_name: emqx
    ports:
      - '1883:1883'
      - '8083:8083'
      - '8087:8084' #port 8084 in use
      - '8883:8883'
      - '18083:18083'
    environment:
      TZ: Pacific/Auckland
    volumes:
      - /volume1/docker/emqx/data:/var/lib/emqx/data
      - /volume1/docker/emqx/log:/var/log/emqx
    image: 'emqx/emqx:latest'
```
