### ISSUE TITLE
Support for docker secrets

### ISSUE THREAD

**Issue by m1212e** [emqx/emqx#10028]
### What would you like to be added or enhanced?

Docker secrets are files which are mounted to a container which provide credentials etc. Many containers which support Docker secrets provide alternatives to the regular env variables, often with a suffix like "_FILE". E.g. the postgres docker image accepts `POSTGRES_PASSWORD=123` or `POSTGRES_PASSWORD_FILE=/path/to/123` to set the password.
A similar approach for emqx env variables would be very useful.

### Why is this needed?

This would allow seamless secret sharing between emqx and other services inside a compose setup. Secrets could be easily rotated and mismatches could be prevented.

**Comment by matthewGEA** [comment]
I agree this feature is needed.

Without Docker secrets, how to the developers suggest handling/managing the passwords of environmental variables like "EMQX_dashboard__default_password" for example?

**Comment by matthewGEA** [comment]
A work-around within a Docker Compose File until official support is given?

Add the following to your existing compose file:
```
version: "3.8"
services:
  emqx:
    secrets:
      - emqx-dash-password
    entrypoint: ["/bin/sh","-c"]
    command: 
      - |
        echo "Using secret 'emqx-dash-password' for variable EMQX_dashboard__default_password"
        export EMQX_dashboard__default_password=$$(cat /var/run/secrets/emqx-dash-password)

        echo "Starting emqx using emqx/emqx docker image entrypoint and cmd"
        /usr/bin/docker-entrypoint.sh /opt/emqx/bin/emqx foreground

secrets:
    emqx-dash-password:
        external: true
```
