### ISSUE TITLE
Multi node cluster with docker emqx

### ISSUE THREAD

**Issue by princejt** [emqx/emqx#10333]
### What happened?

I am trying to setup an EMQX cluster between two docker emqx containers running in server1 and server2.

docker-compose.yml on server 1

```
version: '3'

services:
  emqx1:
    image: emqx/emqx:latest
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=server1fqdn"
    - "EMQX_NODE__COOKIE=somepw"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@server1fqdn, emqx@server2fqdn]"
    networks:
      emqx-bridge:
        aliases:
        - server1fqdn

    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
networks:
  emqx-bridge:
    driver: bridge
```

docker-compose.yml on server 2

```
version: '3'

services:
  emqx1:
    image: emqx/emqx:latest
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=server2fqdn"
    - "EMQX_NODE__COOKIE=somepw"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@server2fqdn, emqx@server1fqdn]"
    networks:
      emqx-bridge:
        aliases:
        - server2fqdn

    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
networks:
  emqx-bridge:
    driver: bridge
```

In server1
Cluster status: #{running_nodes =>
                      ['emqx@server1fqdn'],
                  stopped_nodes => []}

In server2

Cluster status: #{running_nodes =>
                      ['emqx@server2fqdn'],
                  stopped_nodes => []}

I also tried to manually setup the cluster using 

`emqx_ctl cluster join emqx@server1fqdn`

Got below error
Failed to join the cluster: {node_down,'emqx@server1fqdn'}

### What did you expect to happen?

Cluster setup b/w docker instances in two nodes.

### How can we reproduce it (as minimally and precisely as possible)?

Run the 2 docker-compose.yml in two different servers.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```
sysdescr  : EMQX
version   : 5.0.21
datetime  : 2023-04-05T04:30:53.029085994+00:00
uptime    : 21 hours, 47 minutes, 27 seconds
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here

RETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
# paste output here

Linux 7117ec52dbbe 4.15.0-1098-gcp #111~16.04.1-Ubuntu SMP Tue Apr 13 19:05:08 UTC 2021 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by ieQu1** [comment]
Hello,

Most likely this problem happens because EMQX nodes cannot establish backplane connections to each other. This manual page explains network setup in more detail: https://www.emqx.io/docs/en/v5.0/design/clustering.html#how-emqx-nodes-communicate
Please make sure both ports TCP4370 and TCP5369 are reachable from both containers.

**Comment by princejt** [comment]
Enabling these ports helped in fixing this issue. Updating the docker-compose.yml to help if some else faces this issue. Thanks @ieQu1 for your help

```
version: '3'

services:
  emqx1:
    image: emqx/emqx:latest
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=server1fqdn"
    - "EMQX_NODE__COOKIE=somepw"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@server1fqdn, emqx@server2fqdn]"
    networks:
      emqx-bridge:
        aliases:
        - server1fqdn

    ports:
      - 1883:1883
      - 4370:4370
      - 5369:5369
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
networks:
  emqx-bridge:
    driver: bridge
```
