### ISSUE TITLE
Lack of Prometheus metrics 

### ISSUE THREAD

**Issue by memoliyasti** [emqx/emqx#10835]
### What happened?

Metrics we fetch from EMQX are not full. Even though we fetch some of them like below;

<img width="1715" alt="image" src="https://github.com/emqx/emqx/assets/79761080/e9ec8c5b-0c8a-4881-8034-6482c2ff42b2">

We are missing some of them. As it is shown in the screenshot, it says 0 but it should not be.

### What did you expect to happen?

We expect to see all metrics to be shown on the Grafana.

### Anything else we need to know?

This is how we configure the EMQX endpoint on Prometheus side,

```yaml
extraScrapeConfigs: |
  - job_name: JOB_NAME
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /api/v5/prometheus/stats
    scheme: http
    static_configs:
      - targets: [ 'SVC_NAME.NS_NAME.svc.cluster.local:18083' ]
```

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.0.16
datetime  : 2023-05-26T12:35:36.817083103+00:00
uptime    : 54 minutes, 44 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>
