### ISSUE TITLE
Unable to bind ssl certificates in docker compose

### ISSUE THREAD

**Issue by purusartha** [emqx/emqx#10865]
#### Environment

- OS: EMQ X Docker
- Erlang/OTP: 
- EMQ: v4.3.18

#### Description
I am attempting to use the docker image (emqx/emqx:4.3.19) with TLS authentication. I have followed the [link](https://emqx.medium.com/enable-ssl-tls-for-emq-x-mqtt-broker-cb15b1106c35) to generate the correct certificates. Below is my docker-compose where I attempt to bind volume containing the certificates to the `/etc/certs` folder along with the correct Environment Variable bindings.
```
emqx:
        container_name: emqx
        image: emqx/emqx
        environment:
            - EMQX_LISTENER__SSL__EXTERNAL=8883
            - EMQX_LISTENER__SSL__EXTERNAL__KEYFILE=etc/certs/emqx.key
            - EMQX_LISTENER__SSL_EXTERNAL__CERTFILE=etc/certs/emqx.pem
            - EMQX_LISTENER__SSL__EXTERNAL__CACERTFILE=etc/certs/katmatic_ca.pem
        ports:
            - '1883:1883'
            - '8081:8081'
            - '8083:8083'
            - '8084:8084'
            - '8883:8883'
            - '18083:18083'
        volumes:
            - D:\certs\katmatic\:/etc/certs
        networks:
            - pcnetwork
```
However, when I attempt to use a client certificate to connect to the broker, I get the below error message indicating that the certificates could not be found.
`2022-09-02T17:48:30.984773+00:00 [error] supervisor: 'esockd_connection_sup - <0.1882.0>', errorContext: connection_shutdown, reason: {ssl_error,{options,{keyfile,"etc/certs/emqx.key",{error,enoent}}}}, offender: [{pid,<0.2115.0>},{name,connection},{mfargs,{emqx_connection,start_link,[[{deflate_options,[]},{max_conn_rate,500},{active_n,100},{zone,external},{proxy_address_header,<<>>},{proxy_port_header,<<>>},{supported_subprotocols,[]}]]}}]`

Not sure if this is a bug or I am doing something wrong? Any help will be appreciated.
