### ISSUE TITLE
Update broke K8s install 

### ISSUE THREAD

**Issue by fabltd** [emqx/emqx#11123]
### What happened?

Updated to 5.1.0 

The EMQX replicant appears to have disappeared as does the loadbalcner for Ingress. I cannot seem to get these recreated. 

Please help.....

### What did you expect to happen?

Work as 5.0.26

### EMQX version

5.1.0

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by fabltd** [comment]
Replicant pods are no longer provisioned.  Neither is the loadbalancer.

Tested in GKE and self hosted K8s. Its the same for both.

Product is unsuable due to lack of service being provisoned.

**Comment by fabltd** [comment]
@ieQu1 This use to give replican install along with loadbalancer. 

The product is currently non functional as there is no way for devices to connect!

Here is the yaml I use to provision:


```
apiVersion: apps.emqx.io/v2alpha1
kind: EMQX
metadata:
    name: emqx
# Core
spec:
    image: emqx/emqx:5.1.0
    coreTemplate:
      spec:
        podSecurityContext:
              runAsUser: 1000
              runAsGroup: 1000
              fsGroup: 1000
              fsGroupChangePolicy: Always
              supplementalGroups:
                - 1000
        volumeClaimTemplates:
            #storageClassName: standard-rwo
            resources:
              requests:
                storage: 1Gi
            accessModes:
              - ReadWriteOnce
        replicas: 3
# BootStrap Config
    bootstrapConfig: |
        dashboard {
          listeners.http {
              bind: 18083
          }
          default_username: "admin"
          default_password: "public"
        }
    replicantTemplate:
      spec:
        replicas: 3
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
# Dashboard
    dashboardServiceTemplate:
      metadata:
        name: emqx-dashboard
      spec:
        type: NodePort
        selector:
          apps.emqx.io/db-role: core
        ports:
          - name: "dashboard-listeners-http-bind"
            protocol: TCP
            port: 18083
            targetPort: 18083
            nodePort: 30008
# Listeners
    listenersServiceTemplate:
      metadata:
        name: emqx-listeners
      spec:
        type: LoadBalancer
        ports:
        sessionAffinity: ClientIP


```
