### ISSUE TITLE
Allow setting ssl certificate common name in helm chart

### ISSUE THREAD

**Issue by dounix** [emqx/emqx#11199]
### What would you like to be added or enhanced?

Allow setting ssl certificate common name in emqx emqx-enterprise helm chart.
```
ssl.commonname: "somehost.example.com"
```

### Why is this needed?

Some clusterIssuers providers require the common name be set in the certificate request, not just dns/san names.
This is required by the default policy of vault-issuer

Allowing this to be optionally set will resolve the following failure mode of cert issuance from the helm chart. 
```
status:
  conditions:
  - lastTransitionTime: "2023-07-03T18:23:34Z"
    message: |-
      The certificate request has failed to complete and will be retried: Vault failed to sign certificate: failed to sign certificate by vault: Error making API request.

      URL: POST https://vault.example.com/v1/pki/sign/gcp.example.com
      Code: 400. Errors:

      * the common_name field is required, or must be provided in a CSR with "use_csr_common_name" set to true, unless "require_cn" is set to false
```
