### ISSUE TITLE
Auto-discovery with etcd is unstable

### ISSUE THREAD

**Issue by flbraun** [emqx/emqx#11312]
### What happened?

I'm trying to get a 4-node cluster up and running utilizing auto-discovery via etcd.

I did ~30 attempts of which ~25 did not succeed. Errors appeared in the logs (see below).

In one particular attempt I noticed that node data in etcd looked like it was left in a dangling state:
```console
$ docker compose exec etcd-1 etcdctl get "" --prefix
emqxcl/ekkacl/lock//4e468972f9c5e00d

emqxcl/ekkacl/lock//4e468972f9c5e016

emqxcl/ekkacl/lock//4e468972f9c5e01b

emqxcl/ekkacl/nodes/emqx@node1.emqx.io
emqx@node1.emqx.io
```
In this attempt node 1 and 2 were able to join the cluster, but 3 and 4 were not (according to the web dashboard).

### What did you expect to happen?

All EMQX nodes reliably join the cluster successfully.

### How can we reproduce it (as minimally and precisely as possible)?

Use this Docker compose file:
<details>

```yaml
version: '3'

services:

  etcd-1:
    image: quay.io/coreos/etcd:v3.5.9
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd-1'
      - '--initial-advertise-peer-urls=http://etcd-1:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd-1:2379'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://etcd-1:2380'
      - '--initial-cluster-state=new'
      - '--initial-cluster-token=mys3cr3ttok3n'
    networks:
      default:
    volumes:
      - ./etcddata1:/etcd_data

  emqx1:
    user: 0:0
    image: emqx/emqx:5.1
    environment:
      - "EMQX_NAME=emqx"
      - "EMQX_HOST=node1.emqx.io"
    ports:
      - "9999:18083"
      - "9001:1883"
    hostname: node1.emqx.io
    volumes:
      - ./emqx_common.conf:/opt/emqx/etc/emqx.conf
    depends_on:
      - etcd-1

  emqx2:
    user: 0:0
    image: emqx/emqx:5.1
    environment:
      - "EMQX_NAME=emqx"
      - "EMQX_HOST=node2.emqx.io"
    ports:
      - "9002:1883"
    hostname: node2.emqx.io
    volumes:
      - ./emqx_common.conf:/opt/emqx/etc/emqx.conf
    depends_on:
      - etcd-1

  emqx3:
    user: 0:0
    image: emqx/emqx:5.1
    environment:
      - "EMQX_NAME=emqx"
      - "EMQX_HOST=node3.emqx.io"
    ports:
      - "9003:1883"
    hostname: node3.emqx.io
    volumes:
      - ./emqx_common.conf:/opt/emqx/etc/emqx.conf
    depends_on:
      - etcd-1

  emqx4:
    user: 0:0
    image: emqx/emqx:5.1
    environment:
      - "EMQX_NAME=emqx"
      - "EMQX_HOST=node4.emqx.io"
    ports:
      - "9004:1883"
    hostname: node4.emqx.io
    volumes:
      - ./emqx_common.conf:/opt/emqx/etc/emqx.conf
    depends_on:
      - etcd-1

```

</details>

This is my `emqx_common.conf`:

<details>

```hocon
telemetry {
  enable = false
}

node {
  cookie = "abcdefghijklmnopqrstuvw"
  data_dir = "data"
}

log.console_handler {
  enable = true
  level = "debug"
  single_line = false
}

log.file_handlers.default {
  enable = true
  level = "debug"
  file = "log/emqx.log"
}

cluster {
    discovery_strategy = etcd
    etcd {
        server = "http://etcd-1:2379"
    }
}

dashboard {
  listeners.http {
    bind = 18083
  }
  default_username = "admin"
  default_password = "admin"
}
```

</details>

Follow these steps:
1. Start etcd: `docker compose up etcd-1`
2. Now start each EMQX node after the other, with sufficient time in between to let the nodes perform all startup operations:
  - `docker compose up emqx1`
  - `docker compose up emqx2`
  - `docker compose up emqx3`
  - `docker compose up emqx4`
3. Between starting each node, take a look at the keys present in etcd: `docker compose exec etcd-1 etcdctl get "" --prefix`
 As soon as you see a key like `emqxcl/ekkacl/lock//<random>` you can assume the following nodes to crash while attempting to join the cluster.

To have a clean starting point between each attempt, reset the infrastructure with `docker compose down --remove-orphans --volumes`.

### EMQX version

<details>

```console
$ emqx_ctl broker
sysdescr  : EMQX
version   : 5.1.1
datetime  : 2023-07-20T09:41:23.311366499+00:00
uptime    : 3 minutes, 8 seconds
```

</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
Linux <redacted hostname> 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

$ docker --version
Docker version 24.0.4, build 3713ee1

$ docker compose version
Docker Compose version v2.19.1
```
</details>

### Log files

[node1.log](https://github.com/emqx/emqx/files/12105497/node1.log)
[node2.log](https://github.com/emqx/emqx/files/12105498/node2.log)
[node3.log](https://github.com/emqx/emqx/files/12105499/node3.log)
[node4.log](https://github.com/emqx/emqx/files/12105500/node4.log)
