### ISSUE TITLE
Redis Authentication and Docker Compose

### ISSUE THREAD

**Issue by bearrito** [emqx/emqx#11484]
### What happened?

Docker Compose

```
version: '2.4'
services:
  eqmx:
    image: emqx/emqx
    depends_on:
      - eqmx-redis
    ports:
      - 1883:1883
      - 8083:8083
      - 8883:8883
      - 8084:8084
      - 18083:18083 
    environment:
      - EMQX_AUTHENTICATION__1__MECHANISM="password_based"
      - EMQX_AUTHENTICATION__1__BACKEND="redis"
      - EMQX_AUTHENTICATION__1__REDIS_TYPE="single"
      - EMQX_AUTHENTICATION__1__SERVER='redis'
      - EMQX_AUTHENTICATION__1__CMD="'HMGET mqtt_user:$${username} password_hash salt is_superuser'"
    networks:
      - emqx
  eqmx-redis:
    image: redis:latest
    expose:
      - 6379
    networks:
      emqx:
        aliases:
          - redis
networks:
  emqx:
    driver: bridge 
```

**Issue 1**

The command is not accepted.
1. I'm escaping the dollar sign as this is required for docker compose
2. I'm double quoting the CMD singe there is a `:` present.
```
| 2023-08-20T21:37:26.627975+00:00 [error] msg: failed_to_create_authenticator, mfa: emqx_authentication:initialize_authentication/2, line: 312, authenticator: <<"password_based:redis">>, reason: {unsupported_cmd,"'HMGET mqtt_user:${username} password_hash salt is_superuser'"}
```

** Issue 2**
Maybe this is related but if I use another command, removing the `mqtt:` prefix.

`  - EMQX_AUTHENTICATION__1__CMD="HMGET $${username} password_hash salt is_superuser"`
```
emqx-eqmx-1        | 2023-08-20T21:40:27.214318+00:00 [error] Supervisor: {<0.2707.0>,ecpool_worker_sup}. Context: start_error. Reason: #{host => "'\"redis'",port => 6379,reason => nxdomain,type => get_addr}. Offender: id={worker,1},pid=undefined.
emqx-eqmx-1        | 2023-08-20T21:40:27.214448+00:00 [error] Supervisor: {<0.2705.0>,ecpool_pool_sup}. Context: start_error. Reason: {shutdown,{failed_to_start_child,{worker,1},#{host => "'\"redis'",port => 6379,reason => nxdomain,type => get_addr}}}. Offender: id=worker_sup,pid=undefined.
```
But from emqx I can see the redis host

```
emqx@2b3466ee618c:/opt/emqx$ whoami
emqx
emqx@2b3466ee618c:/opt/emqx$ getent hosts redis
172.18.0.3      redis
```

### What did you expect to happen?

For the emqx server to launch and connect to the redis host that is running on the same bridged network.

### How can we reproduce it (as minimally and precisely as possible)?

Run the docker compose file I've included.

### EMQX version

<details>

```
emqx@2b3466ee618c:/opt/emqx$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.0.26
datetime  : 2023-08-20T21:43:54.182683342+00:00
uptime    : 3 minutes, 27 seconds
```

</details>

### OS version

<details>

```
Docker Compose
```

</details>

### Log files

<details>

</details>

**Comment by kjellwinblad** [comment]
**Regarding Issue 1:**

Your docker compose contains the following:

```
      - EMQX_AUTHENTICATION__1__CMD="'HMGET mqtt_user:$${username} password_hash salt is_superuser'"
```

I think this should be replaced by:

```
      - EMQX_AUTHENTICATION__1__CMD="HMGET mqtt_user:$${username} password_hash salt is_superuser"
```

**Regarding Issue 2:**

This seems strange. I don't understand how changing the EMQX_AUTHENTICATION__1__CMD could lead to a connection error. Maybe we can try to resolve Issue 1 first?

**Comment by bearrito** [comment]
Using the alternative

`  - EMQX_AUTHENTICATION__1__CMD="HMGET mqtt_user:$${username} password_hash salt is_superuser"`

Generates the same

```

emqx-eqmx-1        | Listener http:dashboard on :18083 started.
emqx-eqmx-1        | 2023-08-21T14:12:39.949278+00:00 [error] Supervisor: {<0.2712.0>,ecpool_worker_sup}. Context: start_error. Reason: #{host => "'\"redis'",port => 6379,reason => nxdomain,type => get_addr}. Offender: id={worker,1},pid=undefined.
emqx-eqmx-1        | 2023-08-21T14:12:39.949475+00:00 [error] Supervisor: {<0.2710.0>,ecpool_pool_sup}. Context: start_error. Reason: {shutdown,{failed_to_start_child,{worker,1},#{host => "'\"redis'",port => 6379,reason => nxdomain,type => get_addr}}}. Offender: id=worker_sup,pid=undefined.
emqx-eqmx-1        | 2023-08-21T14:12:39.949526+00:00 [error] crasher: initial call: eredis_client:init/1, pid: <0.2714.0>, registered_name: [], exit: {#{host => "'\"redis'",port => 6379,reason => nxdomain,type => get_addr},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,407}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [<0.2713.0>,<0.2712.0>,<0.2710.0>,ecpool_sup,<0.2631.0>], message_queue_len: 0, messages: [], links: [<0.2713.0>], dictionary: [{options,[{ssl,false},{sentinel,undefined}]}], trap_exit: true, status: running, heap_size: 610, stack_size: 29, reductions: 483; neighbours:
emqx-eqmx-1        | 2023-08-21T14:12:39.949680+00:00 [error] crasher: initial call: ecpool_worker:init/1, pid: <0.2713.0>, registered_name: [], exit: {#{host => "'\"redis'",port => 6379,reason => nxdomain,type => get_addr},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,407}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [<0.2712.0>,<0.2710.0>,ecpool_sup,<0.2631.0>], message_queue_len: 1, messages: [{'EXIT',<0.2712.0>,{shutdown,{failed_to_start_child,{worker,1},#{host => "'\"redis'",port => 6379,reason => nxdomain,type => get_addr}}}}], links: [<0.2714.0>], dictionary: [], trap_exit: true, status: running, heap_size: 376, stack_size: 29, reductions: 268; neighbours:
emqx-eqmx-1        | 2023-08-21T14:12:39.949938+00:00 [error] msg: start_ecpool_error, mfa: emqx_resource_pool:start/3, line: 49, pool_name: <<"emqx_authn_redis:1">>, reason: #{host => "'\"redis'",port => 6379,reason => nxdomain,type => get_addr}
emqx-eqmx-1        | 2023-08-21T14:12:39.950637+00:00 [warning] msg: start_resource_failed, mfa: emqx_resource_manager:start_resource/2, line: 489, id: <<"emqx_authn_redis:1">>, reason: {start_pool_failed,<<"emqx_authn_redis:1">>,#{host => "'\"redis'",port => 6379,reason => nxdomain,type => get_addr}}
emqx-eqmx-1        | 2023-08-21T14:12:39.950811+00:00 [warning] msg: alarm_is_activated, mfa: emqx_alarm:do_actions/3, line: 418, message: <<"resource down: {start_pool_failed,<<\"emqx_authn_redis:1\">>,#{host => \"'\\\"redis'\",port => 6379,reason => nxdomain,type => get_addr}}">>, name: <<"emqx_authn_redis:1">>
emqx-eqmx-1        | EMQX 5.0.26 is running now!
emqx-eqmx-1        | 2023-08-21T14:13:39.975434+00:00 [error] Supervisor: {<0.2809.0>,ecpool_worker_sup}. Context: start_error. Reason: #{host => "'\"redis'",port => 6379,reason => nxdomain,type => get_addr}. Offender: id={worker,1},pid=undefined.
emqx-eqmx-1        | 2023-08-21T14:13:39.974875+00:00 [error] crasher: initial call: eredis_client:init/1, pid: <0.2811.0>, registered_name: [], exit: {#{host => "'\"redis'",port => 6379,reason => nxdomain,type => get_addr},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,407}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [<0.2810.0>,<0.2809.0>,<0.2807.0>,ecpool_sup,<0.2631.0>], message_queue_len: 0, messages: [], links: [<0.2810.0>], dictionary: [{options,[{ssl,false},{sentinel,undefined}]}], trap_exit: true, status: running, heap_size: 610, stack_size: 29, reductions: 460; neighbours:
emqx-eqmx-1        | 2023-08-21T14:13:39.975668+00:00 [error] crasher: initial call: ecpool_worker:init/1, pid: <0.2810.0>, registered_name: [], exit: {#{host => "'\"redis'",port => 6379,reason => nxdomain,type => get_addr},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,407}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [<0.2809.0>,<0.2807.0>,ecpool_sup,<0.2631.0>], message_queue_len: 0, messages: [], links: [<0.2809.0>,<0.2811.0>], dictionary: [], trap_exit: true, status: running, heap_size: 376, stack_size: 29, reductions: 262; neighbours:
emqx-eqmx-1        | 2023-08-21T14:13:39.976452+00:00 [error] Supervisor: {<0.2807.0>,ecpool_pool_sup}. Context: start_error. Reason: {shutdown,{failed_to_start_child,{worker,1},#{host => "'\"redis'",port => 6379,reason => nxdomain,type => get_addr}}}. Offender: id=worker_sup,pid=undefined.
emqx-eqmx-1        | 2023-08-21T14:13:39.977681+00:00 [error] msg: start_ecpool_error, mfa: emqx_resource_pool:start/3, line: 49, pool_name: <<"emqx_authn_redis:1">>, reason: #{host => "'\"redis'",port => 6379,reason => nxdomain,type => get_addr}
emqx-eqmx-1        | 2023-08-21T14:13:39.977945+00:00 [warning] msg: start_resource_failed, mfa: emqx_resource_manager:start_resource/2, line: 489, id: <<"emqx_authn_redis:1">>, reason: {start_pool_failed,<<"emqx_authn_redis:1">>,#{host => "'\"redis'",port => 6379,reason => nxdomain,type => get_addr}}
```

**Comment by bearrito** [comment]
@kjellwinblad Thanks for the assist. This looks to have been a problem on my end. In case anyone ends up here from search. Here is a working example that will wire everything up.

```
version: '2.4'
services:
  eqmx:
    image: emqx/emqx
    depends_on:
      - eqmx-redis
      - eqmx-redis-init
    ports:
      - 1883:1883
      - 8083:8083
      - 8883:8883
      - 8084:8084
      - 18083:18083 
    environment:
      - EMQX_AUTHENTICATION__1__MECHANISM="password_based"
      - EMQX_AUTHENTICATION__1__BACKEND="redis"
      - EMQX_AUTHENTICATION__1__REDIS_TYPE="single"
      - EMQX_AUTHENTICATION__1__SERVER="redis"
      - EMQX_AUTHENTICATION__1__CMD="HMGET mqtt_user:$${username} password_hash salt is_superuser"
      - EMQX_DASHBOARD__DEFAULT_USERNAME=admin
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=${EMQX_DASHBOARD_DEFAULT_PASSWORD}
    networks:
      - emqx
  eqmx-redis:
    image: redis:latest
    expose:
      - 6379
    networks:
      emqx:
        aliases:
          - redis
  eqmx-redis-init:
    image: redis:latest
    depends_on:
      - eqmx-redis
    entrypoint: ["/bin/bash", "-c"]
    command: ["redis-cli", "-h", \
              "redis", "HSET", "mqtt:test", "is_superuser 0", "salt", "${EMQX_TEST_GLOBAL_SALT}",
              "password_hash", "${EMQX_TEST_USER}"]
    networks:
      emqx:
        aliases:
          - redis-init
networks:
  emqx:
    driver: bridge 

```
