### ISSUE TITLE
emqx set up with jwks server

### ISSUE THREAD

**Issue by nttq1sub** [emqx/emqx#11538]
### What happened?

I follow the guidance here but it can go through
[https://www.emqx.com/en/blog/jwt-authentication-and-jwks-endpoint-in-mqtt](url)
this is the log I received when set up jwks following above guidance
```
emqx       | 2023-08-29T15:48:08.475625+00:00 [warning] msg: failed_to_request_jwks_endpoint, mfa: emqx_authn_jwks_client:handle_info/2, line: 98, endpoint: http://127.0.0.1:8080, reason: {failed_connect,[{to_address,{"127.0.0.1",8080}},{inet,[inet],econnrefused}]}
```
![image](https://github.com/emqx/emqx/assets/81282520/16ffc2a7-8e61-4cfa-b50a-b7c40f4745a0)

### What did you expect to happen?

I expect it to connect successful to the jwks server 

### How can we reproduce it (as minimally and precisely as possible)?

This is my `docker-compose.yml`
```
version: '3'

services:
  emqx:
    image: emqx:5.1.1
    container_name: emqx
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083

  mqttx:
    image: emqx/mqttx-web
    container_name: mqttx-web
    ports:
      - 8099:80
```

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>
