### ISSUE TITLE
Failed authentication not reported in the logs

### ISSUE THREAD

**Issue by mdallaire** [emqx/emqx#11932]
### What happened?

I am using the built-in database for authentication and console logs set to warning (default for the Helm chart).

While troubleshooting an issue with a mqtt client I realized that a login failure (wrong username or password) does not get logged to the global log.

I am able to see the login failure in a trace log.

### What did you expect to happen?

I expect a login failure to appear in the log as stated in the [documentation](https://www.emqx.io/docs/en/latest/observability/log.html#log-level)

### How can we reproduce it (as minimally and precisely as possible)?

Deploy the helm chart with the following values.
```
  values:
    emqxConfig:
      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_AUTHENTICATION__1__MECHANISM: password_based
      EMQX_AUTHENTICATION__1__BACKEND: built_in_database
      EMQX_AUTHENTICATION__1__USER_ID_TYPE: username
      EMQX_AUTHENTICATION__1__PASSWORD_HASH_ALGORITHM: {"name":"plain", "salt_position":"disable"}
      EMQX_AUTHENTICATION__1__ENABLE: true
      EMQX_LOG__CONSOLE__LEVEL: warning
      EMQX_LOG__CONSOLE__ENABLE: true
      EMQX_LOG__CONSOLE__FORMATTER: text
      EMQX_LOG__CONSOLE__TIME_OFFSET: system
```
Create a user in the dashboard and try to login with a wrong password while monitoring the logs `kubectl logs statefulsets/emqx -f`

### EMQX version

<details>

```console
sysdescr  : EMQX
version   : 5.3.0
datetime  : 2023-11-12T18:44:50.547090074+00:00
uptime    : 16 minutes, 51 seconds
```

</details>

### OS version

<details>

```console
Kubernetes 1.27.7
OS: Talos v1.5.5
Kernel: 6.1.61-talos
Container-Runtime: containerd://1.6.23
```

</details>

### Log files

[node_dump_20231112_184754.tar.gz](https://github.com/emqx/emqx/files/13328898/node_dump_20231112_184754.tar.gz)
