### ISSUE TITLE
Add helm chart support for service labels

### ISSUE THREAD

**Issue by dounix** [emqx/emqx#11956]
### What would you like to be added or enhanced?

Ability to add arbitrary labels to services and serviceMontiors
 This is very similar to the way annotations are currently templated for services.
 
 

### Why is this needed?

If you run multiple Prometheus instances(or you're selective about what is scraped) matchLabel are used to tell a Prometheus  instance what serviceMonitors it should target.

https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/getting-started.md

```yaml
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
```
