### ISSUE TITLE
Bring back curl for better healthchecks and rest api interaction

### ISSUE THREAD

**Issue by paulschmeida** [emqx/emqx#11973]
### What would you like to be added or enhanced?

`curl` was available when emqx was based on alpine, but now that it's based on debian-slim, neither `curl` nor `wget` are available.
Unfortunately using `emqx ctl status` causes a huge CPU spike, so it's not appropriate to run as a healthcheck directive.
I have tested a healthcheck based on `curl`:
```
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://localhost:18083/api/v5/status | grep -z 'Node .* is started.*emqx is running' || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
```
and it doesn't cause the same CPU spike. 

Can we get `curl` added to the emqx image in the dockerfile? 

### Why is this needed?

Calling emqx ctl status causes a CPU spike, so it would be better to use curl to poll api/v5/status endpoint.
It would also allow for REST API interaction from within the container, which might be handy.

**Comment by id** [comment]
@paulschmeida we try to keep image size as small as possible.

How about this:

```
version: '3.9'

services:
  emqx:
    image: emqx:latest
    healthcheck:
      test: "bash -c \"exec 3<>/dev/tcp/localhost/18083; echo -e 'GET /api/v5/status HTTP/1.1\r\nhost: localhost\r\nConnection: close\r\n\r\n' >&3; grep -qz 'emqx is running' <&3\""
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: node1.emqx.io
    environment:
      - "EMQX_HOST=node1.emqx.io"
```
