### ISSUE TITLE
Authorization cache TTL not parsed correctly from configuration file

### ISSUE THREAD

**Issue by ddellarocca** [emqx/emqx#12756]
### What happened?

Hi,
I've set the following parameters under the authorization block to enable cache:
```HOCON
authorization {
  no_match = deny
  deny_action = disconnect
  cache {
    enable = true
    ttl = 1h
  }
}
```
But what I see from the dashboard is:
![image](https://github.com/emqx/emqx/assets/29358615/1a67a83b-fb59-487d-8ab5-8a3bd61292de)

### What did you expect to happen?

I expect to see the TTL parsed correctly. In the previous example I expected to see:
![image](https://github.com/emqx/emqx/assets/29358615/5623dc0e-02cd-4923-8118-c0e8886d4bd9)

### How can we reproduce it (as minimally and precisely as possible)?

Deploy EMQX and add the piece of config shown before.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
sysdescr  : EMQX
version   : 5.5.1
datetime  : 2024-03-21T14:54:24.433571725+00:00
uptime    : 5 minutes, 55 seconds
```

</details>

### OS version

<details>

```console
running on kind version 1.21.14
EMQX image: emqx:5.5.1
```

</details>

### Log files

<details>

</details>

**Comment by id** [comment]
Hi @ddellarocca.

I can't reproduce this.

```
docker run -d --name emqx -p 18083:18083 emqx/emqx:5.5.1
docker exec -it emqx bash
emqx@8b3aede63df1:/opt/emqx$ echo 'authorization {
  no_match = deny
  deny_action = disconnect
  cache {
    enable = true
    ttl = 1h
  }
}' >> etc/emqx.conf
emqx@8b3aede63df1:/opt/emqx$ cat etc/emqx.conf
## NOTE:
## This config file overrides data/configs/cluster.hocon,
## and is merged with environment variables which start with 'EMQX_' prefix.
##
## Config changes made from EMQX dashboard UI, management HTTP API, or CLI
## are stored in data/configs/cluster.hocon.
## To avoid confusion, please do not store the same configs in both files.
##
## See https://www.emqx.io/docs/en/v5.0/configuration/configuration.html for more details.
## Configuration full example can be found in etc/examples

node {
  name = "emqx@127.0.0.1"
  cookie = "emqxsecretcookie"
  data_dir = "data"
}

cluster {
  name = emqxcl
  discovery_strategy = manual
}

dashboard {
    listeners.http {
        bind = 18083
    }
}
authorization {
  no_match = deny
  deny_action = disconnect
  cache {
    enable = true
    ttl = 1h
  }
}
emqx@8b3aede63df1:/opt/emqx$ emqx ctl conf reload
load authorization on 'emqx@172.17.0.2' ok
load dashboard on 'emqx@172.17.0.2' ok
```

<img width="386" alt="image" src="https://github.com/emqx/emqx/assets/138221/e361536a-8db8-4d74-abc0-c8df2ef09244">

**Comment by ddellarocca** [comment]
Hi @id , actually I've deployed the cluster with the Operator, don't know if that could be the issue, the CRD is:
```yaml
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
spec:
  image: emqx:5.5.1
  config:
    data: |-
      authorization {
        no_match = deny
        deny_action = disconnect
        cache {
          enable = true
          ttl = 1h
        }
      }

  coreTemplate:
    spec:
      replicas: 1
```
