### ISSUE TITLE
Then enter in "Retained Messages" got 500 Internal Error

### ISSUE THREAD

**Issue by DieMetRik** [emqx/emqx#12834]
### What happened?

I think after update from 5.5.1 to 5.6.0 i got this error

### What did you expect to happen?

When click "Retained Messages" got 500 Internal Error
![image](https://github.com/emqx/emqx/assets/31734768/cde8af75-8e68-4809-a29e-f1f84e9952d8)

### Anything else we need to know?

Installed:
ProxmoxLXC->docker

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.6.0
datetime  : 2024-04-05T09:33:12.226225133+03:00
uptime    : 43 minutes, 51 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux zigbee 6.5.11-7-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.11-7 (2023-12-05T09:44Z) x86_64 GNU/Linux
```

</details>

### Log files

<details>

</details>

**Comment by zmstone** [comment]
`eaccess` hints a filesystem permission issue. could you check if the `emqx` user in docker is allowed to access the (maybe mounted) directory ?

**Comment by DieMetRik** [comment]
![image](https://github.com/emqx/emqx/assets/31734768/4ad0ba78-ab10-484a-bcc6-0bb3f3cdd31d)
My compose file
```
services:
  emqx:
    image: emqx/emqx:5.6.0
    container_name: emqx
    restart: always
    ports:
      - 1883:1883
      - 8084:8084
      - 8083:8083
      - 18083:18083
      - 8883:8883
    environment:
    - TZ=Europe/Moscow
    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log
volumes:
  vol-emqx-data:
    name: foo-emqx-data
  vol-emqx-etc:
    name: foo-emqx-etc
  vol-emqx-log:
    name: foo-emqx-log
```
