### ISSUE TITLE
Configuration fails to take effect about TCP Keep Alive behavior

### ISSUE THREAD

**Issue by hzms** [emqx/emqx#12862]
### What happened?

I care a lot about traffic，so i want to close TCP Keep Alive or increase the idle check time. I try to modify the conifg: listeners.tcp.default.tcp_options.keepalive, but it won't work. The EMQX Server always send the tcp keep alive package at15-second intervals.
![图片](https://github.com/emqx/emqx/assets/19644181/7309f573-48ee-47b9-ab83-80c58d407db3)
my emqx server run by docker image: 5.5.1, docker-compose config:

```
version: '3.3'
services:
  emqx:
    image: emqx:5.5.1
    ports:
      - 18085:18083
      - 1983:1883
    environment:
      #TCP_KEEPALIVE_TIME: 0,
      EMQX_NAME: "TEST-MQTT"
      EMQX_TELEMETRY__ENABLE: false
      EMQX_DASHBOARD__DEFAULT_USERNAME: admin
      EMQX_DASHBOARD__DEFAULT_PASSWORD: 123456
      EMQX_LISTENERS__TCP__DEFAULT__TCP_OPTIONS__KEEPALIVE: "5,3,2"
```

I try to set EMQX_LISTENERS__TCP__DEFAULT__TCP_OPTIONS__KEEPALIVE: "none", it doesn't work either.

my mqtt client is MQTTX and no special configuration:
![图片](https://github.com/emqx/emqx/assets/19644181/6126073b-2cfa-43c2-9493-3644722b4833)

Is this a bug?Or I didn't configure it the right way？

### What did you expect to happen?

config: listeners.tcp.default.tcp_options.keepalive fails to take effect

### EMQX version

$ emqx_ctl broker
sysdescr  : EMQX
version   : 5.5.1
datetime  : 2024-04-11T07:51:07.838431700+00:00
uptime    : 31 minutes, 33 seconds

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>
