### ISSUE TITLE
Add curl to docker image

### ISSUE THREAD

**Issue by lukas-mertens** [emqx/emqx#13282]
### What would you like to be added or enhanced?

Right now the dockerimage doesn't include curl or wget. I would like to implement the docker compose healthcheck though:

```
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18083/status"]
      interval: 5s
      timeout: 30s
      retries: 5
```

I made a draft PR of this: 
https://github.com/emqx/emqx/pull/13281

### Why is this needed?

The current situation makes it very hard to implement docker compose healthchecks.
