### ISSUE TITLE
can't get real ipaddress of clients

### ISSUE THREAD

**Issue by flyliu33** [emqx/emqx#13478]
### What happened?

program subscribed $SYS/brokers/+/clients/+/connected and "$SYS/brokers/+/clients/+/disconnected" topic，and could recieve the online and offline event from each clients. Whereas, the ipaddress from each clients ara as same as gateway of windows docker desktop, not the real ipaddress.
BTW, everything works well on latest Ubuntu regular docker version

### What did you expect to happen?

program should receive the real ipaddress

### How can we reproduce it (as minimally and precisely as possible)?

deploy emqx with latest windows docker desktop version, my windows docker desktop version is v4.29.0. And use the following docker compose code

```
name: emqx
services:
  emqx:
    image: emqx/emqx:5.7.1
    container_name: emqx
    restart:
      unless-stopped
    environment:
      - EMQX_AUTH__API__KEY=admin
      - EMQX_AUTH__API__SECRET=public
    ports:
      - "11842:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    volumes:
      - emqx-etc:/opt/emqx/etc
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
volumes:
    emqx-data:
    emqx-etc:
    emqx-log:
```

### EMQX version

<details>
5.7.1
</details>

### OS version

<details>
版本	Windows 11 专业版
版本号	23H2
安装日期	‎2024/‎4/‎23
操作系统版本	22631.3737
体验	Windows Feature Experience Pack 1000.22700.1009.0
</details>

### Log files

<details>

</details>
