### ISSUE TITLE
Unable to login the dashboard

### ISSUE THREAD

**Issue by Leonezz** [emqx/emqx#13568]
### What happened?

With a newly deployed emqx docker container (image tag:5.7.0), I cannot login the dashboard with default username and password, which in my tries is admin and public. Also I tried to customize the default accounts with EMQX_DASHBOARD__DEFAULT_USERNAME and EMQX_DASHBOARD__DEFAULT_PASSWORD envs, from what I see in the output of command `emqx ctl conf show` the envs take effects (I can see that dashboard.default_username and dashboard.default_password are set).
The client side errors are 401 bad request:
![image](https://github.com/user-attachments/assets/530a65b2-5b13-40c6-a4b6-83c38c03e22a)
![image](https://github.com/user-attachments/assets/b6aee4f2-f832-4137-9869-91549ddd3514)
![image](https://github.com/user-attachments/assets/28f5710b-430b-4b95-a320-d8f7d19feea7)

I tried to change various of my configs including docker compose envs etc and retried to login, all failed.

### What did you expect to happen?

The dashboard shoud be logged in.

### How can we reproduce it (as minimally and precisely as possible)?

docker compose snippet:
```yaml
  helmat-emqx:
    image: emqx:${EMQX_VERSION}
    container_name: helmat-emqx
    restart: always
    ports:
      - ${EMQX_TCP_PORT}:1883
      - ${EMQX_SSL_PORT}:8883
      - ${EMQX_WS_PORT}:8083
      - ${EMQX_WSS_PORT}:8084
      - ${EMQX_DASHBOARD_PORT}:18083
    volumes:
      - helmat-emqx_log:${EMQX_LOG_DIR}
      - helmat-emqx_etc:${EMQX_ETC_DIR}
      - helmat-emqx_data:${EMQX_DATA_DIR}
      - helmat-emqx_bootstrap:${EMQX_BOOTSTRAP_DIR}
    env_file:
      - .env
```

### Anything else we need to know?

I have tried tag 5.6.0, 5.6.1, 5.7.0 and 5.7.1, all failed. And none of these version reported an error log.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.7.0
datetime  : 2024-08-03T20:59:46.757169700+00:00
uptime    : 12 minutes, 27 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux THIS-DESKTOP 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Log files

<details>
[node_dump_20240803_210112.tar.gz](https://github.com/user-attachments/files/16482904/node_dump_20240803_210112.tar.gz)
[conf.dump.log](https://github.com/user-attachments/files/16482906/conf.dump.log)

</details>
