### ISSUE TITLE
AWK not found in docker

### ISSUE THREAD

**Issue by Tenyun** [emqx/emqx#13610]
### What happened?

When I start the container i get the following error message
`/opt/emqx/bin/emqx: line 960: awk: command not found`

### What did you expect to happen?

Start normaly.

### How can we reproduce it (as minimally and precisely as possible)?

docker-compose.yml 
```
services:
  # EMQX
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - t3_proxy
        #aliases:
        #- emqx
    expose:
      - 1883:1883
      - 18083:18083
    volumes:
      - $DOCKERDIR/appdata/emqx/data:/data
      - $DOCKERDIR/appdata/emqx/etc:/etc
      - $DOCKERDIR/appdata/emqx/log:/log
        #environment:
        #- EMQX_HOST=emqx
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.emqx-rtr.entrypoints=websecure"
      - "traefik.http.routers.emqx-rtr.rule=Host(`emqx.$DOMAINNAME_HL`)"
      # Middlewares
      - "traefik.http.routers.emqx-rtr.middlewares=chain-internal-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.emqx-rtr.service=emqx-svc"
      - "traefik.http.services.emqx-svc.loadbalancer.server.port=18083"
        #- "traefik.tcp.routers.emqx-svc.rule=HostSNI(`*`)"
        #- "traefik.tcp.services.emqx-svc-TCP.loadbalancer.server.port=1883"
        #- "traefik.tcp.routers.emqx-svc.entrypoints=mqtt"
```

### Anything else we need to know?

Please note that i use traefik to communicate with emqx and that due to the problems i am currently experimenting a lot to find a solution.

### EMQX version

docker emqx/emqx:latest

### OS version

docker on ubuntu 24.04

### Log files

<details>

</details>
