### ISSUE TITLE
docker start fail: emqx  | logger: socket /dev/log: No such file or directory

### ISSUE THREAD

**Issue by shushenghong** [emqx/emqx#13890]
### What happened?

[+] Running 1/0
 ✔ Container emqx  Created                                                                                                                                      0.0s 
Attaching to emqx
emqx  | hostname: Name or service not known
emqx  | WARNING: Default (insecure) Erlang cookie is in use.
emqx  | WARNING: Configure node.cookie in /opt/emqx/etc/emqx.conf or override from environment variable EMQX_NODE__COOKIE
emqx  | WARNING: NOTE: Use the same cookie for all nodes in the cluster.
emqx  | EMQX_DASHBOARD__DEFAULT_PASSWORD [dashboard.default_password]: ******
emqx  | EMQX_RPC__PORT_DISCOVERY [rpc.port_discovery]: manual
emqx  | EMQX_NODE__NAME [node.name]: emqx@127.0.0.1
emqx  | logger: socket /dev/log: No such file or directory
emqx exited with code 1

### What did you expect to happen?

start success

### EMQX version

```
emqx:
    container_name: emqx
    image: emqx/emqx:5.7.0
    restart: always
    network_mode: "host"
    volumes:
      - ./data/emqx:/opt/emqx/data
      - ./logs/emqx:/opt/emqx/log
```

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Kylin Linux Advanced Server"
VERSION="V10 (Sword)"
ID="kylin"
VERSION_ID="V10"
PRETTY_NAME="Kylin Linux Advanced Server V10 (Sword)"
ANSI_COLOR="0;31"
$ uname -a
Linux 4.19.90-25.26.v2101.ky10.aarch64 #1 SMP Sun Apr 23 15:26:25 CST 2023 aarch64 aarch64 aarch64 GNU/Linux
```

</details>

### Log files

<details>

</details>

**Comment by id** [comment]
Literally this exact compose file works just fine for me

```
services:
  emqx:
    container_name: emqx
    image: emqx/emqx:5.7.0
    restart: always
    network_mode: "host"
    volumes:
      - ./data/emqx:/opt/emqx/data
      - ./logs/emqx:/opt/emqx/log
```

```
docker compose up
[+] Running 1/1
 ✔ Container emqx  Created                                                                                           0.5s
Attaching to emqx
emqx  | WARNING: Default (insecure) Erlang cookie is in use.
emqx  | WARNING: Configure node.cookie in /opt/emqx/etc/emqx.conf or override from environment variable EMQX_NODE__COOKIE
emqx  | WARNING: NOTE: Use the same cookie for all nodes in the cluster.
emqx  | EMQX_RPC__PORT_DISCOVERY [rpc.port_discovery]: manual
emqx  | EMQX_NODE__NAME [node.name]: emqx@192.168.65.3
emqx  | Listener ssl:default on 0.0.0.0:8883 started.
emqx  | Listener tcp:default on 0.0.0.0:1883 started.
emqx  | Listener ws:default on 0.0.0.0:8083 started.
emqx  | Listener wss:default on 0.0.0.0:8084 started.
emqx  | Listener http:dashboard on :18083 started.
emqx  | EMQX 5.7.0 is running now!
```
