### ISSUE TITLE
容器重启后，Dashboard中的配置会丢失

### ISSUE THREAD

**Issue by solekubi** [emqx/emqx#14412]
### What happened?

1、挂载了/opt/emqx/data，并且自定义/opt/emqx/etc/emqx.conf内容，部分如下：
```conf
exhook {
  servers = [
    {
      auto_reconnect = "60s"
      enable = false
      failed_action = "deny"
      name = "test"
      pool_size = 16
      request_timeout = "5s"
      ssl {
        ciphers = []
        depth = 10
        enable = false
        hibernate_after = "5s"
        reuse_sessions = true
        secure_renegotiate = true
        verify = "verify_peer"
        versions = ["tlsv1.3", "tlsv1.2", "tlsv1.1", "tlsv1"]
      }
      url = "http://xxxxxx:8080"
    }
  ]
}
```
![image](https://github.com/user-attachments/assets/a2c24a25-d03d-4636-89d3-2e7db887ff26)

2、Dashboard中把是否启动改成true，然后重启容器，是否启动会被重置为false

3、cat /opt/emqx/data/configs/cluster.hocon，发现配置已经修改，但是实际却不生效
```conf
exhook {
  servers = [
    {
      auto_reconnect = "60s"
      enable = true
      failed_action = "deny"
      name = "test"
      pool_size = 16
      request_timeout = "5s"
      ssl {
        ciphers = []
        depth = 10
        enable = false
        hibernate_after = "5s"
        reuse_sessions = true
        secure_renegotiate = true
        verify = "verify_peer"
        versions = ["tlsv1.3", "tlsv1.2", "tlsv1.1", "tlsv1"]
      }
      url = "http://xxxxxx:8080"
    }
  ]
}
```
4、测试了其他配置，包括规则，连接器等，重启之后均丢失

### What did you expect to happen?

重启容器后，Dashboard中修改的内容不丢失

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.8.2
datetime  : 2024-12-13T22:05:26.893218364+08:00
uptime    : 4 minutes, 40 seconds
```

docker方式安装，docker-compose.yaml 如下
```yaml
services:
  emqx:
    image: emqx/emqx:5.8.2
    container_name: emqx
    restart: unless-stopped
    user: root
    privileged: true
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    environment:
      - "EMQX_NAME=emqx"
      - "TZ=Asia/Shanghai"
    volumes:
      - ./data:/opt/emqx/data
      - ./etc:/opt/emqx/etc
    ports:
      - 1883:1883
      - 18083:18083
```
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux mm 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 GNU/Linux
```

</details>

### Log files

<details>

</details>
