### ISSUE TITLE
Running Emqx on Docker but healthy check failed

### ISSUE THREAD

**Issue by iccfish** [emqx/emqx#14490]
### What happened?

Runnging emqx v2.8.3 via docker using the following compose file:

```
services:
  emqx1:
    image: emqx:latest
    container_name: emqx1
    restart: unless-stopped
    environment:
    - "EMQX_NODE_NAME=emqx@172.23.146.93"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@172.23.146.93]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    volumes:
      - /data/emqx/data:/opt/emqx/data
      - /data/emqx/log:/opt/emqx/log
```

Logs in docker shows that emqx started successfully.

Visit `http://172.23.146.93:18083/status` in browser shows that emqx running:
>Node eqmx@172.23.146.93 is started
emqx is running

And dashboard works well.

But container heathly check failed. Run `bin/emqx_ctl ctl status` in container manually, this command shows:
>Node 'eqmx@172.23.146.93' not responding to pings.

Running `curl http://172.23.146.93:18083/status` in emqx container does got the correct response:
>Node eqmx@172.23.146.93 is started
emqx is running

Now I can not figure out what's wrong with this setup.

### What did you expect to happen?

I excepted healthy check should passed.

### EMQX version

v2.8.3

### OS version

<details>

CentOS7 (Core)

</details>

### Log files

<details>

</details>
