### ISSUE TITLE
CRL check not working properly

### ISSUE THREAD

**Issue by haritzsaiz** [emqx/emqx#14635]
### What happened?

I have configured EMQX to perform mTLS. The client sends its certificate to EMQX and it is then validated against the configured CACERTFILE. The next step I tried was to enable CRL checking, but I'm stuck here. When the server recieves the client connection, the following log is generated. which could point that the presented client cert does not have a CRL as an extension, but as you can see, there is in fact a CRL

![Image](https://github.com/user-attachments/assets/3b2da94c-36dc-4a3c-bcf1-7681be1f64f7)

![Image](https://github.com/user-attachments/assets/6020638d-dc78-41d8-ad5b-ac1311d6c44e)

I don't know if im not configuring EMQX correctly or I'm not using a "valid" certificate. 

### What did you expect to happen?

EMQX fetches the CRL pointed in the certificate

### How can we reproduce it (as minimally and precisely as possible)?

 Here is both the docker compose file im using, as well as the PEM for the client certificate: 

```
services:
  emqx:
    image: "emqx/emqx:5.8.2"
    ports: 
    - 18083:18083
    - 8883:8883
    volumes:
      - ./certs:/home/lamassu
    environment:
      EMQX_LOG__CONSOLE__LEVEL: "debug"
      EMQX_NODE__NAME: "emqx@127.0.0.1"
      EMQX_NODE__DATA_DIR: "data"

      EMQX_DASHBOARD__DEFAULT_PASSWORD: "admin"
      EMQX_DASHBOARD__DEFAULT_USERNAME: "admin"
      EMQX_DASHBOARD__LISTENERS__HTTP__BIND: "0.0.0.0:18083"

      EMQX_LISTENERS__SSL__DEFAULT__BIND: "0.0.0.0:8883"
      EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__CACERTFILE: "/home/lamassu/ca.crt"
      EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__CERTFILE: "/home/lamassu/emqx.crt"
      EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__KEYFILE: "/home/lamassu/emqx.key"
      EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__VERIFY: "verify_peer"
      EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__FAIL_IF_NO_PEER_CERT: "true"
      EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__ENABLE_CRL_CHECK: "true"
```

```
-----BEGIN CERTIFICATE-----
MIIDJTCCAsugAwIBAgIRALRomUl8s2pRJ0Uw+HeKcnQwCgYIKoZIzj0EAwIwFDES
MBAGA1UEAxMJQ0EtcGxjLTEwMB4XDTI1MDIwMzE0MzU0NloXDTI2MDIwMzE0MzU0
NlowDTELMAkGA1UEAxMCMTAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQClBu+TwEABNzNDUNwa4CosgpHmNVoZaZt/uEzmwFykG4KAn9UYqMkP5j5QGh6M
nl5iSk90XmkqQ7IdkCrcx1yuEtKTtmCxf3M4SHB3GrmFkQ6PnAbPGsQB5G/YJwDQ
LbOFu70AjdD39UDvMUeziSgOZM9ueo9cv1+hCeQSSBJ/Miv/rs1jL7j5XJzb5wNP
MiXAKIc5kZs5CWKfYSnYLNzZ+mkAU9JvI5wSHzkWp2Uzg+nUEbFsLVdcerBFmJa4
VxxMzpUA+I5WXwgYXKG86WuPXiE5+g5yAx9Gxkr7OfzJvr768wcUipK4Xr18QAet
4SYWeeQlYUIOsY38JYRqcuk9AgMBAAGjggE4MIIBNDAdBgNVHSUEFjAUBggrBgEF
BQcDAgYIKwYBBQUHAwEwSwYDVR0jBEQwQoBAMTBlYzMxNmI2ODYyOWMxMzQ4NTA5
Mjg5YTgxMDBhMDkxOGZhNGZhMzRkZGZlMjMxNWM3N2Q0ZWIzYjY3MjY2MDBDBggr
BgEFBQcBAQQ3MDUwMwYIKwYBBQUHMAGGJ2h0dHA6Ly9ob3N0LmRvY2tlci5pbnRl
cm5hbC9hcGkvdmEvb2NzcDCBgAYDVR0fBHkwdzB1oHOgcYZvaHR0cDovL2hvc3Qu
ZG9ja2VyLmludGVybmFsL2FwaS92YS9jcmwvMTBlYzMxNmI2ODYyOWMxMzQ4NTA5
Mjg5YTgxMDBhMDkxOGZhNGZhMzRkZGZlMjMxNWM3N2Q0ZWIzYjY3MjY2MC5jcmwu
cGVtMAoGCCqGSM49BAMCA0gAMEUCIQCqQq7dGYTJtWIXeRxhXBd7+B8cUmUb7+7u
0g+rMOhN0wIgb90ZTpPjPRjB4i5HjlqxzrFA3NngaxbWd3x1DgbjWEM=
-----END CERTIFICATE-----
```

### EMQX version

<details>

docker image emqx 5.8.2

</details>

### OS version

<details>

docker image emqx 5.8.2

</details>

### Log files

<details>

</details>
