### ISSUE TITLE
After restart docker-container built-in database empty

### ISSUE THREAD

**Issue by GerdRuetten** [emqx/emqx#14804]
### What happened?

 I run emqx on my machine as a docker container, created as stack under portainer..
After first start, i change the password from public to myownpw

For authentication and authorization i use the built-in-database.

After restart the container, the default account and password of the dashboard(login page) became admin/public again, and the authentication and authorization information in the built-in database were lost.

### What did you expect to happen?

when I start emqx docker container again:
1.username and password of dashboard are as set in the emqx.conf
2.data in buil-in-dabase still exists

### Anything else we need to know?

My portainer-stack:

```
services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 1883:1883 #default mqtt port
      - 8083:8083
      - 8084:8084 
      - 8883:8883 
      - 18083:18083
    volumes:
      - /opt/containers/emqx/data:/opt/emqx/data
      - /opt/containers/emqx/log:/opt/emqx/log
      - /opt/containers/emqx/etc:/opt/emqx/etc
      - /opt/containers/emqx/etc/emqx.conf:/opt/emqx/etc/emqx.conf
    networks:
      - homelab
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5

networks:
  homelab:
    external: true
```

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```
v5.8.5
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>
