### ISSUE TITLE
Missing org labels on emqx docker image referenced in Operator docs

### ISSUE THREAD

**Issue by morotsgurka** [emqx/emqx#14978]
### What happened?

The regular emqx docker image (used by the EMQX Operator cluster deployment) [as explained in the docs](https://docs.emqx.com/en/emqx-operator/latest/getting-started/getting-started.html#emqx-open-source-5) does not have the org.opencontainers.image.* labels and because of it, Renovate bot cannot pull the release notes from this repo.

### What did you expect to happen?

That the emqx container has the labels, or that the "emqx" image is removed/deprecated and the documentation is updated to use the emqx/emqx image, since it has the labels. (if they are the same image).

### How can we reproduce it (as minimally and precisely as possible)?

Pulling the emqx:5.8.6 image by:
```bash
docker pull emqx:5.8.6
````
then inspecting it with
```bash
docker inspect emqx:5.8.6 | grep org.
```
It does not have these labels:
org.opencontainers.image.source
org.opencontainerse.image.version
etc.

Pulling the emqx/emqx:5.8.6 image and inspecting it does have the expected labels:
```yaml
"org.opencontainers.image.created": "2025-03-25T12:17:13Z",
"org.opencontainers.image.description": "Official docker image for EMQX, the most scalable open-source MQTT broker for IoT, IIoT, and connected vehicles.",
"org.opencontainers.image.documentation": "https://www.emqx.io/docs/en/latest/",
"org.opencontainers.image.edition": "Opensource",
"org.opencontainers.image.licenses": "Apache-2.0",
"org.opencontainers.image.otp.version": "26.2.5.2-3",
"org.opencontainers.image.revision": "b895cdcd8cbc34c5f8fc5ea8b948cd2c40bba0fc",
"org.opencontainers.image.source": "https://github.com/emqx/emqx",
"org.opencontainers.image.title": "emqx",
"org.opencontainers.image.url": "https://www.emqx.io",
"org.opencontainers.image.version": "5.8.6",

```

### Anything else we need to know?

I've looked at the Github action and make script + build it and the local image had the labels. Once if found that the emqx/emqx had the labels i stopped.

### EMQX version

<details>
5.8.6
</details>
