### ISSUE TITLE
docker(emqx/emqx:5.8.6)，coap内置数据库创建客户端，重启docker后数据丢失

### ISSUE THREAD

**Issue by GeXin666** [emqx/emqx#14984]
### What happened?

`docker run \
--name emqx \
-v /etc/localtime:/etc/localtime \
-v emqx_etc:/opt/emqx/etc \
-v emqx_data:/opt/emqx/data \
-v emqx_log:/opt/emqx/log \
-p 1883:1883 \
-p 8083:8083 \
-p 8084:8084 \
-p 8883:8883 \
-p 18083:18083 \
-p 5683:5683/udp \
-d --restart unless-stopped \
emqx/emqx:5.8.6`

docker安装emqx/emqx:5.8.6，开启coap网关，然后使用内置数据库创建客户端数据，接着重启docker，创建的客户端数据丢失。

### What did you expect to happen?

docker安装emqx/emqx:5.8.6，开启coap网关，然后使用内置数据库创建客户端数据，接着重启docker，创建的客户端数据丢失。

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by id** [comment]
Hi @GeXin666. This issue is likely related to database directory being named after node name. Since by default EMQX would use node IP, and IP address in docker containers is ephemeral, you get new directory each time you restart the container.

While we are discussing how to best address this issue, try to use a docker compose file (or run container with similar arguments) where container is assigned a static hostname and set `EMQX_NODE_NAME` accordingly. Something like this:

```
services:
  emqx:
    image: emqx:5.8.6
    container_name: emqx
    environment:
    - "EMQX_NODE_NAME=emqx@node1.emqx.io"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    volumes:
      - ./data:/opt/emqx/data
      - ./logs:/opt/emqx/log
    networks:
      emqx-bridge:
        aliases:
        - node1.emqx.io
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083 

networks:
  emqx-bridge:
    driver: bridge
```
