### ISSUE TITLE
Documentation states hostnames are supported for node names but implementation requires FQDN (docker)

### ISSUE THREAD

**Issue by cford1080** [emqx/emqx#15269]
### What happened?

I had a working instance of EMQX, but after making some changes to my docker networks, I ended up having issues with the node. After reading through the docs, I decided I wanted to use my docker hostname to identify the node, as the documentation states should be possible.

> https://docs.emqx.com/en/emqx/latest/deploy/install-docker.html#use-docker-to-run-a-single-emqx-node
EMQX employs the data/mnesia/<node_name> directory for data storage. It's crucial to choose a stable identifier, such as a `hostname` or Fully Qualified Domain Name (FQDN), to serve as the node name. This practice avoids data loss caused by node name changes.

However, when I check the status, it fails

```bash
emqx@emqx:/opt/emqx$ /opt/emqx/bin/emqx_ctl status
Node emqx@emqx not responding to pings.
```

If I use this status check as the container healtcheck, of course the container never becomes healthy. However, if I omit the healthcheck, the container works seemingly fine, but this status check still fails when I manually execute it inside the container. The healthcheck is needed to delay the start of other containers which rely on MQTT.

### What did you expect to happen?

I expected that the status check could rely on the simple hostname, as long as that hostname was resolvable, and in my case it is.

Within the container, I can verify the hostname does resolve to an ip address

```bash
emqx@emqx:/opt/emqx$ getent hosts emqx
172.16.21.6     emqx
```

### How can we reproduce it (as minimally and precisely as possible)?

This will produce the issue I'm seeing. this happens with and without an alias on the network> i've included it to show that I've attempted this solution. I also included the env var `EMQX_HOST` to no avail.

```yaml
services:
  emqx:
    image: emqx/emqx-enterprise:5.9
    container_name: emqx
    hostname: emqx
    environment:
      - EMQX_HOST=emqx
      - EMQX_NODE_NAME=emqx@emqx
    networks:
      mqtt:
        ipv4_address: 172.16.21.6
        aliases:
          - emqx
    # healthcheck:
    #   test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
networks:
  mqtt:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.22.0/24
          gateway: 172.16.22.1
```

However, thie following will work as expected (though, I do not wish to augment my hostname). Again, this works with and without an alias on the network. I have not included the alias or host env var this time to illustrate that even without them, the hostname resolution succeeds.

```yaml
services:
  emqx:
    image: emqx/emqx-enterprise:5.9
    container_name: emqx
    hostname: emqx.bahbahblacksheep
    environment:
      - EMQX_NODE_NAME=emqx@emqx.bahbahblacksheep
    networks:
      mqtt:
        ipv4_address: 172.16.21.6
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  mqtt:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.22.0/24
          gateway: 172.16.22.1
```

```bash
emqx@emqx:/opt/emqx$ /opt/emqx/bin/emqx_ctl status
Node 'node1@emqx.bahbahblacksheep' 5.9.0 is started
```

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX Enterprise
version   : 5.9.0
datetime  : 2025-05-27T01:30:51.659337194+00:00
uptime    : 3 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.2 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

$ uname -a
Linux server 6.8.0-60-generic #63-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 15 19:04:15 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
```

</details>
