### ISSUE TITLE
When I try to visit dashboard, emqx will crash.

### ISSUE THREAD

**Issue by andares** [emqx/emqx#2023]
#### Environment

- OS: Docker in Ubuntu 16.04
- Erlang/OTP: 21?
- EMQ: 3.0 rc-5

#### Description

I install emqx with docker, and use docker-compose.json:

```yaml
version: "3.3"
services:
  emqx:
    image: emqx/emqx
    environment:
      EMQX_ALLOW_ANONYMOUS: 'false'
      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_jwt"
      EMQX_ADMIN_PASSWORD: "xxxxxxxx" # username is admin
      EMQX_AUTH__JWT__SECRET: "xxxxxxxxxxx"
      EMQX_LISTENER__WSS__EXTERNAL__KEYFILE: etc/certs/ssl/xxxxx.key
      EMQX_LISTENER__WSS__EXTERNAL__CERTFILE: etc/certs/ssl/xxxxxxx.crt
    ports:
      - '18083:18083'
      - '1883:1883'
      - '8083:8083'
      - '8084:8084'
      - '8883:8883'
      - '8884:8884'
    volumes:
      - type: bind
        source: ./ssl
        target: /opt/emqx/etc/certs/ssl
```

It's all is OK.

but today, I try to change retainer config, and then emqx will crash when dashboard is visited.

```yaml
      EMQX_RETAINER__STORAGE_TYPE: disc
      EMQX_RETAINER__MAX_RETAINED_MESSAGES: 500000
      EMQX_RETAINER__MAX_PAYLOAD_SIZE: '32KB'
      EMQX_RETAINER__EXPIRY_INTERVAL: 0
```

docker logs:

```
emqx_1  | EMQX_LOADED_PLUGINS=emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_jwt
emqx_1  | emqx 3.0 is started successfully!
emqx_1  | Start http:management listener on 8080 successfully.
emqx_1  | Start http:dashboard listener on 18083 successfully.
emqx_1  | Start mqtt:tcp listener on 127.0.0.1:11883 successfully.
emqx_1  | Start mqtt:tcp listener on 0.0.0.0:1883 successfully.
emqx_1  | Start mqtt:ws listener on 0.0.0.0:8083 successfully.
emqx_1  | Start mqtt:ssl listener on 0.0.0.0:8883 successfully.
emqx_1  | Start mqtt:wss listener on 0.0.0.0:8084 successfully.
emqx_1  | EMQ X Broker v3.0-rc.5 is running now!
emqx_1  | Eshell V10.0.6  (abort with ^G)
emqx_1  | (70dbd9993b14@172.19.0.2)1> ['2018-12-04T08:20:12Z']:emqx start
emqx_1  | ['2018-12-04T08:20:12Z']:admin password changed to xxxxxxxxxx
emqx_1  | ok
emqx_1  | Node '70dbd9993b14@172.19.0.2' not responding to pings.
emqx_1  | ['2018-12-04T08:21:58Z']:emqx not running, waiting for recovery in 20 seconds
emqx_1  | [os_mon] memory supervisor port (memsup): Erlang has closed
emqx_1  | Node '70dbd9993b14@172.19.0.2' not responding to pings.
emqx_1  | ['2018-12-04T08:22:04Z']:emqx not running, waiting for recovery in 15 seconds
emqx_1  | Node '70dbd9993b14@172.19.0.2' not responding to pings.
emqx_1  | ['2018-12-04T08:22:09Z']:emqx not running, waiting for recovery in 10 seconds
emqx_1  | Node '70dbd9993b14@172.19.0.2' not responding to pings.
emqx_1  | ['2018-12-04T08:22:15Z']:emqx not running, waiting for recovery in 5 seconds
emqx_1  | Node '70dbd9993b14@172.19.0.2' not responding to pings.
emqx_1  | ['2018-12-04T08:22:20Z']:emqx not running, waiting for recovery in 0 seconds
emqx_1  | ['2018-12-04T08:22:25Z']:emqx exit abnormally
```

I try to rollback docker-compose.json, remove retainer config. Kill and remove docker container, remove docker image, reboot host.. but all fail, problem always exists.

other change may be nginx user change to other, and change docker-compose.json parent dir to 700(with same user as nginx). now dashboard open will be blank page, and make emqx crash..
