### ISSUE TITLE
use k8s auto cluster not found

### ISSUE THREAD

**Issue by aq2004723** [emqx/emqx#2161]
#### Environment

- OS: linux
- Erlang/OTP: 

R21/10.2 |  
-- | --

- EMQ:  v3.0

#### Description

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: emqx
  labels:
        app: emqx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
      - name: emqx
        image: emqx/emqx:latest
        ports:
        - name: emqx-dashboard
          containerPort: 18083
        - name: emqx-tcp
          containerPort: 1883
        - name: emqx-ssl
          containerPort: 8883
        - name: emqx-ws
          containerPort: 8083
        - name: emqx-wss
          containerPort: 8084
        env:
        - name: EMQX_CLUSTER__DISCOVERY
          value: k8s
        - name: EMQX_NAME
          value: emqx
        - name: EMQX_CLUSTER__K8S__APISERVER
          value: https://xxx.k8s-g1.cn-hangzhou.aliyuncs.com:6443
        - name: EMQX_CLUSTER__K8S__NAMESPACE
          value: default
        - name: EMQX_CLUSTER__K8S__SERVICE_NAME
          value: emqx
        - name: EMQX_CLUSTER__K8S__ADDRESS_TYPE
          value: dns
        - name: EMQX_CLUSTER__K8S__APP_NAME
          value: emqx
        tty: true
```

but  when i exec `kubectl exec -it emqx-7ff949bbb9-c4s82 /opt/emqx/bin/emqx_ctl cluster status `
it returns
```
[{running_nodes,['emqx@172.20.1.56']}]
```

not Not expected 3
and other 2 pods is alse only rerurn one nodes
