### ISSUE TITLE
K8s cluster one node doesn't join

### ISSUE THREAD

**Issue by wajidp** [emqx/emqx#2216]
#### Environment

- OS: CentOS 7 with Kubernetes
- Erlang/OTP: 21
- EMQ: 3

#### Description

I have setup emqx cluster on k8s based on below article and i have a replica of 3 find my yaml below
https://medium.com/@emqtt/emq-x-auto-cluster-in-kubernetes-3e265f3870ad
```
apiVersion: v1
kind: Service
metadata:
  name: emqx
spec:
  ports:
  - name: dashboard
    port: 32333
    nodePort: 32333
    targetPort:  emqx-dashboard
    protocol: TCP
  - name: mqtt
    port: 1883
    nodePort: 31883
    protocol: TCP
  selector:
    app: emqx
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: emqx
  labels:
        app: emqx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
      - name: emqx
        image: emqx/emqx:latest
        ports:
        - name: emqx-dashboard
          containerPort: 18083
        env:
        - name: EMQX_CLUSTER__DISCOVERY
          value: k8s
        - name: EMQX_NAME
          value: emqx
        - name: EMQX_CLUSTER__K8S__APISERVER
          value: http://192.168.53.71:8080
        - name: EMQX_CLUSTER__K8S__NAMESPACE
          value: default
        - name: EMQX_CLUSTER__K8S__SERVICE_NAME
          value: emqx
        - name: EMQX_CLUSTER__K8S__ADDRESS_TYPE
          value: ip
        - name: EMQX_CLUSTER__K8S__APP_NAME
          value: emqx
        tty: true

kubectl get pods -o wide
emqx-78f4b856c7-2tklc                1/1     Running   0          9m11s   10.244.1.84 
emqx-78f4b856c7-5pzm4                1/1     Running   0          9m11s   10.244.0.68 
emqx-78f4b856c7-hp7v5                1/1     Running   0          9m11s   10.244.3.72  

kubectl exec emqx-78f4b856c7-2tklc /opt/emqx/bin/emqx_ctl  cluster status
Cluster status: [{running_nodes,['emqx@10.244.0.68','emqx@10.244.1.84']}]

kubectl exec emqx-78f4b856c7-5pzm4 /opt/emqx/bin/emqx_ctl  cluster status
Cluster status: [{running_nodes,['emqx@10.244.1.84','emqx@10.244.0.68']}]

kubectl exec emqx-78f4b856c7-hp7v5   /opt/emqx/bin/emqx_ctl  cluster status
Cluster status: [{running_nodes,['emqx@10.244.3.72']}]

```

Here the last node doesn't join. What will be the reason?

In emqx dashboard the nodes & stats jumps changes each time. sometime its just one or two
