### ISSUE TITLE
postgres reconnect

### ISSUE THREAD

**Issue by najeal** [emqx/emqx#2386]
#### Environment

- OS: Container-Optimized OS
- EMQ: docker image emqx/emqx:v3.0.1

#### Description

I deploy emqx as Deployment on Kubernetes. I use Postgres authentication.
My emqx Deployment logs often `login failed for auth_modules_not_found`, then I need to restart my emqx pod. Is there any workaround to force emqx to reconnect to Postgres?

**Comment by zhanghongtong** [comment]
@najeal Need more detailed information

**Comment by najeal** [comment]
Hi @zhanghongtong , I paste below.
I specify that I can successfully login after the restart of the service and use it during several minutes.

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: emqx
  namespace: default

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: emqx
subjects:
- kind: ServiceAccount
  name: emqx
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: emqx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  ports:
  - name: wsocket
    port: 32083
    targetPort: 8083
  - name: tlswsocket
    port: 32084
    targetPort: 8084
  - name: tcppart
    port: 32683
    targetPort: 1883
  - name: mqtts
    port: 32688
    targetPort: 8883
  - name: dashboard
    port: 32333
    targetPort:  18083
    protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: emqx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/part-of: ingress-nginx
    spec:
      serviceAccountName: emqx
      volumes:
      - name: foo
        secret:
          secretName: foosecret
          items:
          - key: tls.crt
            path: tls/my-cert.pem
      - name: foo2
        secret:
          secretName: foo2secret
          items:
          - key: tls.key
            path: tls/my-key.pem
      - name: letca
        secret:
          secretName: letca-secret
          items:
          - key: letsenc.pem
            path: tls/ca.pem
      containers:
      - name: emqx
        image: emqx/emqx:v3.0.1
        volumeMounts:
        - name: foo
          mountPath: "/opt/emqx/etc/foo"
          readOnly: true
        - name: foo2
          mountPath: "/opt/emqx/etc/foo2"
          readOnly: true
        - name: letca
          mountPath: "/opt/emqx/etc/letsca"
          readOnly: true
        ports:
        - name: emqx-tcp
          containerPort: 1883
        - name: mqtts
          containerPort: 8883
        - name: emqx-ws
          containerPort: 8083
        - name: emqx-wss
          containerPort: 8084
        - name: emqx-dashboard
          containerPort: 18083
        env:
        - name: EMQX_ENABLE__ACL__CACHE
          value: "off"
        - name: EMQX_LOADED_PLUGINS
          value: "emqx_management,emqx_auth_pgsql,emqx_recon,emqx_retainer,emqx_dashboard"
        - name: EMQX_LISTENER__SSL__EXTERNAL__TLS_VERSIONS
          value: "tlsv1.2,tlsv1.1,tlsv1"
        - name: EMQX_LISTENER__WSS__EXTERNAL__TLS_VERSIONS
          value: "tlsv1.2,tlsv1.1,tlsv1"
        # - name: EMQX_LISTENER__SSL__EXTERNAL__VERIFY
        #   value: verify_none
        # - name: EMQX_LISTENER__SSL__EXTERNAL__FAIL_IF_NO_PEER_CERT
        #   value: "false"
        - name: EMQX_LISTENER__SSL__EXTERNAL__CACERTFILE
          value: "/opt/emqx/etc/letsca/tls/ca.pem"
        - name: EMQX_LISTENER__SSL__EXTERNAL__KEYFILE
          value: "/opt/emqx/etc/foo2/tls/my-key.pem"
        - name: EMQX_LISTENER__SSL__EXTERNAL__CERTFILE
          value: "/opt/emqx/etc/foo/tls/my-cert.pem"
        - name: EMQX_LISTENER__WSS__EXTERNAL__CACERTFILE
          value: "/opt/emqx/etc/letsca/tls/ca.pem"
        - name: EMQX_LISTENER__WSS__EXTERNAL__KEYFILE
          value: "/opt/emqx/etc/foo2/tls/my-key.pem"
        - name: EMQX_LISTENER__WSS__EXTERNAL__CERTFILE
          value: "/opt/emqx/etc/foo/tls/my-cert.pem"
        - name: EMQX_ALLOW_ANONYMOUS
          value: 'false'
        - name: EMQX_ACL_NOMATCH
          value: deny
        - name: EMQX_CLUSTER__DISCOVERY
          value: k8s
        - name: EMQX_NAME
          value: emqx
        - name: EMQX_CLUSTER__K8S__APISERVER
          value: https://kubernetes.default.svc:443
        - name: EMQX_CLUSTER__K8S__NAMESPACE
          value: default
        - name: EMQX_CLUSTER__K8S__SERVICE_NAME
          value: emqx
        - name: EMQX_CLUSTER__K8S__ADDRESS_TYPE
          value: ip
        - name: EMQX_CLUSTER__K8S__APP_NAME
          value: emqx
        - name: EMQX_LOG__LEVEL
          value: debug
        - name: EMQX_AUTH__PGSQL__SERVER
          value: "postgres-service:5432"
        - name: EMQX_AUTH__PGSQL__USERNAME
          value: postgresusername
        - name: EMQX_AUTH__PGSQL__PASSWORD
          value: mypostgrespasword
        - name: EMQX_AUTH__PGSQL__DATABASE
          value: mqtt
        - name: EMQX_AUTH__PGSQL__PASSWORD_HASH
          value: "bcrypt,salt"
        - name: EMQX_AUTH__PGSQL__AUTH_QUERY
          value: "select password, substring(password, 0, 30) as salt from mqtt_user where username = '%u' limit 1"
        tty: true
```
