### ISSUE TITLE
How to to configure emqx-web-hook with emqx-docker?

### ISSUE THREAD

**Issue by PMExtra** [emqx/emqx#2398]
#### Environment

`emqx/emqx-docker:v3.1-beta.3` docker container.

#### Description

The `emqx-web-hook` has a [default config file](https://github.com/emqx/emqx-web-hook/blob/master/etc/emqx_web_hook.conf) that worked with all the events.

In my case, I want only the `client_connected` and `client_disconnected` hook.

I'm using [emqx-docker](https://github.com/emqx/emqx-docker) to host emqx, and the emqx was in a docker-compose file that would be used to auto scaling. So I have to configure all the settings by the container environments.

So I've tried set
```yaml
      - EMQX_WEB__HOOK__API__URL=http://${API_GATEWAY}/callback/emq/webhook
      - 'EMQX_WEB__HOOK__RULE__CLIENT__CONNECTED__1={"action": "client_connect"}'
      - 'EMQX_WEB__HOOK__RULE__CLIENT__DISCONNECTED__1={"action": "client_disconnect"}'
      - 'EMQX_WEB__HOOK__RULE__CLIENT__SUBSCRIBE__1='
      - 'EMQX_WEB__HOOK__RULE__CLIENT__UNSUBSCRIBE__1='
      - 'EMQX_WEB__HOOK__RULE__SESSION_CREATED_1='
      - 'EMQX_WEB__HOOK__RULE__SESSION_TERMINATED_1='
      - 'EMQX_WEB__HOOK__RULE__SESSION_SUBSCRIBED_1='
      - 'EMQX_WEB__HOOK__RULE__SESSION_UNSUBSCRIBED_1='
      #...
```

But emqx report `Syntax error in /opt/emqx/data/configs/app.2019.04.02.13.32.24.conf`.
So how can I override and disable the default settings such as `web.hook.rule.client.subscribe.1`?

**Comment by zhanghongtong** [comment]
@PMExtra Can you share the full content of emqx in the `docker-compose.yaml`?

**Comment by PMExtra** [comment]
```yaml
version: "3"

volumes:
  emqx-data:
  emqx-lib:

services:
  emqx:
    image: emqx/emqx:v3.1-beta.3
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-lib:/opt/emqx/lib
    ports:
      - 1883:1883
      - 8083:8083
      - 18083:18083
    environment:
      - EMQX_NAME=emqx
      - EMQX_ALLOW_ANONYMOUS=false
      - EMQX_LOADED_PLUGINS=emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_http
      - EMQX_AUTH__HTTP__AUTH_REQ=http://${API_GATEWAY}/Callback/Emq/Auth
      - EMQX_AUTH__HTTP__AUTH_REQ__PARAMS=clientid=%c,password=%P
      - EMQX_AUTH__HTTP__AUTH_REQ__METHOD=post
      - EMQX_AUTH__HTTP__SUPER_REQ=http://${API_GATEWAY}/Callback/Emq/SuperUser
      - EMQX_AUTH__HTTP__SUPER_REQ__PARAMS=clientid=%c
      - EMQX_AUTH__HTTP__SUPER_REQ__METHOD=get
      - EMQX_AUTH__HTTP__ACL_REQ=http://${API_GATEWAY}/Callback/Emq/Acl
      - EMQX_AUTH__HTTP__ACL_REQ__PARAMS=access=%A,clientid=%c,topic=%t
      - EMQX_AUTH__HTTP__ACL_REQ__METHOD=get      - 'EMQX_WEB__HOOK__API__URL=http://${API_GATEWAY}/Callback/Emq/WebHook'
      - 'EMQX_WEB__HOOK__RULE__CLIENT__CONNECTED__1={"action": "client_connect"}'
      - 'EMQX_WEB__HOOK__RULE__CLIENT__DISCONNECTED__1={"action": "client_disconnect"}'
      - 'EMQX_WEB__HOOK__RULE__CLIENT__SUBSCRIBE__1='
      - 'EMQX_WEB__HOOK__RULE__CLIENT__UNSUBSCRIBE__1='
      - 'EMQX_WEB__HOOK__RULE__SESSION_CREATED_1='
      - 'EMQX_WEB__HOOK__RULE__SESSION_TERMINATED_1='
      - 'EMQX_WEB__HOOK__RULE__SESSION_SUBSCRIBED_1='
      - 'EMQX_WEB__HOOK__RULE__SESSION_UNSUBSCRIBED_1='
      - 'EMQX_WEB__HOOK__RULE__MESSAGE_PUBLISH_1='
      - 'EMQX_WEB__HOOK__RULE__MESSAGE_DELIVER_1='
      - 'EMQX_WEB__HOOK__RULE__MESSAGE_ACKED_1='
    depends_on:
      - redis
    restart: unless-stopped

```
