### ISSUE TITLE
K8s-dns found cluster mode invalid

### ISSUE THREAD

**Issue by xiyangxdy** [emqx/emqx#2575]
#### Environment

- OS: linux
- Erlang/OTP: 
- EMQ: 2.3.11

#### Description
     

  I want to use k8s-dns to discover the cluster pattern, but it can't be formed with the following configuration. After entering the pod, the node name is named after the ip of the pod. And after looking at the /etc/hosts file, I think the node name should be node.name = emqtt@emqtt-6bsrt. So I tried to add EMQX_NODE_NAME in yaml, but the pod name is dynamically generated, I have not configured successfully. Have you had a similar experience?

**yaml**
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: emqtt
  labels:
    name: emqtt
spec:
  replicas: 3
  selector:
    name: emqtt
  template:
    metadata:
      labels:
        name: emqtt
    spec:
      containers:
      - name: emqtt
        image: emqtt:v2.3
        ports:
        - containerPort: 80
        env:
          - name: EMQ_NODE__DIST_NET_TICKTIME
            value: "300"
          - name: EMQ_NAME
            value: "emqtt"
          - name: EMQ_CLUSTER__DISCOVERY
            value: "k8s"
          - name: EMQ_CLUSTER__K8S__APISERVER
            value: "http:\\/\\/***:8080"
          - name: EMQ_CLUSTER__K8S__SERVICE_NAME
            value: "emqtt"
          - name: EMQ_CLUSTER__K8S__ADDRESS_TYPE
            value: "dns"
          - name: EMQ_CLUSTER__K8S__APP_NAME
            value: "emqtt"
          - name: EMQ_CLUSTER__NAME
            value: "emqttcl"
          - name: EMQ_CLUSTER__AUTOHEAL
            value: "on"
          - name: EMQ_CLUSTER__AUTOCLEAN
            value: "5m"
          - name: EMQ_NODE__COOKIE
            value: "secretcookieeeetfggggg"
          #- name: EMQ_NODE_NAME
          #  value: emq@${POD_NAME}
        volumeMounts:
          - name: syslog
            mountPath: /workspace/logs
          - name: systime
            readOnly: true
            mountPath: /etc/localtime
      volumes:
        - name: syslog
          hostPath: {path: /home/azureuser/logs}
        - name: systime
          hostPath: {path: /etc/localtime}

```

**pod name——emqtt-6bsrt** 

**pod /etc/hosts**
```
# Kubernetes-managed hosts file.
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
fe00::0 ip6-mcastprefix
fe00::1 ip6-allnodes
fe00::2 ip6-allrouters
172.34.26.102   emqtt-6bsrt
172.34.26.102        172.34.26.102
```

**emq.conf**
`## Node name
node.name = emqtt@172.34.26.102 `

*A description of the issue*
