### ISSUE TITLE
client fail to connect on kubernetes based cluster

### ISSUE THREAD

**Issue by neo-feng** [emqx/emqx#2856]
#### Environment

- OS:  centos 7.3 - hosted in kubernetes
- Erlang/OTP: 
- EMQ: v3.2.2 - docker image

#### Description

*A description of the issue*
I set up emq cluster inside kubernetes, using template below,
```
apiVersion: v1
kind: Service
metadata:
  name: emqx
spec:
  ports:
  - port: 1883
    targetPort: emqx-tcp
    protocol: TCP    
    name: tcpport  
  - port: 8083
    targetPort: emqx-ws
    protocol: TCP    
    name: tcpport    
  - port: 32333
    # nodePort: 32333
    targetPort: emqx-dashboard
    protocol: TCP
    name: dashboardport
  selector:
    app: emqx
  # type: NodePort
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: emqx
  labels:
    app: emqx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
      - name: emqx
        image: emqx/emqx:v3.2.2
        ports:
        - name: emqx-dashboard
          containerPort: 18083
        - name: emqx-tcp
          containerPort: 1883
        - name: emqx-ws
          containerPort: 8083                    
        env:
        - name: EMQX_CLUSTER__DISCOVERY
          value: k8s
        - name: EMQX_NAME
          value: emqx
        - name: EMQX_CLUSTER__K8S__APISERVER
          value: {{apiserver}}
        - name: EMQX_CLUSTER__K8S__NAMESPACE
          value: emq
        - name: EMQX_CLUSTER__K8S__SERVICE_NAME
          value: emqx
        - name: EMQX_CLUSTER__K8S__ADDRESS_TYPE
          value: ip
        - name: EMQX_CLUSTER__K8S__APP_NAME
          value: emqx
        - name: EMQX_SERVICE_PORT
          value: "1883"  
        - name: EMQX_LISTENER__TCP__EXTERNAL
          value: "1883"
        tty: true
```

Cluster started successfully, and when type kubectl exec -it emqx-8655f58bbc-8p76x /opt/emqx/bin/emqx_ctl cluster status -n emq, got output below, which seems good,
```
Cluster status: [{running_nodes,['emqx@174.20.2.253','emqx@174.20.1.131']}]
```
Dashboard is also working fine and I can access it via browser, and can see 2 nodes running on the dashboard overview page.
However, my Paho mqtt client can never connect to the cluster, reporting cannot connect to server. No logs found from either emq pod nor ingress pod.
I was trying to connect to tcp://mqtt1.iquality.cn. 
Route path: dns -- load balance -- ingress based on host -- k8s service emqx:1883
The mqtt service ingress content:
```
Name:             emq-iquality-cn-emqx-tcp
Namespace:        emq
Address:
Default backend:  default-http-backend:80 (<none>)
Rules:
  Host               Path  Backends
  ----               ----  --------
  mqtt1.xxx.cn
                        emqx:1883 (<none>)
Annotations:
  kubernetes.io/ingress.class:                       traefik
  ingress.kubernetes.io/protocol:                    http
  kubectl.kubernetes.io/last-applied-configuration:  {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"ingress.kubernetes.io/protocol":"http","kubernetes.io/ingress.class":"traefik"},"name":"emq-iquality-cn-emqx-tcp","namespace":"emq"},"spec":{"rules":[{"host":"mqtt1.iquality.cn","http":{"paths":[{"backend":{"serviceName":"emqx","servicePort":1883}}]}}]}}

Events:  <none>
```

I have being struggling on this whole day, can hardly find anything useful from internet, strange thing is that all the articles on this from internet never expose tcp port (1883). Any suggestion will be appreciated.
