### ISSUE TITLE
how to use acl.conf,plugin username and http at the same time？

### ISSUE THREAD

**Issue by Rebellioncry** [emqx/emqx#2981]
#### Environment
docker:19+
EMQ: 3.2.3

#### Description

I want to use pluign emqx_auth_username with acl.conf so that I can set a default user，but I want to use emqx_auth_http as fallback at the same time。After my test,emqx_auth_http and  emqx_auth_username can run at the same time,ACL will be take over by emqx_auth_http then acl.conf won't work。What should I do?How to set a default user in an easy way?

**Comment by Rebellioncry** [comment]
I found a similar question: [https://github.com/emqx/emqx/issues/1363](url)，this problem does not seem to be resolved

**Comment by terry-xiaoyu** [comment]
First, the auth/acl plugins are performed at the order they are started. So you can control the order of `acl-chain` by changing the starting order in the file `data/loaded_plugins`. Note that the acl.conf is always at the tail of the `acl-chain`.

To make the `acl-chain` skip an acl result got from the http acl server, you could let the http server return a message with status code 200 and with string body "ignore":

```erlang
case check_acl_request(AclReq, ClientInfo1, HttpOpts, RetryOpts) of
        {ok, 200, "ignore"} -> ok;
        {ok, 200, _Body}    -> {stop, allow};
        {ok, _Code, _Body}  -> {stop, deny};
        {error, Error}      ->
            ?LOG(error, "[ACL http] do_check_acl url ~s Error: ~p",
                 [AclReq#http_request.url, Error]),
            ok
    end.
```

In the above 4 case-clauses:
- `ok` is to skip the acl result and continue the `acl-chain`;
- `{stop, allow}` is to stop the chain and allow the pub/sub;
- `{stop, deny}` is to stop the chain and deny the pub/sub.

**Comment by alexandrim0** [comment]
Hello!

Is it possible to choose order of loading acl.conf to place it on the top?
I would be better for perfomance reason to use static ACL before request to HTTP server for ACL.
Is it?

**Comment by Rebellioncry** [comment]
hello @terry-xiaoyu ,Sorry to reply to you so late.I know what you mean,but if when I stop http server,then acl.conf will not work，So I just want  set a internal default user ,just like rabbitmq's http auth setting.
my setting as follow:
emqx-stack.yml:
 ```
 emqx:
    image: emqx/emqx:latest
    volumes:  
      - ./conf/emqx_auth_http.conf:/opt/emqx/etc/plugins/emqx_auth_http.conf
      - ./conf/acl.conf:/etc/acl.conf
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      # resources:
        # limits:
          # cpus: "0.2"
          # memory: 1024M
      # update_config:
        # parallelism: 1 # 每次更新1个副本
        # delay: 5s # 每次更新间隔 
        # monitor: 10s # 单次更新多长时间后没有结束则判定更新失败
        # max_failure_ratio: 0.1 # 更新时能容忍的最大失败率
        # order: start-first # 更新顺序为新任务启动优先
    ports:
      - 1883:1883
      - 18083:18083
      - 8083:8083
      - 8080:8080
      - 8084:8084
      - 8883:8883
    environment:
      - TZ=Asia/Shanghai
      - EMQX_MQTT__MAX_PACKET_SIZE=100MB
      - EMQX_ALLOW_ANONYMOUS=false
      - EMQX_ACL_NOMATCH=deny
      - EMQX_LOADED_PLUGINS="emqx_management,emqx_auth_http,emqx_recon,emqx_retainer,emqx_dashboard"
    networks:
      - emqx-net
```

acl.conf:
`{allow, {user, "admin"}, pubsub, ["$SYS/#", "#"]}.`
