### ISSUE TITLE
Better documentation for EMQX Docker usage

### ISSUE THREAD

**Issue by zhongjiewu** [emqx/emqx#3427]
**What would you like to be added/modified**:

The following should be available in the documentation:

When using EMQ X broker between docker containers, the following folders should be persisted:

- `/opt/emqx/data`
- `/opt/emqx/etc`, 
- `/opt/emqx/log`

Since data in these folders are partially stored under the "node_name", the user also needs to reuse the same node name to see the previous state. In detail, one needs to specify the two environment variables: `EMQX_NAME` and `EMQX_HOST`. I discovered `EMQX_HOST` set as 127.0.0.1 would be useful.

In if you use `docker-compose`, the configuration would look something like this:

```
volumes:
  vol-emqx-root:
    name: foo-emqx-root
  vol-emqx-data:
    name: foo-emqx-data
  vol-emqx-etc:
    name: foo-emqx-etc
  vol-emqx-log:
    name: foo-emqx-log
services:
  emqx:
    user: root
    container_name: foo_emqx
    hostname: foo_emqx
    image: emqx/emqx:v4.1-beta.1
    restart: always
    environment:
      EMQX_NAME: foo_emqx
      EMQX_HOST: 127.0.0.1
    ports:
      - 1883:1883
      - 8083:8083
      - 18083:18083
    volumes:
      - vol-emqx-root:/root
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log
```

**Why is this needed**:

When I use the docker images in the docker-compose, every time something changed, a new container will be created and as a result, all settings I changed in the dashboard are gone. Although I tried persisting the three folders using volumes, `/opt/emqx/data`, `/opt/emqx/etc`, 
`/opt/emqx/log`, the problem is still there. After looking into the start script, I realized that the node hostname + IP is important. If that changes, the previously saved state will not be picked up.
