### ISSUE TITLE
EMQX unable to recover and closes abruptly

### ISSUE THREAD

**Issue by daadu** [emqx/emqx#3568]
I am getting following crash error:

```
acl_nomatch=deny                                                                                                                                                                  │
│ EMQX_LOADED_PLUGINS=emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_pgsql,emqx_rule_engine,emqx_statsd                                                          │
│ EMQ X Broker v4.1.0 is started successfully!                                                                                                                                      │
│ =====                                                                                                                                                                             │
│ ===== LOGGING STARTED Sat Jul  4 05:37:10 UTC 2020                                                                                                                                │
│ =====                                                                                                                                                                             │
│ Exec: /opt/emqx/erts-10.7.1/bin/erlexec -boot /opt/emqx/releases/v4.1.0/emqx -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-10.7.1/../lib -mnesia dir "/opt/emqx/data/mnesi │
│ Root: /opt/emqx                                                                                                                                                                   │
│ /opt/emqx                                                                                                                                                                         │
│ Starting emqx on node mqtt@mqtt-emqx-0.mqtt-emqx-headless.nh-production.svc.cluster.local                                                                                         │
│ ['2020-07-04T05:37:27Z']:emqx start                                                                                                                                               │
│ ['2020-07-04T05:37:27Z']:emqx not running, waiting for recovery in 20 seconds                                                                                                     │
│ ['2020-07-04T05:37:32Z']:emqx not running, waiting for recovery in 15 seconds                                                                                                     │
│ ['2020-07-04T05:37:37Z']:emqx not running, waiting for recovery in 10 seconds                                                                                                     │
│ ['2020-07-04T05:37:42Z']:emqx not running, waiting for recovery in 5 seconds                                                                                                      │
│ ['2020-07-04T05:37:47Z']:emqx not running, waiting for recovery in 0 seconds                                                                                                      │
│ =====                                                                                                                                                                             │
│ ===== LOGGING STARTED Sat Jul  4 05:37:10 UTC 2020                                                                                                                                │
│ =====                                                                                                                                                                             │
│ Exec: /opt/emqx/erts-10.7.1/bin/erlexec -boot /opt/emqx/releases/v4.1.0/emqx -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-10.7.1/../lib -mnesia dir "/opt/emqx/data/mnesi │
│ Root: /opt/emqx                                                                                                                                                                   │
│ /opt/emqx                                                                                                                                                                         │
│ Starting emqx on node mqtt@mqtt-emqx-0.mqtt-emqx-headless.nh-production.svc.cluster.local                                                                                         │
│ ['2020-07-04T05:37:52Z']:emqx exit abnormally                                                                                                                                     │
│ stream closed    
```

Can someone explain me what is the issue?

**Comment by zhanghongtong** [comment]
Hi, @daadu 
This looks like a k8s cluster, are you deploying with our helm packages?

**Comment by daadu** [comment]
Yes v4.1.0

**Comment by daadu** [comment]
This happened multiple times.

**Comment by zhanghongtong** [comment]
Can you share the configuration when you deploy?

**Comment by daadu** [comment]
I am using helmfile to depoy it, following is the values.yaml.gotmpl i use

```yaml
# default values: https://github.com/emqx/emqx-rel/blob/master/deploy/charts/emqx/values.yaml

## It is recommended to have odd number of nodes in a cluster, otherwise the emqx cluster cannot be automatically healed in case of net-split.
replicaCount: {{ .Values.emqx | getOrNil "replicaCount" | default 1 }}
image:
  repository: emqx/emqx
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce

# TODO figure out right resource limit for emqx
#resources:
#  limits:
#    cpu: 500m
#    memory: 512Mi
#  requests:
#    cpu: 500m
#    memory: 512Mi

## EMQX configuration item, see the documentation (https://github.com/emqx/emqx-docker#emq-x-configuration)
emqxConfig:
  ## k8s related
  EMQX_CLUSTER__K8S__APISERVER: "https://kubernetes.default.svc:443"
  EMQX_CLUSTER__K8S__ADDRESS_TYPE: "hostname"
  EMQX_CLUSTER__K8S__SUFFIX: "svc.cluster.local"
  ## emqx.conf
  EMQX_ALLOW_ANONYMOUS: "false"
  EMQX_ACL_NOMATCH: "deny"
  EMQX_ACL_DENY_ACTION: "disconnect"
  # emqx_auth_pgsql
  EMQX_AUTH__PGSQL__SERVER: {{ .Values.postgres.host }}:{{ .Values.postgres.port }}
  EMQX_AUTH__PGSQL__USERNAME: {{ .Values.postgres.user }}
  {{ if hasKey .Values.postgres "password" }}
  EMQX_AUTH__PGSQL__PASSWORD: {{ .Values.postgres.password }}
  {{ end }}
  EMQX_AUTH__PGSQL__DATABASE: {{ .Values.postgres.database }}
  EMQX_AUTH__PGSQL__SSL: "true"
  EMQX_AUTH__PGSQL__POOL: {{ if eq .Environment.Name "production" }} 4 {{ else }} 2 {{ end }}
  EMQX_AUTH__PGSQL__AUTH_QUERY: SELECT password, substring(password, 0, 30) as salt FROM mqtt_mqttuser WHERE username = '%u' LIMIT 1
  EMQX_AUTH__PGSQL__PASSWORD_HASH: salt,bcrypt
  EMQX_AUTH__PGSQL__SUPER_QUERY: SELECT is_superuser FROM mqtt_mqttuser WHERE username = '%u'  LIMIT 1
  EMQX_AUTH__PGSQL__ACL_QUERY: SELECT 1 as allow, NULL as ipaddr, \"mqtt_mqttuser\".\"username\", NULL as clientid, \"mqtt_mqttacl\".\"rw\" as access, \"mqtt_mqttacl\".\"topic\"  FROM \"mqtt_mqttacl\" INNER JOIN \"mqtt_mqttuser\" ON (\"mqtt_mqttacl\".\"user_id\" = \"mqtt_mqttuser\".\"id\") WHERE \"mqtt_mqttuser\".\"username\" = '%u'
  # emqx_web_hook
  EMQX_WEB__HOOK__API__URL: http://mqtt-webhook:{{ .Values.mqtt.webhook.password }}@nexthome/mqtt/webhook/
  # emqx_statsd
  EMQX_STATSD__PUSH__GATEWAY__SERVER: "http://prometheus-pushgateway.monitoring.svc:9091"
  ## other
  EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_pgsql,emqx_web_hook,emqx_statsd"

##  [ACL](https://docs.emqx.io/broker/latest/en/advanced/acl-file.html)
emqxAclConfig: >
  {allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.
  {allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.
  {deny, all}.

```

My guess is that it is crashing due to WebHook resource not being active

**Comment by daadu** [comment]
I am using helmfile to depoy it, following is the values.yaml.gotmpl i use

```yaml
# default values: https://github.com/emqx/emqx-rel/blob/master/deploy/charts/emqx/values.yaml

## It is recommended to have odd number of nodes in a cluster, otherwise the emqx cluster cannot be automatically healed in case of net-split.
replicaCount: {{ .Values.emqx | getOrNil "replicaCount" | default 1 }}
image:
  repository: emqx/emqx
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce

# TODO figure out right resource limit for emqx
#resources:
#  limits:
#    cpu: 500m
#    memory: 512Mi
#  requests:
#    cpu: 500m
#    memory: 512Mi

## EMQX configuration item, see the documentation (https://github.com/emqx/emqx-docker#emq-x-configuration)
emqxConfig:
  ## k8s related
  EMQX_CLUSTER__K8S__APISERVER: "https://kubernetes.default.svc:443"
  EMQX_CLUSTER__K8S__ADDRESS_TYPE: "hostname"
  EMQX_CLUSTER__K8S__SUFFIX: "svc.cluster.local"
  ## emqx.conf
  EMQX_ALLOW_ANONYMOUS: "false"
  EMQX_ACL_NOMATCH: "deny"
  EMQX_ACL_DENY_ACTION: "disconnect"
  # emqx_auth_pgsql
  EMQX_AUTH__PGSQL__SERVER: {{ .Values.postgres.host }}:{{ .Values.postgres.port }}
  EMQX_AUTH__PGSQL__USERNAME: {{ .Values.postgres.user }}
  {{ if hasKey .Values.postgres "password" }}
  EMQX_AUTH__PGSQL__PASSWORD: {{ .Values.postgres.password }}
  {{ end }}
  EMQX_AUTH__PGSQL__DATABASE: {{ .Values.postgres.database }}
  EMQX_AUTH__PGSQL__SSL: "true"
  EMQX_AUTH__PGSQL__POOL: {{ if eq .Environment.Name "production" }} 4 {{ else }} 2 {{ end }}
  EMQX_AUTH__PGSQL__AUTH_QUERY: SELECT password, substring(password, 0, 30) as salt FROM mqtt_mqttuser WHERE username = '%u' LIMIT 1
  EMQX_AUTH__PGSQL__PASSWORD_HASH: salt,bcrypt
  EMQX_AUTH__PGSQL__SUPER_QUERY: SELECT is_superuser FROM mqtt_mqttuser WHERE username = '%u'  LIMIT 1
  EMQX_AUTH__PGSQL__ACL_QUERY: SELECT 1 as allow, NULL as ipaddr, \"mqtt_mqttuser\".\"username\", NULL as clientid, \"mqtt_mqttacl\".\"rw\" as access, \"mqtt_mqttacl\".\"topic\"  FROM \"mqtt_mqttacl\" INNER JOIN \"mqtt_mqttuser\" ON (\"mqtt_mqttacl\".\"user_id\" = \"mqtt_mqttuser\".\"id\") WHERE \"mqtt_mqttuser\".\"username\" = '%u'
  # emqx_statsd
  EMQX_STATSD__PUSH__GATEWAY__SERVER: "http://prometheus-pushgateway.monitoring.svc:9091"
  ## other
  EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_pgsql,emqx_web_hook,emqx_statsd"

##  [ACL](https://docs.emqx.io/broker/latest/en/advanced/acl-file.html)
emqxAclConfig: >
  {allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.
  {allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.
  {deny, all}.

```

My guess is that it is crashing due to WebHook resource not being active
