### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by am3n** [emqx/emqx#3701]
please add timezone option in configurations

**Comment by tigercl** [comment]
@am3n Where do you want it to be used?

**Comment by am3n** [comment]
use in dashboard and logs

my docker compose:
```yaml
version: '3.7'
services:
  emqx:
    ...
    environment:
      - TZ=Asia/Tehran
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Tehran
      - EMQX_NAME=emqx

    ports:
       ...
```

and my start bash script:
```
#!/bin/bash

###################################################
#                      Run                        #
###################################################

docker-compose up -d
docker image prune -f
docker volume prune -f

###################################################
#                   Set timezone                  #
###################################################

sudo docker exec -it emqx sh -c "sudo apk add -U tzdata"
sudo docker exec -it emqx sh -c "sudo cp /usr/share/zoneinfo/Asia/Tehran /etc/localtime"
sudo docker exec -it emqx sh -c "sudo ln -snf /usr/share/zoneinfo/Asia/Tehran /etc/localtime && sudo dpkg-reconfigure -f noninteractive tzdata"
sudo docker exec -it emqx sh -c "sudo ln -snf /usr/share/zoneinfo/Asia/Tehran /etc/localtime && sudo echo Asia/Tehran > /etc/timezone"
```

it's now working with my timezone
tnx :)
