### ISSUE TITLE
how to do data persistence in docker about emqx_auth_clientid plugin

### ISSUE THREAD

**Issue by simplezhao** [emqx/emqx#3709]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
I  use the official emqx docker image, and I have done the volumes, below is my config
```yml
emqx:
        image: emqx/emqx:latest
        container_name: emqx
        restart: always
        volumes: 
             - /contiocean/emqx/etc:/opt/emqx/etc
             - /contiocean/emqx/log:/opt/emqx/log 
             - /contiocean/emqx/data:/opt/emqx/data
        user: root
        ports: 
            - 1883:1883
            - 8083:8083
            - 8084:8084
            - 8080:8080
            - 18083:18083
```
and then I add some users (client_id with password)
![image](https://user-images.githubusercontent.com/24296783/92194119-801e4e00-ee9c-11ea-9ba4-7b60ac47356c.png)
but when I rebuild the docker, the data lost 
my question is how to do the data persistence about emqx_auth_clientid plugin?
