### ISSUE TITLE
WSS and MQTTS TLS doesn't work in docker with LetsEncrypt

### ISSUE THREAD

**Issue by gbaranski** [emqx/emqx#3761]
**Environment**:

- EMQ X version: 4.2.1
- Hardware configuration: Docker on x86_64 host
- OS: Arch Linux
- Kernel: 5.8.13-arch1-1 

**What happened and what you expected to happen**:
TLS doesn't want to work while using WSS and MQTTS, it only works when using it via MQTTX, but doesn't work in Node.JS and this command
`openssl s_client -connect $DOMAIN:8883`
gives me errors
```
depth=0 CN = $DOMAIN
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = $DOMAIN
verify error:num=21:unable to verify the first certificate
verify return:1
```

in Node.JS i get error like that
```
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1506:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at TLSSocket._finishInit (_tls_wrap.js:948:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
```

**How to reproduce it (as minimally and precisely as possible)**:
Get a LetsEncrypt fullchain certificate, and private key, add service config to docker-compose.yml, and try to use
`openssl s_client -connect $DOMAIN:8883`

**Anything else we need to know?**:
My docker-compose emqx service
```yml
  emqx:
    image: 'emqx/emqx'
    container_name: 'emqx'
    env_file:
      - .env
    environment:
      - EMQX_NAME=emqx
      - EMQX_LOG__LEVEL=debug
      - EMQX_ALLOW_ANONYMOUS=false
      - EMQX_LISTENER__SSL__EXTERNAL__KEYFILE=etc/certs/emqx.key
      - EMQX_LISTENER__SSL__EXTERNAL__CERTFILE=etc/certs/emqx.crt

      - EMQX_LISTENER__WSS__EXTERNAL__KEYFILE=etc/certs/emqx.key
      - EMQX_LISTENER__WSS__EXTERNAL__CERTFILE=etc/certs/emqx.crt

      - EMQX_LOADED_PLUGINS=emqx_auth_http,emqx_web_hook,emqx_management,emqx_recon,emqx_retainer,emqx_dashboard
    ports:
      - 1883:1883 # MQTT
      - 8883:8883 # MQTT/SSL
      - 8083:8083 # MQTT/WS
      - 8084:8084 # MQTT/WSS
      - 18083:18083 # Dashboard
    volumes:
      - ./emqx/plugins:/opt/emqx/etc/plugins

      - /etc/letsencrypt/live/$DOMAIN/privkey.pem:/opt/emqx/etc/certs/emqx.key
      - /etc/letsencrypt/live/$DOMAIN/fullchain.pem:/opt/emqx/etc/certs/emqx.crt
    networks:
      - backend
```
