### ISSUE TITLE
Load plugin emqx_auth_redis error - exception exit: {connection_error,econnrefused}

### ISSUE THREAD

**Issue by maraspin** [emqx/emqx#3839]
**Environment**:

- EMQ X version:  4.0.1 (same results with 4.0.2 and 4.0.7)
- Hardware configuration: Digital Ocean Droplet - Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, 2Gb RAM
- OS: Ubuntu 18.04 LTS
- Kernel: Linux 4.15.0-121-generic #123-Ubuntu SMP
- Erlang/OTP version: 1:20.2.2+dfsg-1ubuntu2
- Others: existing 3 node cluster running steadily for months now. Same OS, same software version, same Redis Auth back-end, same configuration.

**What happened and what you expected to happen**:

I have a 3 host cluster running with same setup (they were all prepared through Ansible). I've made emqx installation on another host and tried adding it to the cluster. Calling `/usr/bin/emqx_ctl cluster join emqx@PRIMARY_NODE` went just fine. As I have tried to enable Redis Authentication through `/usr/bin/emqx_ctl plugins load emqx_auth_redis` I've stepped into an issue. Output has been as follows:

> Load plugin emqx_auth_redis error: {emqx_auth_redis,
>                                     {bad_return,
>                                      {{emqx_auth_redis_app,start,[normal,[]]},
>                                       {'EXIT',
>                                        {{badmatch,
>                                          {error,
>                                           {shutdown,
>                                            {failed_to_start_child,
>                                             emqx_auth_redis,
>                                             {shutdown,
>                                              {failed_to_start_child,
>                                               worker_sup,
>                                               {shutdown,
>                                                {failed_to_start_child,
>                                                 {worker,1},
>                                                 {connection_error,
>                                                  econnrefused}}}}}}}}},
>                                         [{emqx_auth_redis_app,start,2,
>                                           [{file,
>                                             "/emqx-rel/_build/emqx-pkg/lib/emqx_auth_redis/src/emqx_auth_redis_app.erl"},
>                                            {line,30}]},
>                                          {application_master,start_it_old,4,
>                                           [{file,"application_master.erl"},
>                                            {line,277}]}]}}}}}.

Also, I was tricked into thinking everything went on fine as Ansible reported no errors. I've later found out that `echo $?` after executing the above returns status 0. Trying to activate plugin either through CLI or Web UI ends up in the same error.

Nothing useful for me came out of strace. Unfortunately I'm not familiar with Erlang, so it's hard for me to proceed debugging this.

**How to reproduce it**:

I have used following ansible playbook to install emqx 4.0.1 (same as on all other hosts within the cluster; and later also tried the same with both 4.0.2 and 4.0.7 - always same results):

```
- name: Installing EMQX
  hosts: mqtt
  become: true
  tasks:

  - name: Installing Erlang
    apt: name="erlang" state=present update_cache=yes force_apt_get=yes
    register: task_result
    until: task_result is success
    retries: 3
    delay: 10

  - name: Importing EMQX APT Key
    apt_key:
      url: "https://repos.emqx.io/gpg.pub"
      state: present

  - name: Adding Ubuntu Bionic repo
    apt_repository:
      repo: deb [arch=amd64] https://repos.emqx.io/emqx-ce/deb/ubuntu bionic stable
      filename: "emqx"
      state: present
      update_cache: yes

  - name: Installing EMQX
    package:
      name: "emqx=4.0.1"
      state: present
      update_cache: true
      dpkg_options: force-downgrade
      force: yes

  - name: Ensure EMQX is stopped
    service:
      state: stopped
      name: emqx

  - name: Makes absolutely sure EMQX process is stopped
    shell: |
      /usr/bin/killall beam.smp
      /bin/sleep 15

  - name: copy certificates
    copy:
      src: files/etc/emqx/certs
      dest: /etc/emqx/
      owner: emqx
      group: emqx
      mode: '0655'

  - name: backup existing emqx configuration
    command: mv /etc/emqx/emqx.conf /etc/emqx/emqx.conf.bkp

  - name: copy EMQX configuration template
    copy:
      src: files/etc/emqx/emqx.base.conf
      dest: /etc/emqx/emqx.conf
      owner: emqx
      group: emqx
      mode: '0644'

  - name: copy EMXQ Redis Auth plugin configuration
    copy:
      src: files/etc/emqx/plugins/emqx_auth_redis.conf
      dest: /etc/emqx/plugins/emqx_auth_redis.conf
      owner: emqx
      group: emqx
      mode: '0644'

  - name: configure cluster instance hostname
    lineinfile:
      dest: "/etc/emqx/emqx.conf"
      regexp: "^node.name"
      line: "node.name = emqx@{{ inventory_hostname }}"

  - name: Starts EMQX
    service:
      state: started
      name: emqx

  - name: enable redis auth
    command: /usr/bin/emqx_ctl plugins load emqx_auth_redis
```

I've executed `/usr/bin/emqx_ctl cluster join emqx@PRIMARY_NODE` to join the cluster (it worked), and then tried to enable Redis Authentication through `/usr/bin/emqx_ctl plugins load emqx_auth_redis`. It failed with output message above.

**Anything else we need to know?**:

Same exact configuration files has been working for months now on other 3 hosts. Redis is running locally and responds to PING. emqx_auth_redis.conf content is as follows:

```
## Redis server address.
##
## Value: Port | IP:Port
##
## Redis Server: 6379, 127.0.0.1:6379, localhost:6379, Redis Sentinel: 127.0.0.1:26379
auth.redis.server = localhost:6379

## Redis sentinel cluster name.
##
## Value: String
## auth.redis.sentinel = mymaster

## Redis pool size.
##
## Value: Number
auth.redis.pool = 8

## Redis database no.
##
## Value: Number
auth.redis.database = 0

## Redis password.
##
## Value: String
## auth.redis.password =
auth.redis.password = !PASSWORD!

## Variables: %u = username, %c = clientid

## Authentication Query Command
auth.redis.auth_cmd = HMGET mqtt_user:%u password

## Password hash: plain, md5, sha, sha256, pbkdf2, bcrypt
auth.redis.password_hash = sha256

## sha256 with salt prefix
## auth.redis.password_hash = salt,sha256

## sha256 with salt suffix
## auth.redis.password_hash = sha256,salt

## bcrypt with salt prefix
## auth.redis.password_hash = salt,bcrypt

## pbkdf2 with macfun iterations dklen
## macfun: md4, md5, ripemd160, sha, sha224, sha256, sha384, sha512
## auth.redis.password_hash = pbkdf2,sha256,1000,20

## Superuser Query Command
auth.redis.super_cmd = HGET mqtt_user:%u is_superuser
```

How can I know more precisely what is going on? Error message isn't saying much. And neither do logs in /var/log/emqx, where content is pretty much the same:

```
2020-11-22 14:10:35.657 [error]   crasher:
    initial call: eredis_client:init/1
    pid: <0.3547.0>
    registered_name: []
    exception exit: {connection_error,econnrefused}
      in function  gen_server:init_it/6 (gen_server.erl, line 358)
    ancestors: [<0.3546.0>,<0.3545.0>,<0.3543.0>,emqx_auth_redis_sup,
                  <0.3541.0>]
    message_queue_len: 0
    messages: []
    links: [<0.3546.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 1096
  neighbours:

2020-11-22 14:10:35.657 [error]     supervisor: {<0.3545.0>,ecpool_worker_sup}
    errorContext: start_error
    reason: {connection_error,econnrefused}
    offender: [{pid,undefined},
               {id,{worker,1}},
               {mfargs,{ecpool_worker,start_link,
                                      [emqx_auth_redis,1,emqx_auth_redis_cli,
                                       [{type,single},
                                        {pool_size,8},
                                        {auto_reconnect,1},
                                        {database,0},
                                        {password,"u3l6iqc9x6s7j6hl"},
                                        {sentinel,[]},
                                        {host,"localhost"},
                                        {port,6379}]]}},
               {restart_type,transient},
               {shutdown,5000},
               {child_type,worker}]
```

 
Can somebody help me troubleshoot this? 
Thank you!
