### ISSUE TITLE
Broker readiness or liveness probe failures in k8s

### ISSUE THREAD

**Issue by mariusstaicu** [emqx/emqx#3916]
Hi,

we are using emqx v4.0.7 in production in kubernetes and we started to have readiness or liveness probe failures recently causing k8s to restart the broker pods. 
Health checks are done as following:
```
  readinessProbe:
      tcpSocket:
         port: 1883
      initialDelaySeconds: 60
      periodSeconds: 10
   livenessProbe:
      tcpSocket:
         port: 1883
      initialDelaySeconds: 60
      periodSeconds: 3
```

Also some considerations:
- pod memory is at about 20% from total memory allocated, but despite this, there are some high memory watermark alarms in history and I don't understand why since the pod has all the memory it can dream of
- we've recently started calling the broker API to evict clients, but there are only 10-20 such requests per minute

Logs are totally clean except when the broker is restarting, but the restart is triggered by k8s health check probe because it fails, but also all logging is by default set on warning.
Is there any way for us to diagnose what's causing broker stop responding on TCP 1883 ? We are also using emqx grafana dashboards, but there's nothing special there also.
