### ISSUE TITLE
cluster restart order issue

### ISSUE THREAD

**Issue by hehejiuhuizhe** [emqx/emqx#3923]
I used docker to run emqx cluster like example in : https://docs.emqx.cn/cn/broker/latest/getting-started/install.html#%E9%80%9A%E8%BF%87-docker-%E8%BF%90%E8%A1%8C-%E5%8C%85%E5%90%AB%E7%AE%80%E5%8D%95%E7%9A%84-docker-compose-%E9%9B%86%E7%BE%A4

this is my docker-compose.yaml:

```yaml
version: '3'

services:
  emqx1:
    image: emqx/emqx:v4.0.0
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node1.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io, emqx@node2.emqx.io, emqx@node3.emqx.io"
    ports:
      - 1883:1883
      - 18083:18083
      - 8081:8081
    networks:
      emqx-bridge:
        aliases:
        - node1.emqx.io
  
  emqx2:
    image: emqx/emqx:v4.0.0
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node2.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io, emqx@node2.emqx.io, emqx@node3.emqx.io"
    ports:
      - 1884:1883
    networks:
      emqx-bridge:
        aliases:
        - node2.emqx.io

  emqx3:
    image: emqx/emqx:v4.0.0
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node3.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io, emqx@node2.emqx.io, emqx@node3.emqx.io"
    ports:
      - 1885:1883
    networks:
      emqx-bridge:
        aliases:
        - node3.emqx.io

networks:
  emqx-bridge:
    driver: bridge

```

I created three service,emqx1, emqx2, emqx3. They started ok and the cluster status was ok.

Then I stop them.

Then I start emq3, but it can't start.The log shows:

** Cannot get connection id for node 'emqx@node3.emqx.io'
2020-12-16 05:08:37.923 [critical] [EMQ X] emqx shutdown for join
['2020-12-16T05:10:26Z']:waiting emqx
['2020-12-16T05:10:28Z']:waiting emqx
['2020-12-16T05:10:30Z']:waiting emqx
['2020-12-16T05:10:31Z']:waiting emqx
['2020-12-16T05:10:33Z']:waiting emqx
['2020-12-16T05:10:34Z']:waiting emqx
['2020-12-16T05:10:34Z']:timeout error

Then I start emqx2, again,it can't start.

Finally,I start emqx1, it's ok and after that, emqx2 and emqx3 can start.

So the problem is the start order. I must start emqx1 first or other nodes can't start.

**Comment by hehejiuhuizhe** [comment]
I change image version to 4.2.4. Now, I must start three service at the same time to make them run normally.

**Comment by zhanghongtong** [comment]
Hi,@hehejiuhuizhe
This is a distributed problem, and when three nodes stop and start at the same time, emqx cannot tell which node's data is up-to-date, so the startup fails.  
The solution to this problem is to start the last stopped node first, and then the other nodes can successfully join the cluster

**Comment by hehejiuhuizhe** [comment]
@zhanghongtong 
I guess so. But in production environment, sometimes it's hard to tell which node is the last stopped. And whatif the computer or the data center can't boot due to hardware(or other situations)? Then the whole system may down for a long period. I think it should be improved for quick recovery. If the system down, I hope I can start from any node.

**Comment by zhanghongtong** [comment]
@hehejiuhuizhe 
In fact, you can start any one node and then clear the directory of `data/mnesia/$node_name` for the other nodes, so that the cluster can be restored, but at the expense of losing some of the data

**Comment by hehejiuhuizhe** [comment]
@zhanghongtong 
Thanks for your reply。
I try to persist the data and now my docker-compose.yaml is like this:
```yaml
version: '3'

volumes:
  vol-emqx1-data:
  vol-emqx1-etc:
  vol-emqx1-log:
  vol-emqx2-data:
  vol-emqx2-etc:
  vol-emqx2-log:
  vol-emqx3-data:
  vol-emqx3-etc:
  vol-emqx3-log:

services:
  emqx1:
    image: emqx/emqx:4.2.4
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node1.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io, emqx@node2.emqx.io, emqx@node3.emqx.io"
    ports:
      - 1883:1883
      - 18083:18083
      - 8081:8081
    volumes:
      - vol-emqx1-data:/opt/emqx/data
      - vol-emqx1-etc:/opt/emqx/etc
      - vol-emqx1-log:/opt/emqx/log
    networks:
      emqx-bridge:
        aliases:
        - node1.emqx.io
  
  emqx2:
    image: emqx/emqx:4.2.4
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node2.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io, emqx@node2.emqx.io, emqx@node3.emqx.io"
    ports:
      - 1884:1883
    volumes:
      - vol-emqx2-data:/opt/emqx/data
      - vol-emqx2-etc:/opt/emqx/etc
      - vol-emqx2-log:/opt/emqx/log
    networks:
      emqx-bridge:
        aliases:
        - node2.emqx.io

  emqx3:
    image: emqx/emqx:4.2.4
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node3.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io, emqx@node2.emqx.io, emqx@node3.emqx.io"
    ports:
      - 1885:1883
    volumes:
      - vol-emqx3-data:/opt/emqx/data
      - vol-emqx3-etc:/opt/emqx/etc
      - vol-emqx3-log:/opt/emqx/log
    networks:
      emqx-bridge:
        aliases:
        - node3.emqx.io

networks:
  emqx-bridge:
    driver: bridge
```

I stop emqx1 first, then 3 , then 2.  
I start emqx2(which was the last stopped) by "docker start myemqx_emqx2_1", fail. Same fail for 1 and 3.
I try start emqx2 and emqx3 at the same time, fail. Emqx2 and emqx1,fail.
Finally I try start emqx1 and emqx3 at the same time, success.(Is it expected?)

And I've tried what you say. I delete all data in emqx2's data/mnesia/$node_name, and it start ok. But then I start emqx1 and 3, they all crash. After I also delete all data in emqx1 and emqx3's data/mnesia/$node_name, they can start normally.

If that's the right solution, I think it should be mentioned in document( I didn't find ). And it's still a little painful to recover from crash.
