### ISSUE TITLE
can't start emqx in docker

### ISSUE THREAD

**Issue by lonelyleaf** [emqx/emqx#3996]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`):  4.2.3
- Docker version 19.03.13 with emqx docker image

**What happened and what you expected to happen**:

can‘t start emqx docker container：
```
node.max_ports=1048576
emq_1        | listener.tcp.external.acceptors=64
emq_1        | auth.http.auth_req.method=post
emq_1        | auth.http.auth_req.content_type=x-www-form-urlencoded
emq_1        | auth.http.auth_req.params=clientid=%c,username=%u,password=%P,protocol=%r,clientPort=%p
emq_1        | auth.http.acl_req=http://backend:8080/mqtt/acl
emq_1        | allow_anonymous=true
emq_1        | listener.ssl.external.acceptors=32
emq_1        | node.process_limit=2097152
emq_1        | node.max_ets_tables=2097152
emq_1        | listener.ws.external.acceptors=16
emq_1        | auth.http.acl_req.method=post
emq_1        | auth.http.acl_req.content_type=x-www-form-urlencoded
emq_1        | auth.http.acl_req.params=access=%A,username=%u,clientid=%c,ipaddr=%a,topic=%t,mountpoint=%m
emq_1        | auth.http.auth_req=http://backend:8080/mqtt/auth
emq_1        | EMQX_LOADED_PLUGINS="emqx_management,emqx_recon,emqx_retainer,emqx_dashboard,emqx_telemetry,emqx_auth_http"
emq_1        | EMQ X Broker 4.2.3 failed to start within 15 seconds,
emq_1        | see the output of '/opt/emqx/bin/emqx console' for more information.
emq_1        | If you want to wait longer, set the environment variable
emq_1        | WAIT_FOR_ERLANG to the number of seconds to wait.
emq_1        | ['2021-01-10T11:38:56Z']:emqx exit abnormally

```

log of emqx.log
```
2021-01-10 11:27:30.339 [error] ** State machine gen_rpc_server_tcp terminating
** When server state  = {undefined,undefined}
** Reason for termination = exit:badarg
** Callback modules = [gen_rpc_server]
** Callback mode = undefined
** Stacktrace =
**  [{inet_tcp,listen,2,[{file,"inet_tcp.erl"},{line,160}]},
     {gen_rpc_server,init,1,[{file,"gen_rpc_server.erl"},{line,56}]},
     {gen_statem,init_it,6,[{file,"gen_statem.erl"},{line,718}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]

2021-01-10 11:27:30.340 [error]     supervisor: {local,gen_rpc_sup}
    errorContext: start_error
    reason: badarg
    offender: [{pid,undefined},
               {id,gen_rpc_server_tcp},
               {mfargs,{gen_rpc_server,start_link,[tcp]}},
               {restart_type,permanent},
               {shutdown,5000},
               {child_type,worker}]
2021-01-10 11:27:30.340 [error]   crasher:
    initial call: application_master:init/4
    pid: <0.1357.0>
    registered_name: []
    exception exit: {{shutdown,
                         {failed_to_start_child,gen_rpc_server_tcp,badarg}},
                     {gen_rpc_app,start,[normal,[]]}}
      in function  application_master:init/4 (application_master.erl, line 138)
    ancestors: [<0.1356.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.1358.0>,normal}]
    links: [<0.1356.0>,<0.1266.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 193
  neighbours:
```

log of erlang.log

```
Exec: /opt/emqx/erts-10.7.2.1/bin/erlexec -boot /opt/emqx/releases/4.2.3/emqx -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-10.7.2.1/../lib -mnesia dir "/opt/emqx/data/mnesia/d2e4d1254154@172.23.0.2" -config /opt/emqx/data/configs/app.2021.01.10.11.27.28.config -args_file /opt/emqx/data/configs/vm.2021.01.10.11.27.28.args -vm_args /opt/emqx/data/configs/vm.2021.01.10.11.27.28.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- console
Root: /opt/emqx
/opt/emqx
2021-01-10 11:27:30.339 [error] ** State machine gen_rpc_server_tcp terminating
** When server state  = {undefined,undefined}
** Reason for termination = exit:badarg
** Callback modules = [gen_rpc_server]
** Callback mode = undefined
** Stacktrace =
**  [{inet_tcp,listen,2,[{file,"inet_tcp.erl"},{line,160}]},
     {gen_rpc_server,init,1,[{file,"gen_rpc_server.erl"},{line,56}]},
     {gen_statem,init_it,6,[{file,"gen_statem.erl"},{line,718}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]

{"Kernel pid terminated",application_controller,"{application_start_failure,gen_rpc,{{shutdown,{failed_to_start_child,gen_rpc_server_tcp,badarg}},{gen_rpc_app,start,[normal,[]]}}}"}

Kernel pid terminated (application_controller) ({application_start_failure,gen_rpc,{{shutdown,{failed_to_start_child,gen_rpc_server_tcp,badarg}},{gen_rpc_app,start,[normal,[]]}}})



Crash dump is being written to: log/crash.dump...done
```

and the `crash.dump` file

[crash_dump.zip](https://github.com/emqx/emqx/files/5792529/crash_dump.zip)

**Comment by tigercl** [comment]
@lonelyleaf Sorry for not replying to you in time, this should be caused by a node name resolution error, it should be a BUG, before we solve this problem, you may need to set up another node name.

**Comment by zhanghongtong** [comment]
Hi, @lonelyleaf 
How did you start the docker container?

**Comment by lonelyleaf** [comment]
@zhanghongtong Before I restart the container，emqx keeps report some error and can't serve connection，so I run `docker-compose rm -sf emq` and `docker-compose up -d`,then I receive the error.

But now I can't receive these error any more...

my docker-compose file is like below:
```
version: '3'
services:
  emq:
    image: emqx/emqx:4.2.3
#    restart: always
    user: root
    environment:
      - EMQX_ALLOW_ANONYMOUS=true
      - EMQX_CLUSTER__DISCOVERY
      - TZ=Aisa/Shanghai
      - EMQX_LOADED_PLUGINS="emqx_management,emqx_recon,emqx_retainer,emqx_dashboard,emqx_telemetry,emqx_auth_http"
    env_file:
      - emq.env
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: 1
    ports:
      - 1883:1883
      - 8083:8083
      - 8883:8883
      - 8084:8084
      - 18083:18083
    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log
volumes:
  vol-emqx-data:
    name: emqx-data
  vol-emqx-etc:
    name: emqx-etc
  vol-emqx-log:
    name: emqx-log
```


```
EMQX_AUTH__HTTP__AUTH_REQ = http://host.docker.internal:8080/mqtt/auth
EMQX_AUTH__HTTP__AUTH_REQ__METHOD = post
EMQX_AUTH__HTTP__AUTH_REQ__CONTENT_TYPE = x-www-form-urlencoded
EMQX_AUTH__HTTP__AUTH_REQ__PARAMS=clientid=%c,username=%u,password=%P,protocol=%r,clientPort=%p
EMQX_AUTH__HTTP__ACL_REQ = http://host.docker.internal:8080/mqtt/acl
EMQX_AUTH__HTTP__ACL_REQ__METHOD = post
EMQX_AUTH__HTTP__ACL_REQ__CONTENT_TYPE = x-www-form-urlencoded
EMQX_AUTH__HTTP__ACL_REQ__PARAMS = access=%A,username=%u,clientid=%c,ipaddr=%a,topic=%t,mountpoint=%m
#EMQX_AUTH__HTTP__SUPER_REQ = http://172.28.240.1:8080/mqtt/su
#EMQX_AUTH__HTTP__SUPER_REQ__METHOD = post
#EMQX_AUTH__HTTP__SUPER_REQ__PARAMS = clientid=%c,username=%u
```
