### ISSUE TITLE
emqx:4.2.6 crashes (Docker)

### ISSUE THREAD

**Issue by andryyy** [emqx/emqx#4079]
**Environment**:

- v4.2.6
- Intel(R) Core(TM) i5-7260U (NUC i5)
- Debian GNU/Linux 10 (buster) x64
- Linux debian 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
- Docker 20.10.0

I start emqx like this (which works fine with 4.2.5):
```
version: "2.4"
services:

  emqx1:
    image: emqx/emqx:4.2.6
    restart: always
    ports:
      - 8083:8083
      - 1883:1883
      - 18083:18083
    environment:
      - TZ=Europe/Berlin
      - EMQX_LOADED_PLUGINS="emqx_management,emqx_auth_username,emqx_recon,emqx_retainer,emqx_dashboard"
      - EMQX_AUTH__USER__1__USERNAME=sensorsusr
      - EMQX_AUTH__USER__1__PASSWORD=sensorspw
      - EMQX_ALLOW_ANONYMOUS=false
      - EMQX_DASHBOARD__DEFAULT_USER__LOGIN=admin
      - EMQX_DASHBOARD__DEFAULT_USER__PASSWORD=blabla
      - EMQX_LISTENER__TCP__EXTERNAL=1883
      - EMQX_LISTENER__WS__EXTERNAL=8083
      - EMQX_LISTENER__WSS__EXTERNAL=8084
      - EMQX_LISTENER__API__MGMT=8080
    networks:
      iot-network:

networks:
  iot-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-iot
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/24
        - subnet: fd4d:2:2:2::/64
```

Docker logs output:
```
mqx1_1                          | =====
emqx1_1                          | ===== LOGGING STARTED Tue Jan 26 19:47:49 UTC 2021
emqx1_1                          | =====
emqx1_1                          | Exec: /opt/emqx/erts-10.7.2.6/bin/erlexec -boot /opt/emqx/releases/4.2.6/emqx -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-10.7.2.6/../lib -mnesia dir "/opt/emqx/data/mnesia/39fc55f2cd54@172.20.1.18" -config /opt/emqx/data/configs/app.2021.01.26.19.47.49.config -args_file /opt/emqx/data/configs/vm.2021.01.26.19.47.49.args -vm_args /opt/emqx/data/configs/vm.2021.01.26.19.47.49.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- console
emqx1_1                          | Root: /opt/emqx
emqx1_1                          | /opt/emqx
emqx1_1                          | {"init terminating in do_boot",{load_failed,[sys_core_fold_lists,core_pp,v3_kernel_pp,v3_kernel,v3_core,rec_env,sys_pre_attributes,sys_core_inline,sys_core_fold,sys_core_bsm,sys_core_alias,erl_bifs,core_scan,core_lib,core_lint,core_parse,compile,cerl_trees,cerl_sets,cerl_inline,cerl_clauses,cerl,beam_z,beam_validator,beam_utils,beam_trim,beam_ssa_type,beam_ssa_share,beam_ssa_recv,beam_ssa_pre_codegen,beam_ssa_pp,beam_ssa_opt,beam_ssa_lint,beam_ssa_funs,beam_ssa_dead,beam_ssa_codegen,beam_ssa_bsm,beam_ssa,beam_peep,beam_opcodes,beam_listing,beam_kernel_to_ssa,beam_jump,beam_flatten,beam_except,beam_disasm,beam_dict,beam_clean,beam_block,beam_asm,beam_a]}}
emqx1_1                          | init terminating in do_boot ({load_failed,[sys_core_fold_lists,core_pp,v3_kernel_pp,v3_kernel,v3_core,rec_env,sys_pre_attributes,sys_core_inline,sys_core_fold,sys_core_bsm,sys_core_alias,erl_bifs,core
emqx1_1                          |
emqx1_1                          | Crash dump is being written to: log/crash.dump...done
emqx1_1                          | ['2021-01-26T19:48:17Z']:emqx exit abnormally
emqx1_1                          | allow_anonymous=false
emqx1_1                          | auth.user.1.password=***secret***
emqx1_1                          | auth.user.1.username=sensorsusr
emqx1_1                          | dashboard.default_user.login=admin
emqx1_1                          | dashboard.default_user.password=***secret***
emqx1_1                          | listener.ssl.external.acceptors=32
emqx1_1                          | listener.tcp.external=1883
emqx1_1                          | listener.tcp.external.acceptors=64
emqx1_1                          | listener.wss.external=8084
emqx1_1                          | listener.ws.external=8083
emqx1_1                          | listener.ws.external.acceptors=16
emqx1_1                          | node.max_ets_tables=2097152
emqx1_1                          | node.max_ports=1048576
emqx1_1                          | node.process_limit=2097152
emqx1_1                          | EMQX_LOADED_PLUGINS=emqx_management emqx_auth_username emqx_recon emqx_retainer emqx_dashboard
emqx1_1                          | EMQ X Broker 4.2.6 failed to start within 15 seconds,
emqx1_1                          | see the output of '/opt/emqx/bin/emqx console' for more information.
emqx1_1                          | If you want to wait longer, set the environment variable
emqx1_1                          | WAIT_FOR_ERLANG to the number of seconds to wait.
emqx1_1                          |
```

Crash dump: https://termbin.com/s2du
