### ISSUE TITLE
emqx_ctl behaviour changes (not responding to pings) somewhere between 3.2.2 and 3.2.7

### ISSUE THREAD

**Issue by ilarimikkonen** [emqx/emqx#4142]
we are running emqx in docker containers, pulling images from dockerhub. If we run 3.2.2 running it's all sunshine and rainbows:
 
```
[centos@ip-xxx-yyy-83-114 ~]$ docker-compose exec emqttd emqx_ctl broker
sysdescr  : EMQ X Broker
version   : 3.2.2
uptime    : 43 seconds
datetime  : 2021-02-03 17:02:57
[centos@ip-xxx-yyy-83-114 ~]$

```

if we run the same config with 3.2.7 we get this:
```
[centos@ip-xxx-yyy-83-114 ~]$ docker-compose exec emqttd emqx_ctl broker
Node 'emqx@xxx.yyy.83.114' not responding to pings.
[centos@ip-xxx-yyy-83-114 ~]$
```

Here is the docker-compose, and as you can see we try to cluster. There are 2 virtual machines running in AWS.

```
version: '3'
services:
  emqttd:
    image: emqx/emqx:v3.2.2
    #image: emqx/emqx:v3.2.7
    restart: always
    environment:
      EMQX_NODE__NAME: "emqx@xxx.yyy.83.140"
      EMQX_NODE__COOKIE: "thisthat"
      EMQX_CLUSTER__NAME: "thisdev"
      EMQX_CLUSTER__DISCOVERY: "static"
      EMQX_CLUSTER__STATIC__SEEDS: "emqx@xxx.yyy.83.114"
      EMQX_LOADED_PLUGINS: "emqx_management emqx_recon"

    ports:
      - "1883:1883"
      - "8083:8083"
      - "4369:4369"
      - "5369:5369"
      - "6369:6369"
    volumes:
      - ./config/blonk/etc/acl.conf:/opt/emqx/etc/acl.conf

    logging:
      driver: json-file
      options:
        max-size: "500k"
        max-file: "10"
    sysctls:
      net.core.somaxconn: 32768
      net.ipv4.ip_local_port_range: "1000 65535"

    ulimits:
      nofile:
        soft: 40000
        hard: 60000
```

If we forget the clustering, so we don't give any environmental arguments in the docker-compose.yml,  it works also with 3.2.7:

```
[centos@ip-xxx-yyy-83-114 ~]$ docker-compose exec emqttd emqx_ctl broker
sysdescr  : EMQ X Broker
version   : 3.2.7
uptime    : 3 seconds
datetime  : 2021-02-03 17:10:38
```
Something has changed in the way that nodes find eachother. Is this somehow related to this: https://github.com/emqx/emqx/issues/2153 ? How should we approach the naming of the nodes with 3.2.7?

The thing is that from 3.2.3 onwards the docker build system is sweet and we'd like to use that.
