### ISSUE TITLE
Emqx in docker rare crash

### ISSUE THREAD

**Issue by velimirj** [emqx/emqx#4630]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.2.10
- Hardware configuration (e.g. `lscpu`): /
- OS (e.g. `cat /etc/os-release`): /
- Kernel (e.g. `uname -a`): /
- Erlang/OTP version (in case you build emqx from source code): /
- Others: /

**What happened and what you expected to happen**: 
Every once in a while, when doing `docker-compose up -d` with the docker-compose file which includes two services using emqx image, one or both of them crash and keep crashing when automatically restarted because of docker-compose. This keeps happening until `docker-compose down` and `docker-compose up -d` is done.

emqx.log contents:
```2021-04-16 14:04:09.321 [error] ** State machine gen_rpc_server_tcp terminating
** When server state  = {undefined,undefined}
** Reason for termination = exit:badarg
** Callback modules = [gen_rpc_server]
** Callback mode = undefined
** Stacktrace =
**  [{inet_tcp,listen,2,[{file,"inet_tcp.erl"},{line,160}]},
     {gen_rpc_server,init,1,[{file,"gen_rpc_server.erl"},{line,56}]},
     {gen_statem,init_it,6,[{file,"gen_statem.erl"},{line,718}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]

2021-04-16 14:04:09.322 [error]     supervisor: {local,gen_rpc_sup}
    errorContext: start_error
    reason: badarg
    offender: [{pid,undefined},
               {id,gen_rpc_server_tcp},
               {mfargs,{gen_rpc_server,start_link,[tcp]}},
               {restart_type,permanent},
               {shutdown,5000},
               {child_type,worker}]
2021-04-16 14:04:09.322 [error]   crasher:
    initial call: application_master:init/4
    pid: <0.1379.0>
    registered_name: []
    exception exit: {{shutdown,
                         {failed_to_start_child,gen_rpc_server_tcp,badarg}},
                     {gen_rpc_app,start,[normal,[]]}}
      in function  application_master:init/4 (application_master.erl, line 138)
    ancestors: [<0.1378.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.1380.0>,normal}]
    links: [<0.1378.0>,<0.1288.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 193
  neighbours:
  ```

**How to reproduce it (as minimally and precisely as possible)**:
Here is Dockerfile and config files used to build custom emqx image: [emqx.zip](https://github.com/emqx/emqx/files/6334286/emqx.zip)

```
version: '3.5'
services:
    emqx1:
        image: emqx-test:latest
        restart: unless-stopped
        environment:
          - EMQX_LOADED_PLUGINS="emqx_retainer, emqx_management, emqx_dashboard, emqx_web_hook, emqx_auth_http"
    emqx2:
        image: emqx-test:latest
        restart: unless-stopped
        environment:
          - EMQX_LOADED_PLUGINS="emqx_retainer, emqx_management, emqx_dashboard, emqx_web_hook, emqx_auth_http"
          - EMQX_LISTENER__TCP__EXTERNAL=2883
          - EMQX_LISTENER__SSL__EXTERNAL=7883
          - EMQX_LISTENER__WS__EXTERNAL=7083
          - EMQX_LISTENER__WSS__EXTERNAL=7084
          - EMQX_ALLOW_ANONYMOUS=false
 ```

**Anything else we need to know?**:
/

**Comment by airclear** [comment]
同问

**Comment by Rory-Z** [comment]
Hi, @velimirj 
I noticed that the image you are using is `emqx-test:latest`. This is not the image we released. Can you tell us what this image does?

**Comment by velimirj** [comment]
Hi @Rory-Z, 
I attached emqx.zip file in the original post, in there you can find Dockerfile and configuration files that I am using. 
Thank you for helping!

**Comment by Rory-Z** [comment]
Hi, @velimirj Can you use `FROM emqx/emqx:4.2.10` in Dockerfile, and retry

**Comment by velimirj** [comment]
Hi @Rory-Z, I've used your official image directly in docker-compose, and I'm still getting the same error after doing docker-compose down and up a number of times.
```
version: '3.5'
services:
    emqx1:
        image: emqx/emqx:4.2.10
        restart: unless-stopped
        environment:
          - EMQX_LOADED_PLUGINS="emqx_retainer, emqx_management, emqx_dashboard, emqx_web_hook, emqx_auth_http"
    emqx2:
        image: emqx/emqx:4.2.10
        restart: unless-stopped
        environment:
          - EMQX_LOADED_PLUGINS="emqx_retainer, emqx_management, emqx_dashboard, emqx_web_hook, emqx_auth_http"
          - EMQX_LISTENER__TCP__EXTERNAL=2883
          - EMQX_LISTENER__SSL__EXTERNAL=7883
          - EMQX_LISTENER__WS__EXTERNAL=7083
          - EMQX_LISTENER__WSS__EXTERNAL=7084
          - EMQX_ALLOW_ANONYMOUS=false
   ```
