### ISSUE TITLE
Request failed with status code 500 when switch to plugins and modules page

### ISSUE THREAD

**Issue by GaoShin** [emqx/emqx#4652]
#### Environment

- OS: Ubuntu
- Erlang/OTP: Not use
- EMQ: latest version

#### Description

I deploy EMQX using docker-compose but it seems something wrong with EMQX web management.When I switch to plugins page or modules page,it says "Request failed with status code 500" and no modules or plugins show .The monitor page seems have the same problem.When error 500 happens, system name ,version,uptime and system time not show under the broker section
Then I find the errors output in docker log:

>emqx    | 2021-04-21 06:00:10.553 [error] GET /api/v4/nodes/all/modules error: function_clause, stacktrace:
>emqx    | [{emqx_modules_api,'-list/2-lc$^0/1-1-',
>emqx    |                    [{error,nodedown}],
>emqx    |                    [{file,"emqx_modules_api.erl"},{line,81}]},
>emqx    |  {emqx_modules_api,list,2,[{file,"emqx_modules_api.erl"},{line,81}]},
>emqx    |  {minirest_handler,dispatch,2,[{file,"minirest_handler.erl"},{line,84}]},
>emqx    |  {minirest,handle_request,2,[{file,"minirest.erl"},{line,116}]},
>emqx    |  {minirest,init,2,[{file,"minirest.erl"},{line,108}]},
>emqx    |  {cowboy_handler,execute,2,[{file,"cowboy_handler.erl"},{line,41}]},
>emqx    |  {cowboy_stream_h,execute,3,[{file,"cowboy_stream_h.erl"},{line,320}]},
>emqx    |  {cowboy_stream_h,request_process,3,[{file,"cowboy_stream_h.erl"},{line,302}]},
>emqx    |  {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]
>emqx    | 2021-04-21 06:04:38.618 [error] GET /api/v4/nodes/all/plugins error: function_clause, stacktrace:
>emqx    | [{emqx_mgmt_api_plugins,'-list/2-lc$^0/1-1-',
>emqx    |                         [{error,nodedown}],
>emqx    |                         [{file,"emqx_mgmt_api_plugins.erl"},{line,72}]},
>emqx    |  {emqx_mgmt_api_plugins,list,2,[{file,"emqx_mgmt_api_plugins.erl"},{line,72}]},
>emqx    |  {minirest_handler,dispatch,2,[{file,"minirest_handler.erl"},{line,84}]},
>emqx    |  {minirest,handle_request,2,[{file,"minirest.erl"},{line,116}]},
>emqx    |  {minirest,init,2,[{file,"minirest.erl"},{line,108}]},
>emqx    |  {cowboy_handler,execute,2,[{file,"cowboy_handler.erl"},{line,41}]},
>emqx    |  {cowboy_stream_h,execute,3,[{file,"cowboy_stream_h.erl"},{line,320}]},
>emqx    |  {cowboy_stream_h,request_process,3,[{file,"cowboy_stream_h.erl"},{line,302}]},
>emqx    |  {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]

Here is my docker-compose.yml

```yaml
emqx:
  image: emqx/emqx:latest
  container_name: emqx
  environment:
    - EMQX_NAME=emqx
    - EMQX_HOST=localgost
  volumes:
    - volume-emqx-lib:/opt/emqx/lib
    - volume-emqx-etc:/opt/emqx/etc
    - volume-emqx-data:/opt/emqx/data
    - volume-emqx-log:/opt/emqx/log
  ports:
    - 1883:1883
    - 8081:8081
    - 8083:8083
    - 8084:8084
    - 8883:8883
    - 18083:18083
```
