### ISSUE TITLE
Enable TLS for dashboard using Helm

### ISSUE THREAD

**Issue by Fidenz-Lasithh** [emqx/emqx#5703]
How do I enable TLS for EMQX dashboard using helm. I tried the following but didn't work.

```
ingress:
  dashboard:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    path: /
    hosts:
    - ptemqxmqtt.westeurope.cloudapp.azure.com
    tls: []
```
UPDATE: To add a little more to the question, I couldn't find the documentation for the possible values for `tls:[]`
