### ISSUE TITLE
emqx in docker does not run when using host mappings, only runs with volumes

### ISSUE THREAD

**Issue by laundmo** [emqx/emqx#6091]
### Subject of the support
When running the emqx docker image, i am able to run it when using docker volumes, but not with host mappings.

The main issue is this: `[error] Could not open file (/opt/emqx/etc/emqx.conf) for Reason enoent`
But i also get other issues when not using a bind mount for `etc`

To me it seems that emqx does not properly create the files it needs when using bind mounts.

<details>
<summary>Logs and docker-compose with volumes</summary>

```yaml
services:
  emqx:
    image: emqx/emqx:4.3.9
    restart: unless-stopped
    ports:
      - 18083:18083 
      - 8081:8081
      - 11883:11883
      - 1883:1883
      - 8083:8083
      - 8883:8883
      - 8084:8084
    environment:
      EMQX_NAME: geosens_emqx
      EMQX_HOST: 127.0.0.1
      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard"
    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log

volumes:
  vol-emqx-data:
    name: emqx-data
  vol-emqx-etc:
    name: emqx-etc
  vol-emqx-log:
    name: emqx-log
```

```
emqx_1      | EMQX_LOADED_PLUGINS=emqx_recon emqx_retainer emqx_management emqx_dashboard
emqx_1      | listener.ssl.external.acceptors = "32"
emqx_1      | listener.ssl.external.max_connections = "102400"
emqx_1      | listener.tcp.external.acceptors = "64"
emqx_1      | listener.tcp.external.max_connections = "1024000"
emqx_1      | listener.ws.external.acceptors = "16"
emqx_1      | listener.ws.external.max_connections = "102400"
emqx_1      | listener.wss.external.acceptors = "16"
emqx_1      | listener.wss.external.max_connections = "102400"
emqx_1      | log.to = "console"
emqx_1      | node.max_ets_tables = "2097152"
emqx_1      | node.max_ports = "1048576"
emqx_1      | node.name = "geosens_emqx@127.0.0.1"
emqx_1      | node.process_limit = "2097152"
emqx_1      | rpc.port_discovery = "manual"
emqx_1      | Starting emqx on node geosens_emqx@127.0.0.1
emqx_1      | Start http:management listener on 8081 successfully.
emqx_1      | Start http:dashboard listener on 18083 successfully.
emqx_1      | Start mqtt:tcp:internal listener on 127.0.0.1:11883 successfully.
emqx_1      | Start mqtt:tcp:external listener on 0.0.0.0:1883 successfully.
emqx_1      | Start mqtt:ws:external listener on 0.0.0.0:8083 successfully.
emqx_1      | Start mqtt:ssl:external listener on 0.0.0.0:8883 successfully.
emqx_1      | Start mqtt:wss:external listener on 0.0.0.0:8084 successfully.
emqx_1      | EMQ X Broker 4.3.9 is running now!
```

</details>

<details>
<summary>Logs and docker-compose with host-mappings</summary>

```yaml
  emqx:
    image: emqx/emqx:4.3.9
    restart: unless-stopped
    ports:
      - 18083:18083 
      - 8081:8081
      - 11883:11883
      - 1883:1883
      - 8083:8083
      - 8883:8883
      - 8084:8084
    environment:
      EMQX_NAME: geosens_emqx
      EMQX_HOST: 127.0.0.1
      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard"
    volumes:
      - ./emqx/data:/opt/emqx/data
      - ./emqx/etc:/opt/emqx/etc
      - ./emqx/log:/opt/emqx/log
```

```
emqx_1      | EMQX_LOADED_PLUGINS=emqx_recon emqx_retainer emqx_management emqx_dashboard
emqx_1      | 2021-11-08T16:48:11.771130+00:00 [error] Could not open file (/opt/emqx/etc/emqx.conf) for Reason enoent
emqx_1      | EMQX_LOADED_PLUGINS=emqx_recon emqx_retainer emqx_management emqx_dashboard
emqx_1      | 2021-11-08T16:48:14.650757+00:00 [error] Could not open file (/opt/emqx/etc/emqx.conf) for Reason enoent
```
</details>

### Your environment

this is concerning the startup process in docker and as such i dont think node_dump would work

Otherwise please provide below info:
- EMQ X version (e.g. `emqx_ctl status`): 4.3.9 (docker)
- Hardware configuration (e.g. `lscpu`): <details>

    ```
    Architecture:                    x86_64
    CPU op-mode(s):                  32-bit, 64-bit
    Byte Order:                      Little Endian
    Address sizes:                   39 bits physical, 48 bits virtual
    CPU(s):                          16
    On-line CPU(s) list:             0-15
    Thread(s) per core:              2
    Core(s) per socket:              8
    Socket(s):                       1
    NUMA node(s):                    1
    Vendor ID:                       GenuineIntel
    CPU family:                      6
    Model:                           167
    Model name:                      11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
    Stepping:                        1
    CPU MHz:                         3600.000
    CPU max MHz:                     5000,0000
    CPU min MHz:                     800,0000
    BogoMIPS:                        7200.00
    L1d cache:                       384 KiB
    L1i cache:                       256 KiB
    L2 cache:                        4 MiB
    L3 cache:                        16 MiB
    NUMA node0 CPU(s):               0-15
    Vulnerability Itlb multihit:     Not affected
    Vulnerability L1tf:              Not affected
    Vulnerability Mds:               Not affected
    Vulnerability Meltdown:          Not affected
    Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
    Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
    Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
    Vulnerability Srbds:             Not affected
    Vulnerability Tsx async abort:   Not affected
    Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm c
                                    onstant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl smx est
                                    tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_
                                    fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap
                                    avx512ifma clflushopt intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window
                                    hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm md_clear flush_l
                                    1d arch_capabilities
    ```

    </details>
- OS (e.g. `cat /etc/os-release`): Ubuntu 21.04 (Hirsute Hippo)
- Kernel (e.g. `uname -a`): `Linux jona 5.11.0-37-generic #41-Ubuntu SMP Mon Sep 20 16:39:20 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Others: 
  - Docker version 20.10.9, build c2ea9bc
  - docker-compose version 1.29.2,

### LOG File

Logs are in the expandable sections further up.
