### ISSUE TITLE
docker swarm listener.tcp.external.proxy_protocol does not work

### ISSUE THREAD

**Issue by seqwait** [emqx/emqx#6359]
docker version: 20.10.11
emqx version: emqx/emqx:v4.0.0
os: CentOS Linux release 8.4.2105
docker-compose
```
  emqx1:
    image: emqx/emqx:v4.0.0
    environment:
      - "EMQX_NAME=emqx"
      - "EMQX_HOST=node2.emqx.io"
      - "EMQX_ALLOW_ANONYMOUS=false"
      - "EMQX_CLUSTER__DISCOVERY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io, emqx@node2.emqx.io"
      - "EMQX_LOADED_PLUGINS=emqx_management,emqx_recon,emqx_retainer,emqx_dash\
        board,emqx_auth_username,emqx_auth_redis,emqx_web_hook"
      #- "EMQX_LISTENER__TCP__EXTERNAL__PROXY_PROTOCOL=on"
```
 set EMQX_LISTENER__TCP__EXTERNAL__PROXY_PROTOCOL=on  it could not connect emqx otherwise it is ok!
