### ISSUE TITLE
docker-compose 部署 emqx集群，集群方式选择 etcd，报错！

### ISSUE THREAD

**Issue by iGoogle-ink** [emqx/emqx#6422]
docker-compose 如下

```
version: "3"
services:
  emqx:
    image: emqx/emqx:4.3.10
    container_name: emqx
    restart: always
    volumes:
      - /sys:/sys
    ulimits:
      nproc: 1048576
      nofile:
        soft: 1048576
        hard: 1048576
    environment:
      - EMQX_NODE__PROCESS_LIMIT=2097152
      - EMQX_NODE__MAX_PORTS=1048576
      - EMQX_LISTENER__TCP__EXTERNAL=0.0.0.0:1883
      - EMQX_LISTENER__TCP__EXTERNAL__ACCEPTORS=64
      - EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS=1048576
      - EMQX_ALLOW_ANONYMOUS=true
      - EMQX_LOADED_PLUGINS=emqx_management,emqx_auth_mysql,emqx_recon,emqx_retainer,emqx_dashboard,emqx_rule_engine
      - EMQX_MQTT__MAX_PACKET_SIZE=1024KB
      - EMQX_AUTH__MYSQL__USERNAME=root
      - EMQX_AUTH__MYSQL__PASSWORD=123456
      - EMQX_AUTH__MYSQL__DATABASE=emqx
      - EMQX_AUTH__MYSQL__SERVER=localhost:3306
      - EMQX_AUTH__MYSQL__PASSWORD_HASH=sha256
      - EMQX_AUTH__MYSQL__AUTH_QUERY=SELECT password FROM mqtt_user WHERE username = '%u' LIMIT 1
      - EMQX_AUTH__MYSQL__SUPER_QUERY=SELECT is_super FROM mqtt_user WHERE username = '%u' LIMIT 1
      - EMQX_AUTH__MYSQL__ACL_QUERY=SELECT allow, ipaddr, username, clientid, access, topic FROM mqtt_acl WHERE ipaddr = '%a' OR username = '%u' OR username = '$all' OR clientid = '%c'
      - EMQX_NAME=emqx
      - EMQX_HOST=172.16.1.214
      - EMQX_CLUSTER__DISCOVERY=etcd
      - EMQX_CLUSTER__ETCD__SERVER=http://172.16.1.207:2379
      - EMQX_CLUSTER__ETCD__PREFIX=emqcl
      - EMQX_CLUSTER__ETCD__NODE_TTL=1m
      - EMQX_CLUSTER__AUTOHEAL=on
      - EMQX_CLUSTER__AUTOCLEAN=5m
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
```

![image](https://user-images.githubusercontent.com/17245594/145544128-265cc82a-28ea-456a-a2f4-292141deb6a8.png)

日志如下：
```
emqx    | Start mqtt:tcp:internal listener on 127.0.0.1:11883 successfully.
emqx    | Start mqtt:tcp:external listener on 0.0.0.0:1883 successfully.
emqx    | Start mqtt:ws:external listener on 0.0.0.0:8083 successfully.
emqx    | Start mqtt:ssl:external listener on 0.0.0.0:8883 successfully.
emqx    | Start mqtt:wss:external listener on 0.0.0.0:8084 successfully.
emqx    | Start http:management listener on 8081 successfully.
emqx    | Start http:dashboard listener on 18083 successfully.
emqx    | EMQ X Broker 4.3.10 is running now!
emqx    | 2021-12-10T08:41:17.601757+00:00 [error] Ekka(AutoCluster): AutoCluster stopped for lock error: {404,"404 page not found\n"}
emqx    | 2021-12-10T08:41:22.609189+00:00 [error] Ekka(AutoCluster): AutoCluster stopped for lock error: {404,"404 page not found\n"}
emqx    | 2021-12-10T08:41:27.599449+00:00 [error] Ekka(AutoCluster): AutoCluster stopped for lock error: {404,"404 page not found\n"}
emqx    | 2021-12-10T08:41:32.609833+00:00 [error] Ekka(AutoCluster): AutoCluster stopped for lock error: {404,"404 page not found\n"}
emqx    | 2021-12-10T08:41:37.635642+00:00 [error] Ekka(AutoCluster): AutoCluster stopped for lock error: {404,"404 page not found\n"}
```
