### ISSUE TITLE
Can't load auth_http plugin from env when using helm

### ISSUE THREAD

**Issue by lonelyleaf** [emqx/emqx#6513]
### Subject of the issue
I'm trying to install emqx cluster in k8s, with http auth and acl.But when using version 4.3 ,emq can't load my config from env.

My helm values:
```yaml
affinity: {}
containerSecurityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000
emqxAclConfig: |
  {allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}. {allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}. {deny, all, subscribe, ["$SYS/#", {eq, "#"}]}. {allow, all}.
emqxConfig:
  EMQX_CLUSTER__K8S__ADDRESS_TYPE: hostname
  EMQX_CLUSTER__K8S__APISERVER: https://kubernetes.default.svc:443
  EMQX_CLUSTER__K8S__SUFFIX: svc.cluster.local
  EMQX_AUTH__HTTP__AUTH_REQ__URL: http://wid-backend.wid-backend:8080/mqtt/auth
  EMQX_AUTH__HTTP__AUTH_REQ__CONTENT_TYPE: x-www-form-urlencoded
  EMQX_AUTH__HTTP__AUTH_REQ__METHOD: post
  EMQX_AUTH__HTTP__AUTH_REQ__PARAMS: clientid=%c,username=%u,password=%P,protocol=%r,clientPort=%p
  EMQX_AUTH__HTTP__ACL_REQ__URL: "http://wid-backend.wid-backend:8080/mqtt/acl"
  EMQX_AUTH__HTTP__ACL_REQ__CONTENT_TYPE: x-www-form-urlencoded
  EMQX_AUTH__HTTP__ACL_REQ__METHOD: post
  EMQX_AUTH__HTTP__ACL_REQ__PARAMS: access=%A,username=%u,clientid=%c,ipaddr=%a,topic=%t,mountpoint=%m
emqxLicneseSecretName: null
emqxLoadedModules: |
  {emqx_mod_acl_internal, true}. {emqx_mod_presence, true}. {emqx_mod_delayed, false}. {emqx_mod_rewrite, false}. {emqx_mod_subscription, false}. {emqx_mod_topic_metrics, false}.
emqxLoadedPlugins: |
  {emqx_management, true}. {emqx_recon, true}. {emqx_retainer, true}. {emqx_dashboard, true}. {emqx_telemetry, true}. {emqx_rule_engine, true}. {emqx_bridge_mqtt, false}. {emqx_auth_http, true}. {emqx_statsd, true}.
image:
  pullPolicy: IfNotPresent
  repository: emqx/emqx
ingress:
  dashboard:
    annotations: {}
    enabled: false
    hosts:
    - dashboard.emqx.local
    path: /
    tls: []
  mgmt:
    annotations: {}
    enabled: false
    hosts:
    - api.emqx.local
    path: /
    tls: []
initContainers: {}
nodeSelector: {}
persistence:
  accessMode: ReadWriteOnce
  enabled: false
  size: 20Mi
podManagementPolicy: Parallel
podSecurityContext:
  enabled: true
  fsGroup: 1000
  fsGroupChangePolicy: Always
  runAsUser: 1000
  supplementalGroups:
  - 1000
recreatePods: false
replicaCount: 3
resources: {}
service:
  annotations: {}
  dashboard: 18083
  externalIPs: []
  loadBalancerSourceRanges: []
  mgmt: 8081
  mqtt: 1883
  mqttssl: 8883
  nodePorts:
    dashboard: null
    dashboardtls: null
    mgmt: null
    mqtt: null
    mqttssl: null
    ws: null
    wss: null
  type: ClusterIP
  ws: 8083
  wss: 8084
tolerations: []
```

Emq logs:
```
cluster.discovery = "k8s"
cluster.k8s.address_type = "hostname"
cluster.k8s.apiserver = "https://kubernetes.default.svc:443"
cluster.k8s.app_name = "emqx"
cluster.k8s.namespace = "emqx"
cluster.k8s.service_name = "emqx-headless"
cluster.k8s.suffix = "svc.cluster.local"
listener.ssl.external.acceptors = "32"
listener.ssl.external.max_connections = "102400"
listener.tcp.external.acceptors = "64"
listener.tcp.external.max_connections = "1024000"
listener.ws.external.acceptors = "16"
listener.ws.external.max_connections = "102400"
listener.wss.external.acceptors = "16"
listener.wss.external.max_connections = "102400"
log.to = "console"
node.max_ets_tables = "2097152"
node.max_ports = "1048576"
node.name = "emqx@emqx-0.emqx-headless.emqx.svc.cluster.local"
node.process_limit = "2097152"
rpc.port_discovery = "manual"
Starting emqx on node emqx@emqx-0.emqx-headless.emqx.svc.cluster.local
Start mqtt:tcp:internal listener on 127.0.0.1:11883 successfully.
Start mqtt:tcp:external listener on 0.0.0.0:1883 successfully.
Start mqtt:ws:external listener on 0.0.0.0:8083 successfully.
Start mqtt:ssl:external listener on 0.0.0.0:8883 successfully.
Start mqtt:wss:external listener on 0.0.0.0:8084 successfully.
2021-12-22T02:25:27.848647+00:00 [alert] [Plugins] cannot_find_plugins: [emqx_statsd]
Start http:management listener on 8081 successfully.
Start http:dashboard listener on 18083 successfully.
EMQ X Broker 4.3.11 is running now!
```

It did't load my config from env.

### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/blob/master/bin/node_dump) 

- EMQ X version (e.g. `emqx_ctl status`):  4.3.11
- OS (e.g. `cat /etc/os-release`): docker image:emqx/emqx:4.3.11
