### ISSUE TITLE
docker swarm node service auto exit

### ISSUE THREAD

**Issue by seqwait** [emqx/emqx#6606]
docker version: Docker version 20.10.11, build dea9396
system: CentOS Linux release 8.4.2105
emqx version: emqx/emqx:v4.0.0
docker network : overlay
node discovery : static

compose file
```
version: '3.7'

services:
  emqx1:
    image: emqx/emqx:v4.0.0
    environment:
      - "EMQX_NAME=emqx"
      - "EMQX_HOST=node1.emqx.io"
      - "EMQX_ALLOW_ANONYMOUS=false"
      - "EMQX_CLUSTER__DISCOVERY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io, emqx@node2.emqx.io"
      - "EMQX_LOADED_PLUGINS=emqx_management,emqx_recon,emqx_retainer,emqx_dash\
        board,emqx_auth_username,emqx_auth_redis,emqx_web_hook"
      - "EMQX_ZONE__EXTERNAL__MAX_INFLIGHT=1024"
      - "EMQX_LISTENER__TCP__EXTERNAL__PROXY_PROTOCOL=on"
      - "EMQX_LISTENER__TCP__EXTERNAL__PROXY_PROTOCOL_TIMEOUT=15s"
      - "EMQX_DASHBOARD__DEFAULT_USER__LOGIN=admin"
      - "EMQX_DASHBOARD__DEFAULT_USER__PASSWORD=123321"
      - "EMQX_AUTH__USER__PASSWORD_HASH=plain"
      - "EMQX_AUTH__USER__1__USERNAME=admin"
      - "EMQX_AUTH__USER__1__PASSWORD=admin123"
      - "EMQX_AUTH__REDIS__SERVER=yoyo-redis.com"
      - "EMQX_AUTH__REDIS__POOL=8"
      - "EMQX_AUTH__REDIS__DATABASE=4"
      - "EMQX_AUTH__REDIS__PASSWORD=123321"
      - "EMQX_AUTH__REDIS__AUTH_CMD=HMGET mqtt_user:%u password"
      - "EMQX_AUTH__REDIS__PASSWORD_HASH=plain"
      - "EMQX_AUTH__REDIS__SUPER_CMD=HGET mqtt_user:%u is_superuser"
      - "EMQX_AUTH__REDIS_ACL_CMD=HGETALL mqtt_acl:%u"
      - "EMQX_LOG__TO=file"
      - "EMQX_LOG__LEVEL=error"
      - "EMQX_LOG__ROTATION__SIZE=200MB"
      - "EMQX_LOG__ROTATION__COUNT=5"
    deploy:
      placement:
        constraints:
          - "node.labels.emqx1 == yes"
    networks:
      overall_yy:
        aliases:
          - node1.emqx.io

  emqx2:
    image: emqx/emqx:v4.0.0
    environment:
      - "EMQX_NAME=emqx"
      - "EMQX_HOST=node2.emqx.io"
      - "EMQX_ALLOW_ANONYMOUS=false"
      - "EMQX_CLUSTER__DISCOVERY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io, emqx@node2.emqx.io"
      - "EMQX_LOADED_PLUGINS=emqx_management,emqx_recon,emqx_retainer,emqx_dash\
        board,emqx_auth_username,emqx_auth_redis,emqx_web_hook"
      - "EMQX_ZONE__EXTERNAL__MAX_INFLIGHT=1024"
      - "EMQX_LISTENER__TCP__EXTERNAL__PROXY_PROTOCOL=on"
      - "EMQX_LISTENER__TCP__EXTERNAL__PROXY_PROTOCOL_TIMEOUT=15s"
      - "EMQX_DASHBOARD__DEFAULT_USER__LOGIN=admin"
      - "EMQX_DASHBOARD__DEFAULT_USER__PASSWORD=123321"
      - "EMQX_AUTH__USER__PASSWORD_HASH=plain"
      - "EMQX_AUTH__USER__1__USERNAME=admin"
      - "EMQX_AUTH__USER__1__PASSWORD=admin123"
      - "EMQX_AUTH__REDIS__SERVER=yoyo-redis.com"
      - "EMQX_AUTH__REDIS__POOL=8"
      - "EMQX_AUTH__REDIS__DATABASE=4"
      - "EMQX_AUTH__REDIS__PASSWORD=123321"
      - "EMQX_AUTH__REDIS__AUTH_CMD=HMGET mqtt_user:%u password"
      - "EMQX_AUTH__REDIS__PASSWORD_HASH=plain"
      - "EMQX_AUTH__REDIS__SUPER_CMD=HGET mqtt_user:%u is_superuser"
      - "EMQX_AUTH__REDIS_ACL_CMD=HGETALL mqtt_acl:%u"
      - "EMQX_LOG__TO=file"
      - "EMQX_LOG__LEVEL=error"
      - "EMQX_LOG__ROTATION__SIZE=200MB"
      - "EMQX_LOG__ROTATION__COUNT=5"
    deploy:
      placement:
        constraints:
          - "node.labels.emqx2 == yes"
    networks:
      overall_yy:
        aliases:
          - node2.emqx.io
```

service
```
7rztxkohq2wn   yy_emqx1.1       emqx/emqx:v4.0.0   yy-emqx   Running         Running about an hour ago
9zccvhaf8bd9    \_ yy_emqx1.1   emqx/emqx:v4.0.0   yy-emqx   Shutdown        Failed about an hour ago    "task: non-zero exit (1)"
ss8aksckpj4o    \_ yy_emqx1.1   emqx/emqx:v4.0.0   yy-emqx   Shutdown        Failed 27 hours ago         "task: non-zero exit (1)"
tszq7gta5kkn    \_ yy_emqx1.1   emqx/emqx:v4.0.0   yy-emqx   Shutdown        Failed 2 days ago           "task: non-zero exit (1)"
t1lp4wttfgwa    \_ yy_emqx1.1   emqx/emqx:v4.0.0   yy-emqx   Shutdown        Shutdown 2 weeks ago
```

kernel log:
```
Jan  3 15:52:13 yy-emqx NetworkManager[844]: <info>  [1641196333.0932] manager: (vethbbf36f3): new Veth device (/org/freedesktop/NetworkManager/Devices/203)
Jan  3 15:52:13 yy-emqx kernel: docker_gwbridge: port 2(veth98f0234) entered disabled state
Jan  3 15:52:13 yy-emqx kernel: device veth98f0234 left promiscuous mode
Jan  3 15:52:13 yy-emqx kernel: docker_gwbridge: port 2(veth98f0234) entered disabled state
Jan  3 15:52:13 yy-emqx NetworkManager[844]: <info>  [1641196333.1013] device (veth98f0234): released from master device docker_gwbridge
Jan  3 15:52:13 yy-emqx kernel: br0: port 3(veth1) entered disabled state
Jan  3 15:52:13 yy-emqx kernel: device veth1 left promiscuous mode
Jan  3 15:52:13 yy-emqx kernel: br0: port 3(veth1) entered disabled state
Jan  3 15:52:13 yy-emqx systemd[1]: run-docker-netns-a249aa447820.mount: Succeeded.
Jan  3 15:52:13 yy-emqx systemd[1]: var-lib-docker-overlay2-9b821df723bb6b569069e282f03a95df196fa3d874dd2b593a27289b306fd237-merged.mount: Succeeded.
Jan  3 15:52:13 yy-emqx dockerd[29031]: time="2022-01-03T15:52:13.166717560+08:00" level=error msg="fatal task error" error="task: non-zero exit (1)" module=node/agent/taskmanager node.id=4kjl5tb9k1zbx13sks3zv5nj2 service.id=hrz2rc727fcvcmao0izs3aj2a task.id=9zccvhaf8bd9bzymc4ofdltoi
Jan  3 15:52:13 yy-emqx kernel: br0: port 2(veth0) entered disabled state
Jan  3 15:52:13 yy-emqx kernel: br0: port 1(vxlan0) entered disabled state
Jan  3 15:52:13 yy-emqx kernel: ov-001002-8y05s: renamed from br0
Jan  3 15:52:13 yy-emqx kernel: device veth0 left promiscuous mode
Jan  3 15:52:13 yy-emqx kernel: ov-001002-8y05s: port 2(veth0) entered disabled state
Jan  3 15:52:13 yy-emqx kernel: device vxlan0 left promiscuous mode
Jan  3 15:52:13 yy-emqx kernel: ov-001002-8y05s: port 1(vxlan0) entered disabled state
Jan  3 15:52:13 yy-emqx kernel: vx-001002-8y05s: renamed from vxlan0
Jan  3 15:52:13 yy-emqx systemd-udevd[3176038]: Using default interface naming scheme 'rhel-8.0'.
Jan  3 15:52:13 yy-emqx kernel: veth9558352: renamed from veth0
```

dockerd log:
```
1月 03 15:39:10 yy-emqx dockerd[29031]: time="2022-01-03T15:39:10.980821013+08:00" level=info msg="NetworkDB stats yy-emqx(8a9cf4207def) - netID:pup51us16xk21k0rnrx4c7n6k leaving:false netPeers:10 entries:52 Queue qLen:0 netMsg/s:0"
1月 03 15:39:10 yy-emqx dockerd[29031]: time="2022-01-03T15:39:10.980868126+08:00" level=info msg="NetworkDB stats yy-emqx(8a9cf4207def) - netID:8y05sf6g7n40elsjk2fnkgs7p leaving:false netPeers:9 entries:61 Queue qLen:0 netMsg/s:0"
1月 03 15:40:21 yy-emqx dockerd[29031]: time="2022-01-03T15:40:21.585293266+08:00" level=error msg="Bulk sync to node 911db2fdc59c timed out"
1月 03 15:43:21 yy-emqx dockerd[29031]: time="2022-01-03T15:43:21.584495803+08:00" level=error msg="Bulk sync to node ecad7005ac9b timed out"
1月 03 15:44:11 yy-emqx dockerd[29031]: time="2022-01-03T15:44:11.180929328+08:00" level=info msg="NetworkDB stats yy-emqx(8a9cf4207def) - netID:pup51us16xk21k0rnrx4c7n6k leaving:false netPeers:10 entries:52 Queue qLen:0 netMsg/s:0"
1月 03 15:44:11 yy-emqx dockerd[29031]: time="2022-01-03T15:44:11.180980376+08:00" level=info msg="NetworkDB stats yy-emqx(8a9cf4207def) - netID:8y05sf6g7n40elsjk2fnkgs7p leaving:false netPeers:9 entries:61 Queue qLen:0 netMsg/s:0"
1月 03 15:45:51 yy-emqx dockerd[29031]: time="2022-01-03T15:45:51.584890215+08:00" level=error msg="Bulk sync to node ecad7005ac9b timed out"
1月 03 15:47:21 yy-emqx dockerd[29031]: time="2022-01-03T15:47:21.584815665+08:00" level=error msg="Bulk sync to node ecad7005ac9b timed out"
1月 03 15:49:11 yy-emqx dockerd[29031]: time="2022-01-03T15:49:11.380977915+08:00" level=info msg="NetworkDB stats yy-emqx(8a9cf4207def) - netID:pup51us16xk21k0rnrx4c7n6k leaving:false netPeers:10 entries:52 Queue qLen:0 netMsg/s:0"
1月 03 15:49:11 yy-emqx dockerd[29031]: time="2022-01-03T15:49:11.381035555+08:00" level=info msg="NetworkDB stats yy-emqx(8a9cf4207def) - netID:8y05sf6g7n40elsjk2fnkgs7p leaving:false netPeers:9 entries:61 Queue qLen:0 netMsg/s:0"
1月 03 15:52:13 yy-emqx dockerd[29031]: time="2022-01-03T15:52:13.017250901+08:00" level=info msg="ignoring event" container=086b4407117c3b3d8519cac4ccdc6bbf237243e097c0c467989a6785261553e1 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
1月 03 15:52:13 yy-emqx dockerd[29031]: time="2022-01-03T15:52:13.166717560+08:00" level=error msg="fatal task error" error="task: non-zero exit (1)" module=node/agent/taskmanager node.id=4kjl5tb9k1zbx13sks3zv5nj2 service.id=hrz2rc727fcvcmao0izs3aj2a task.id=9zccvhaf8bd9bzymc4ofdltoi
1月 03 15:52:13 yy-emqx dockerd[29031]: time="2022-01-03T15:52:13.306529648+08:00" level=warning msg="Error (Unable to complete atomic operation, key modified) deleting object [endpoint 8y05sf6g7n40elsjk2fnkgs7p 1f7e69babb57cc6116193119dcc1e741a9e4cf9a150ec621301035e5e3914ec3], retrying...."
```
