### ISSUE TITLE
appid lost

### ISSUE THREAD

**Issue by itmisx** [emqx/emqx#6729]
The docker-compose configuration is as follows：
```yaml
  emqx:
    image: emqx/emqx:4.3.11
    container_name: "emqx"
    environment:
      - EMQX_LOADED_PLUGINS="emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_mysql"
      - EMQX_AUTH__MYSQL__SERVER="mysql"
      - EMQX_AUTH__MYSQL__POOL=2
      - EMQX_AUTH__MYSQL__USERNAME="root"
      - EMQX_AUTH__MYSQL__PASSWORD="xxx"
      - EMQX_AUTH__MYSQL__DATABASE="emqx"
      - EMQX_AUTH__MYSQL__PASSWORD__HASH="plain"
    ports:
      - 1883:1883
      - 18083:18083
    volumes:
      - ./emqx/etc:/opt/emqx/etc
      - ./emqx/data:/opt/emqx/data
      - ./emqx/log:/opt/emqx/log
    restart: 'always'
    logging:
      options:
        max-file: "5"
        max-size: "50M"
```

then i create a appID in /General/Applications.but when i delete the container `docker rm -f emqx`，and recreate the container `docker-compose up -d`,the appID i created is lost.

**Comment by HJianBo** [comment]
The data did disappear, due to a change in the node name of emqx, after re-creating the new container. By default, the node name of emqx defaults to `{container-name}@{IP}`.

You can fix the emqx node name to ensure that data is not lost after each re-creation of the emqx container. e.g:

```
  emqx1:
    container_name: node1.emqx.io
    environment:
      - "EMQX_HOST=node1.emqx.io"
    networks:
      emqx_bridge:
        aliases:
        - node1.emqx.io
```

**Comment by itmisx** [comment]
Thanks a lot and hope it's explained in the documentation to help others.

**Comment by itmisx** [comment]
I modify my docker-compose.yaml, like this
```yaml
  emqx:
    image: emqx/emqx:4.3.11
    container_name: "node1.emqx.io"
    environment:
      - "EMQX_HOST=node1.emqx.io"
      - "EMQX_LOADED_PLUGINS=emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_mysql"
      - "EMQX_AUTH__MYSQL__SERVER=mysql"
      - "EMQX_AUTH__MYSQL__POOL=2"
      - "EMQX_AUTH__MYSQL__USERNAME=root"
      - "EMQX_AUTH__MYSQL__PASSWORD=xxx"
      - "EMQX_AUTH__MYSQL__DATABASE=emqx"
      - "EMQX_AUTH__MYSQL__PASSWORD__HASH=plain"
    ports:
      - 1883:1883
      - 18083:18083
    volumes:
      - ./emqx/etc:/opt/emqx/etc
      - ./emqx/data:/opt/emqx/data
      - ./emqx/log:/opt/emqx/log
    networks:
      emqx-bridge:
        aliases:
        - node1.emqx.io
    restart: 'always'
    logging:
      options:
        max-file: "5"
        max-size: "50M"
networks:
  emqx-bridge:
    driver: bridge
```
> But the problem is still not resolved.
