### ISSUE TITLE
only latest test arm64 image is setting up port maps

### ISSUE THREAD

**Issue by dkebler** [emqx/emqx#6745]
Just some feedback.

https://hub.docker.com/r/emqx/emqx/tags

I wasn't able to get any of the arm64 images to work except this new one just published.  The older images would not map the ports to host.  FYI I've never had any issues with amd64 images this was my first attempt to run emqx on an arm64 box.

https://hub.docker.com/layers/emqx/emqx/ci-william-test-docker-multi-arch-push/images/sha256-4ee5716515e5ffeb73018b11ad1366ebf2e9668037bf908de53ff15bd62697a6

**Comment by zmstone** [comment]
Hi @dkebler 
thank you for reporting it.
emqx-docker is for old builds. we have moved everything to this mono-repo since 4.3

could you be more specific about this issue though?
maybe provide a docker run command example. 
e.g. `docker run -p 1883:1883 emqx/emqx:TAG`

**Comment by dkebler** [comment]
All the ports below would not map to the host from the contain except with the docker hub image I mentioned.
The other images which have a tag of arm64 all failed

e.g 4.3.11 lists arm64 but that image does not work with arm64 (as in the ports don't map to the host so it is useless)
https://hub.docker.com/r/emqx/emqx/tags



this works but only for this weirdly label image "william-test"  like someone was testing the build
```
version: "3"
services:
  emqx:
    container_name: mqtt-broker-emqx
# check back here for better image https://hub.docker.com/r/emqx/emqx/tags
    image: emqx/emqx:ci-william-test-docker-multi-arch-push
#  image: emqx/emqx:4.3.11-alpine-arm64v8  
    restart: always
    ports:
      - "1883:1883" # mqtt
      - "8083:8083" # ws
      - "8883:8883" # mqtts
      - "8084:8084" # wss
      - "18083:18083"
 ```
