### ISSUE TITLE
Stress Testing issue on k8s

### ISSUE THREAD

**Issue by cferrera** [emqx/emqx#7170]
### Subject of the support
Hello. I'm trying to release EMQX on kubernetes (helm chart) to support 500k clients (at first) but I'm failing on reach a stable deploy.
As described below, with **3x 7core 29GB** I can barely reach 60k clients on each node. The dashboard freezes and pretty soon the pods goes into OOM.

So I was wondering if EMQX is not designed to run hundreds of thousands connections in kubernetes or, if it is, which changes I'm missing.

Is there any benchmark around made on k8s?

Really appreciate any help.
Thanks a lot!

### Stresser Tool
https://github.com/inovex/mqtt-stresser
**10x 2 cpu 14Gb** = each spins up 50k clients at total, ramping up 30 clients every 5s and sending 1 message every second

### Your environment

Otherwise please provide below info:
- EMQ X version (e.g. `emqx_ctl status`): **4.3.11**
- If cluster (e.g. 3 X 4Core16GB): 
   &nbsp;&nbsp;&nbsp;&nbsp; AWS NLB
   &nbsp;&nbsp;&nbsp;&nbsp; **AWS EKS 3x 7core 29GB**
- OS (e.g. `cat /etc/os-release`):
   &nbsp;&nbsp;&nbsp;&nbsp; NAME="Alpine Linux"
   &nbsp;&nbsp;&nbsp;&nbsp; ID=alpine
   &nbsp;&nbsp;&nbsp;&nbsp; VERSION_ID=3.14.3
- Kernel (e.g. `uname -a`): **Linux emqx-0 5.4.129-63.229.amzn2.x86_64**
- Erlang/OTP version (in case you build emqx from source code): 
- Others: AWS EC2s

### EMQX Conf
emqxConfig:
   &nbsp;&nbsp;&nbsp;&nbsp;EMQX_CLUSTER__K8S__ADDRESS_TYPE: "hostname"
   &nbsp;&nbsp;&nbsp;&nbsp;EMQX_CLUSTER__K8S__SUFFIX: "svc.cluster.local"
   &nbsp;&nbsp;&nbsp;&nbsp;EMQX_CLUSTER__K8S__APP_NAME: "emqx"
   &nbsp;&nbsp;&nbsp;&nbsp;EMQX_CLUSTER__K8S__SERVICE_NAME: "emqx"
   &nbsp;&nbsp;&nbsp;&nbsp;EMQX_CLUSTER__K8S__NAMESPACE: "${namespace}"
   &nbsp;&nbsp;&nbsp;&nbsp;EMQX_BROKER_SHARED__SUBSCRIPTION__STRATEGY: "random"
   &nbsp;&nbsp;&nbsp;&nbsp;EMQX_BROKER_SHARED__DISPATCH__ACK__ENABLED: "${sharedAckEnabled}"
   &nbsp;&nbsp;&nbsp;&nbsp;EMQX_LISTENER__SSL__EXTERNAL__FAIL_IF_NO_PEER_CERT: true
   &nbsp;&nbsp;&nbsp;&nbsp;EMQX_LISTENER__SSL__EXTERNAL__VERIFY: verify_peer
   &nbsp;&nbsp;&nbsp;&nbsp;EMQX_LISTENER__SSL__EXTERNAL__KEYFILE: /opt/emqx/data/certs/emqx.key
   &nbsp;&nbsp;&nbsp;&nbsp;EMQX_LISTENER__SSL__EXTERNAL__CERTFILE: /opt/emqx/data/certs/emqx.crt
   &nbsp;&nbsp;&nbsp;&nbsp;EMQX_LISTENER__SSL__EXTERNAL__CACERTFILE: /opt/emqx/data/certs/ca.crt
   &nbsp;&nbsp;&nbsp;&nbsp;EMQX_LISTENER__TCP__EXTERNAL__ACCEPTORS: "64"
   &nbsp;&nbsp;&nbsp;&nbsp;EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: "5120000"
   &nbsp;&nbsp;&nbsp;&nbsp;EMQX_LISTENER__TCP__EXTERNAL__MAX_CONN_RATE: "300"
   &nbsp;&nbsp;&nbsp;&nbsp;\# 100,10s means that the maximum PUBLISH message rate allowed on each connection is 100 every 10 seconds.
   &nbsp;&nbsp;&nbsp;&nbsp;\# EMQX_LISTENER__TCP__EXTERNAL__RATE_LIMIT: "" #(msg/s)
   &nbsp;&nbsp;&nbsp;&nbsp;\# 100KB,10s means that the maximum TCP packet rate allowed on each connection is 100KB every 10 seconds.
   &nbsp;&nbsp;&nbsp;&nbsp;\# EMQX_ZONE__EXTERNAL__PUBLISH_LIMIT: "" #(bytes/s)
   &nbsp;&nbsp;&nbsp;&nbsp;EMQX_LOG__TO: "both"
   &nbsp;&nbsp;&nbsp;&nbsp;EMQX_LOG__LEVEL: "debug"
   &nbsp;&nbsp;&nbsp;&nbsp;EMQX_LOG__DIR: "/opt/emqx/log"
   &nbsp;&nbsp;&nbsp;&nbsp;EMQX_LOG__FILE: "emqx.log"
   &nbsp;&nbsp;&nbsp;&nbsp;EMQX_LOG__ERROR_FILE: "error.log"

**Comment by thalesmg** [comment]
Hi @cferrera !

While we have not specifically run benchmarks on k8s, we have done so in EC2 clusters and they did pretty well in terms of scale.  So, it's quite strange that only 60 k connections per node is making your pods OOM.

Do the nodes have some logs that can hint at problems?

Another thing to check is if the memory/vCPU limits for the deployment/pods are set correctly and not over-constraining the nodes.

**Comment by cferrera** [comment]
Hello @thalesmg @qzhuyan thanks for replying!

I did some further testing and benchmarking and I was able to reach these results:

Freq  | 1x 7cpu 29Gi 
-- | --
1 msg/ 1s | 50k stablefreezes at ~55k
1 msg/ 10s | 90k stable- freezes at ~91k;- memory at 12Gb
1 msg/ 20s | 170k stable- freezes at ~173k- memory at 25Gb
1 msg/ 30s | 243k stable- freezes at ~245k- memory at 26.7Gb
1 msg/ 60s | 355k stable

\* I've baked a custom AMI image based on the [tunning guide](https://www.emqx.io/docs/en/v4.3/tutorial/tune.html#linux-kernel-tuning)

So I believe that the message rate was the main point here, since the tutorial guide does not say anything about the messaging, can we presume that the benchmark was only for simultaneous connections without publishing?


#### _how much mem does each container take?_
I've dedicated nodes for EMQX in my cluster, each node is an **EC2 m5.2xlarge** (8vCPU/32Gb) and the emqx helm deploy allocates almost everything - just left some room for small agents and common stuff
```
resources:
  limits:
    cpu: 7
    memory: 29Gi
  requests:
    cpu: 7
    memory: 29Gi
```

About the stress-tool, I've tested two:

`mqtt-stresser`
```
        image: inovex/mqtt-stresser
        args:
          - -broker=tcp://{HOST}:1883
          - -publisher-qos=1
          - -subscriber-qos=1
          - -num-clients=3000
          - -num-messages=500
          - -rampup-size=30
          - -rampup-delay=5s
          - -pause-between-messages=1s
          - -global-timeout=3600s
          - -timeout=45s
          - -constant-payload="{\"stress\":\"true\",\"ts\":1645780406000,\"power\":100,\"id\":\"f96a23c4-a6ab-4ae6-88f2-95ee65141cbd\"}"
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 2
            memory: 1Gi
```

`emqtt-bench`
```
        imagePullPolicy: IfNotPresent
        image: mqtt-stresser:0.4.4-1-bench
        args:
          - pub
          - --host={HOST}
          - --port=1883
          - --version=5
          - --count=25000
          - --startnumber=0
          - --interval=5
          - --interval_of_msg=60000
          - --topic=status
          - --qos=1
          - --size=256
        resources:
          requests:
            cpu: 1
            memory: 3Gi
          limits:
            cpu: 2
            memory: 3Gi
```

> As a side note: emqtt-bench performed much better than mqtt-stresser, the only downside is you cannot set a custom message payload yet. Also, mqtt-stresser has a tricky stuff that it connects twice to the cluster (1pub/1sub) for each client expected - so if you try to spin up 20k it will connect twice of that.

As a final conclusion, I could say that my scenario was a little bit misconfigured - or if a single node is supposed to perform better than my results I really want to dig more -. 

I would really appreciate your final thoughts.
Thanks again!
