### ISSUE TITLE
Differing Helm chart versions in Github and chart repos

### ISSUE THREAD

**Issue by may-cDev** [emqx/emqx#7269]
### Subject of the support
While trying to deploy EMQX to kubernetes via Helm I figured out that the helm charts available via GitHub and via charts repo are quite different from each other. This led to some confusion while configuring the helm chart, especially because the chart from the chart repo is missing some functionality I would be interested in, e.g. the "envFromSecrets" parameter. 

As in the readme it's mentioned that the chart can be either downloaded from GitHub or via the charts repo (see https://github.com/emqx/emqx/tree/master/deploy/charts/emqx#installing-the-chart) I would have expected that those charts are the same.

Is there any reason why those charts differ? Are there plans to harmonize them?

### Your environment

Helm version: 3.8.0

**Comment by may-cDev** [comment]
Thanks for the fast response. 
Is there any overview where one can lookup which branch/revision is pushed to the helm repo?

I was mainly looking at the readme/files in the master branch and the ones I have pulled via helm via the following commands:

```
helm repo add emqx https://repos.emqx.io/charts
helm repo update emqx
helm pull emqx/emqx
```

When executing those commands I get the latest chart from the helm repo, 

e.g. the Charts.yaml looks like the following:

```yaml
apiVersion: v2
appVersion: 4.4.1
description: A Helm chart for EMQ X
name: emqx
type: application
version: 4.4.1
```

e.g. the values.yaml:

```yaml
affinity: {}
containerSecurityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000
emqxAclConfig: |
  {allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}. {allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}. {deny, all, subscribe, ["$SYS/#", {eq, "#"}]}. {allow, all}.
emqxConfig:
  EMQX_CLUSTER__DISCOVERY: k8s
  EMQX_CLUSTER__K8S__ADDRESS_TYPE: hostname
  EMQX_CLUSTER__K8S__APISERVER: https://kubernetes.default.svc:443
  EMQX_CLUSTER__K8S__APP_NAME: '{{ .Release.Name }}'
  EMQX_CLUSTER__K8S__NAMESPACE: '{{ .Release.Namespace }}'
  EMQX_CLUSTER__K8S__SERVICE_NAME: '{{ .Release.Name }}-headless'
  EMQX_CLUSTER__K8S__SUFFIX: svc.cluster.local
  EMQX_NAME: '{{ .Release.Name }}'
emqxLicenseSecretName: null
emqxLoadedModules: |
  {emqx_mod_acl_internal, true}. {emqx_mod_presence, true}. {emqx_mod_trace, false}. {emqx_mod_st_statistics, false}. {emqx_mod_delayed, false}. {emqx_mod_rewrite, false}. {emqx_mod_subscription, false}. {emqx_mod_topic_metrics, false}.
emqxLoadedPlugins: |
  {emqx_management, true}. {emqx_recon, true}. {emqx_retainer, true}. {emqx_dashboard, true}. {emqx_telemetry, true}. {emqx_rule_engine, true}. {emqx_bridge_mqtt, false}.
extraArgs: []
extraEnv: []
extraEnvFrom: []
extraVolumeMounts: []
extraVolumes: []
image:
  pullPolicy: IfNotPresent
  repository: emqx/emqx
ingress:
  annotations: {}
  dashboard:
    annotations: {}
    enabled: false
    hosts:
    - dashboard.emqx.local
    path: /
    tls: []
  mgmt:
    annotations: {}
    enabled: false
    hosts:
    - api.emqx.local
    path: /
    tls: []
  wss:
    annotations: {}
    enabled: false
    hosts:
    - wss.emqx.local
    path: /mqtt
    tls: []
initContainers: {}
nodeSelector: {}
persistence:
  accessMode: ReadWriteOnce
  enabled: false
  size: 20Mi
podManagementPolicy: Parallel
podSecurityContext:
  enabled: true
  fsGroup: 1000
  fsGroupChangePolicy: Always
  runAsUser: 1000
  supplementalGroups:
  - 1000
recreatePods: false
replicaCount: 3
resources: {}
service:
  annotations: {}
  dashboard: 18083
  externalIPs: []
  loadBalancerSourceRanges: []
  mgmt: 8081
  mqtt: 1883
  mqttssl: 8883
  nodePorts:
    dashboard: null
    dashboardtls: null
    mgmt: null
    mqtt: null
    mqttssl: null
    ws: null
    wss: null
  type: ClusterIP
  ws: 8083
  wss: 8084
tolerations: []
```

However, when searching through all of the branches I couldn't find any that has those files with that content. 
Therefore I'm still a bit confused on which state/branch the chart in the helm repo is based.
