### ISSUE TITLE
can not create a data bridge to Kafka

### ISSUE THREAD

**Issue by benckx** [emqx/emqx#7859]
### Subject of the support
When trying to create a Kafka resource in the EMQX dashboard (in order to create a data bridge to Kafka), I have to enter a Kafka username and password. So I deployed a Kafka with SASL_PLAINTEXT in order to enable simple username/password authentication. I can connect to this broker with another client, but the form on the EMQX dashboard responds with "Init resource failure!".

<img width="546" alt="Screenshot 2022-05-04 at 12 35 07" src="https://user-images.githubusercontent.com/8626080/166666658-68da6aad-82cb-41b7-8155-dad134417006.png">

I'm running EMQX with:
```
docker run -d --name emqx-ee -p 1883:1883 -p 8081:8081 -p 8083:8083 -p 8084:8084 -p 8883:8883 -p 18083:18083 emqx/emqx-ee:4.4.3
```

docker-compose.yaml:

```yaml
version: '2'
services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOOKEEPER_SERVERS: server.1=zookeeper:2888:3888
      ZOOKEEPER_SASL_ENABLED: "false"
    volumes:
      - ./zoo1/data:/data
      - ./zoo1/datalog:/datalog
  kafka:
    image: confluentinc/cp-kafka:5.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: SASL_PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ZOOKEEPER_SASL_ENABLED: "false"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
      - ./data:/var/lib/kafka/data
    links:
      - zookeeper
``` 

kafka_server_jaas.conf:
```conf
KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="admin"
  password="admin-secret"
  user_admin="admin-secret"
  user_alice="alice-secret";
};
Client{};
```

I'm able to connect to the Kafka with this auth set-up and list the topics:

jaas.conf:
```conf
KafkaClient {
org.apache.kafka.common.security.plain.PlainLoginModule required
username="admin"
password="admin-secret";
};
```

```scala
import org.apache.kafka.clients.admin.AdminClient

import java.util.Properties

object PlainAuthUtils {

  def buildAdminClient(): AdminClient = {
    System.setProperty("java.security.auth.login.config", "jaas.conf")
    val props = new Properties()
    props.put("bootstrap.servers", "localhost:9092")
    props.put("security.protocol", "SASL_PLAINTEXT")
    props.put("sasl.mechanism", "PLAIN")
    AdminClient.create(props)
  }

}
```

```scala
import scala.jdk.CollectionConverters.IterableHasAsScala

object ListTopics extends App {

  val client = PlainAuthUtils.buildAdminClient()
  val result = client.listTopics()
  while(!result.names().isDone) {
    println("waiting...")
    Thread.sleep(100)
  }
  result.names().get().asScala.foreach {name => println(name)}
  client.close()

}
```
```
> Task :kafka-spy-scripts:ListTopics.main()
waiting...
waiting...
some-test-topic
__confluent.support.metrics
```

### Your environment

Otherwise please provide below info:
- EMQX version: 4.4.3
- Hardware configuration (e.g. `lscpu`): Apple M1
- OS: MacOS
- Kernel: Darwin CMM-XF96L3X0FT 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

### LOG File

```
2022-05-04T10:20:58.716569+00:00 [error] cluster_call error found, ResL: [{{emqx_bridge_kafka_actions,on_resource_create},{throw,{connect_kafka_server_fail,[{<<"localhost:9092">>,connection_refused}]},[{emqx_bridge_kafka_actions,start_resource,3,[{file,"emqx_bridge_kafka_actions.erl"},{line,335}]},{emqx_bridge_kafka_actions,on_resource_create,2,[{file,"emqx_bridge_kafka_actions.erl"},{line,322}]},{emqx_rule_engine,init_resource,4,[{file,"emqx_rule_engine.erl"},{line,587}]},{erpc,execute_call,4,[{file,"erpc.erl"},{line,392}]}]}}]

2022-05-04T10:25:57.721214+00:00 [error] cluster_call error found, ResL: [{{emqx_bridge_kafka_actions,on_resource_create},{throw,{connect_kafka_server_fail,[{<<"localhost:9092">>,connection_refused}]},[{emqx_bridge_kafka_actions,start_resource,3,[{file,"emqx_bridge_kafka_actions.erl"},{line,335}]},{emqx_bridge_kafka_actions,on_resource_create,2,[{file,"emqx_bridge_kafka_actions.erl"},{line,322}]},{emqx_rule_engine,init_resource,4,[{file,"emqx_rule_engine.erl"},{line,587}]},{erpc,execute_call,4,[{file,"erpc.erl"},{line,392}]}]}}
```

**Comment by thalesmg** [comment]
Hi @benckx !

I see that you are running EMQX inside docker via `docker run`, and Kafka is running in a separate docker compose.  In that case, the URL `localhost:9092` won't work from inside EMQX's container.  You will need to connect the EMQX container network to docker compose's.

One easy way of making the containers talk to each other is to also put EMQX in your `docker-compose.yaml` and then connect to Kafka using `kafka:9092` instead of `localhost`.

**Comment by benckx** [comment]
You're right indeed.

Here is the updated docker-compose, where I managed to connect to `kafka:9092`:

```yaml
version: '2'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOOKEEPER_SERVERS: server.1=zookeeper:2888:3888
      ZOOKEEPER_SASL_ENABLED: "false"
    volumes:
      - ./zoo1/data:/data
      - ./zoo1/datalog:/datalog
  kafka:
    image: confluentinc/cp-kafka:5.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: SASL_PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ZOOKEEPER_SASL_ENABLED: "false"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
      - ./data:/var/lib/kafka/data
    links:
      - zookeeper
  emqx-ee:
    image: emqx/emqx-ee:4.4.3
    ports:
      - "1883:1883"
      - "8081:8081"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
```

Thanks. I will now attempt to configure a bridge.
