### ISSUE TITLE
Data Bridge to Kafka / Record key not always mapped

### ISSUE THREAD

**Issue by benckx** [emqx/emqx#7880]
### Subject of the support

I set up a MQTT-to-Kafka bridge in the Rule Engine, with Kafka record key mapped from "topic".

If the query is `SELECT * FROM "t/#"` (all fields) the key is properly set. But if the query is `SELECT payload FROM "t/#"` (just 1 field), the key is null. It looks like a bug, because the config is exactly the same in both cases, beside the `SELECT` clause. I don't see why this should behave differently.

### Your environment

Otherwise please provide below info:
- EMQX version: 4.4.3
- Hardware configuration (e.g. `lscpu`): Apple M1
- OS: MacOS
- Kernel: Darwin CMM-XF96L3X0FT 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

kafka_server_jaas.conf:
```conf
KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="admin"
  password="admin-secret"
  user_admin="admin-secret"
  user_alice="alice-secret";
};
Client{};
```

docker-compose.yaml:
```yaml
version: '2'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOOKEEPER_SERVERS: server.1=zookeeper:2888:3888
      ZOOKEEPER_SASL_ENABLED: "false"
    volumes:
      - ./zoo1/data:/data
      - ./zoo1/datalog:/datalog
  kafka:
    image: confluentinc/cp-kafka:5.1.0
    ports:
      - "9093:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: CONTAINER_LISTENER://0.0.0.0:29094,HOST_LISTENER://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: CONTAINER_LISTENER://kafka:29094,HOST_LISTENER://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTAINER_LISTENER:SASL_PLAINTEXT,HOST_LISTENER:SASL_PLAINTEXT
      ZOOKEEPER_SASL_ENABLED: "false"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      KAFKA_INTER_BROKER_LISTENER_NAME: CONTAINER_LISTENER
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
      - ./data:/var/lib/kafka/data
    links:
      - zookeeper
  emqx-ee:
    image: emqx/emqx-ee:4.4.3
    ports:
      - "1883:1883"
      - "8081:8081"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"

```

Resource:
```json
{
  "config": {
    "servers": "kafka:29094",
    "min_metadata_refresh_interval": "3s",
    "username": "admin",
    "password": "admin-secret",
    "sync_timeout": "3s",
    "max_batch_bytes": "900KB",
    "compression": "no_compression",
    "send_buffer": "1024KB",
    "query_api_versions": true,
    "ssl": false,
    "cacertfile": {
      "file": "",
      "filename": ""
    },
    "keyfile": {
      "file": "",
      "filename": ""
    },
    "certfile": {
      "file": "",
      "filename": ""
    },
    "verify": false
  },
  "description": "",
  "type": "bridge_kafka",
  "id": "resource:236690",
  "name": "bridge_kafka"
}
```

Rule:
```json
{
  "rawsql": "SELECT * FROM \"t/#\"",
  "actions": [
    {
      "name": "data_to_kafka",
      "params": {
        "topic": "output-test-topic-2",
        "type": "async",
        "strategy": "key_dispatch",
        "key": "topic",
        "required_acks": "all_isr",
        "partition_count_refresh_interval": "60s",
        "cache_mode": "Memory",
        "max_total_bytes": "2GB",
        "segments_bytes": "100MB",
        "highmem_drop": false,
        "payload_tmpl": "",
        "$resource": "resource:236690"
      },
      "fallbacks": []
    }
  ],
  "description": "",
  "id": "rule:926177"
}
```

### Steps to reproduce

Following code sends MQTT messages and consumes from the target Kafka topic:

When doing `SELECT * FROM "t/#"` (key is correct):
```
08:22:01.091 [Thread-5] INFO  c.c.i.i.b.MqttIntegrationExample$ - pushing UmCGMe1Vwj to t/input-test-topic/47 (MQTT)
08:22:01.146 [output-test-topic-2-reader] INFO  c.r.kafka.tools.CustomStreamReader - received record: org.apache.kafka.clients.consumer.ConsumerRecord@5f07cc38[
  checksum=<null>
  headers=RecordHeaders(headers = [], isReadOnly = false)
  key=t/input-test-topic/47
  leaderEpoch=Optional[0]
  offset=11
  partition=0
  serializedKeySize=21
  serializedValueSize=518
  timestamp=1651818121097
  timestampType=CreateTime
  topic=output-test-topic-2
  value={"username":"undefined","topic":"t/input-test-topic/47","timestamp":1651818121097,"qos":1,"publish_received_at":1651818121097,"pub_props":{},"peerhost":"172.18.0.1","payload":"UmCGMe1Vwj","node":"a86a0dbd4f63@172.18.0.3","metadata":{"rule_id":"rule:926177"},"id":"0005DE51E05770D06F6300000B0C0005","headers":{"username":"undefined","protocol":"mqtt","proto_ver":4,"properties":{},"peerhost":"172.18.0.1"},"flags":{"retain":false,"dup":false},"event":"message.publish","clientid":"779c8881-de6d-4256-9842-722b712c4a1b"}
]
```

When doing `SELECT payload FROM "t/#"` (key is null):
```
08:25:51.010 [Thread-5] INFO  c.c.i.i.b.MqttIntegrationExample$ - pushing 1m3EwSGVvF to t/input-test-topic/33 (MQTT)
08:25:51.069 [output-test-topic-2-reader] INFO  c.r.kafka.tools.CustomStreamReader - received record: org.apache.kafka.clients.consumer.ConsumerRecord@4a2a0773[
  checksum=<null>
  headers=RecordHeaders(headers = [], isReadOnly = false)
  key=<null>
  leaderEpoch=Optional[0]
  offset=17
  partition=5
  serializedKeySize=-1
  serializedValueSize=24
  timestamp=1651818351021
  timestampType=CreateTime
  topic=output-test-topic-2
  value={"payload":"1m3EwSGVvF"}
]
```

### Expected behaviour
Key should be set in both cases

### Actual behaviour
Key is null with query `SELECT payload FROM "t/#"`
