### ISSUE TITLE
Ingress broken on 4.4.4 Helm chart

### ISSUE THREAD

**Issue by onedr0p** [emqx/emqx#8131]
### What happened?

```
Helm upgrade failed: template: emqx/templates/ingress.dashboard.yaml:37:28: executing "emqx/templates/ingress.dashboard.yaml" at <.Values.ingress.dashboard.pathType>: can't evaluate field Values in type interface {}
```

Values:

```yaml
    ingress:
      dashboard:
        enabled: true
        ingressClassName: nginx
        path: /
        hosts:
          - emqx.domain.tld
        tls:
          - hosts:
              - emqx.domain.tld
```

### What did you expect to happen?

Ingress to work

### How can we reproduce it (as minimally and precisely as possible)?

Try to enable ingress on this helm chart

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>
