### ISSUE TITLE
k8s chart podAnnotations ?

### ISSUE THREAD

**Issue by siaron** [emqx/emqx#8144]
### What would you like to be added or enhanced?

- How to add Annotations to a pod? for example:
```
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
```

### Why is this needed?

Custom Annotations.

**Comment by zmstone** [comment]
are you using emqx-operator ?

**Comment by Rory-Z** [comment]
After deploy emqx-operator controller and waiting it running, you can create emqx custom resource file, like this:
```
apiVersion: apps.emqx.io/v1beta2
kind: EmqxBroker
metadata:
  name: emqx
  annotation:
    foo: "bar"
spec:
  image: emqx/emqx:4.4.4
```
