### ISSUE TITLE
Helm chart version 4.4.4 throws errors related with ingress

### ISSUE THREAD

**Issue by marcinbojko** [emqx/emqx#8185]
### What happened?

During
```bash
helm template emqx/emqx --version 4.4.4 -f values2.yaml --debug
```
there is an error when ingress dashboard or mgmt is set  enabled: true

```
Error: template: emqx/templates/ingress.dashboard.yaml:37:28: executing "emqx/templates/ingress.dashboard.yaml" at <.Values.ingress.dashboard.pathType>: can't evaluate field Values in type interface {}
helm.go:84: [debug] template: emqx/templates/ingress.dashboard.yaml:37:28: executing "emqx/templates/ingress.dashboard.yaml" at <.Values.ingress.dashboard.pathType>: can't evaluate field Values in type interface {}
```

### What did you expect to happen?

As with version 4.4.3

❯ helm template emqx/emqx --version 4.4.3 -f values2.yaml|kubeconform --verbose
stdin - ConfigMap release-name-emqx-acl is valid
stdin - ConfigMap release-name-emqx-loaded-plugins is valid
stdin - ConfigMap release-name-emqx-env is valid
stdin - ConfigMap release-name-emqx-loaded-modules is valid
stdin - ServiceAccount release-name-emqx is valid
stdin - RoleBinding release-name-emqx is valid
stdin - Role release-name-emqx is valid
stdin - Service release-name-emqx is valid
stdin - Service release-name-emqx-headless is valid
stdin - Ingress release-name-emqx-dashboard is valid
stdin - StatefulSet release-name-emqx is valid

### How can we reproduce it (as minimally and precisely as possible)?

values.yaml

```yaml
replicaCount: 3
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi
ingress:
  ## ingress for EMQX Dashboard
  dashboard:
    enabled: true
```

### EMQX version

helm chart 4.4.4

### OS version

not related

### Log files

<details>

</details>
