### ISSUE TITLE
Which ip did ipaddr get?

### ISSUE THREAD

**Issue by myifeng** [emqx/emqx#8591]
### What happened?

```
ipaddr=10.244.98.128
```

![image](https://user-images.githubusercontent.com/26652657/180451963-e31f6af0-72fd-4d4d-ab9e-842d2772340d.png)

But 10.244.98.128 is not my ip address, why is this?

### What did you expect to happen?

ipaddr=real IP

### How can we reproduce it (as minimally and precisely as possible)?

I am using emqx in the k8s cluster,I see in my `my-mqtt-auth` logs that the ipaddr parameter is not as expected.
``` yaml
          name: emqx
          image: emqx/emqx:4.3.16
          ports:
            - name: mqtt
              containerPort: 1883
            - name: mqttssl
              containerPort: 8883
            - name: mgmt
              containerPort: 8081
            - name: ws
              containerPort: 8083
            - name: wss
              containerPort: 8084
            - name: dashboard
              containerPort: 18083
          env:
            - name: EMQX_NAME
              value: "emqx"
            - name: EMQX_CLUSTER__DISCOVERY
              value: "k8s"
            - name: EMQX_CLUSTER__K8S__APP_NAME
              value: "emqx"
            - name: EMQX_CLUSTER__K8S__SERVICE_NAME
              value: "emqx-headless"
            - name: EMQX_CLUSTER__K8S__ADDRESS_TYPE
              value: "hostname"
            - name: EMQX_CLUSTER__K8S__APISERVER
              value: "https://kubernetes.default.svc:443"
            - name: EMQX_CLUSTER__K8S__SUFFIX
              value: "svc.cluster.local"
            - name: EMQX_CLUSTER__K8S__NAMESPACE
              value: "default"
            - name: EMQX_LOADED_PLUGINS
              value: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_http"
            - name: EMQX_AUTH__HTTP__AUTH_REQ__URL
              value: "http://my-mqtt-auth:8080/auth/user"
            - name: EMQX_AUTH__HTTP__AUTH_REQ__METHOD
              value: "post"
            - name: EMQX_AUTH__HTTP__AUTH_REQ__HEADERS__CONTENT_TYPE
              value: "application/json"
            - name: EMQX_AUTH__HTTP__AUTH_REQ__PARAMS
              value: "username=%u,password=%P,clientId=%c,ipaddr=%a"       
```
ingress.yaml
``` yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emqx
  annotations:
    kubernetes.io/ingress.class: "nginx"
  namespace: default
spec:
  rules:
    - host: emqx.domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emqx-service
                port:
                  number: 18083
```
ingress-tcp-udp-proxy.yaml
``` yaml
# tcp-data.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
# <namespace/service name>:<service port>:[PROXY]:[PROXY]
  1883: "default/emqx-service:1883"
  8883: "default/emqx-service:8883"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  namespace: ingress-nginx
```

### EMQX version

4.3.16

### OS version

Linux

### Log files

<details>

</details>
