### ISSUE TITLE
EMQX fails with config schema validation when attempting to configure first authorizer

### ISSUE THREAD

**Issue by agronholm** [emqx/emqx#8793]
### What happened?

I tried to configure an http authorizer for EMQX via environment variables, but it crashed with a configuration validation error, complaining about an unrecognized parameter, `path`.

### What did you expect to happen?

I expected the server to start normally.

### How can we reproduce it (as minimally and precisely as possible)?

Create the following `docker-compose.yml` and run `docker compose up emqx`:
```yaml
services:
  emqx:
    image: emqx/emqx:5.0.6
    environment:
      EMQX_AUTHORIZATION__SOURCES__1__TYPE: http
      EMQX_AUTHORIZATION__SOURCES__1__ENABLE: "true"
      EMQX_AUTHORIZATION__SOURCES__1__URL: http://web:8800/v1/integrations/mqtt/authorize
      EMQX_AUTHORIZATION__SOURCES__1__BODY: >
        {"username": "$${username}","password": "$${password}", "cert_subject": "$${cert_subject}", "topic": "$${topic}", "action": "$${action}"}
```

### Anything else we need to know?

The problem was caused by a preconfigured, internal file-based authorizer at index 1. Since the configuration was merged, the authorizer configuration had the parameter `path` which the http authorizer did not recognize. I could not find any mention in the documentation that custom authorizers need to start from index 2.

### EMQX version

<details>
sysdescr  : EMQX
version   : 5.0.6
datetime  : 2022-08-23T14:32:17.491631964+00:00
uptime    : 17 minutes, 15 seconds
</details>

### OS version

<details>
Linux fedora 5.18.18-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Aug 17 16:02:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
</details>

### Log files

<details>
eb_server-emqx-1  | 2022-08-24T11:26:23.794685+00:00 [error] failed_to_check_schema: emqx_conf_schema
eb_server-emqx-1  | 2022-08-24T11:26:23.796789+00:00 [error] #{kind => validation_error,mismatches => #{<<"authz:file">> => #{kind => validation_error,path => "authorization.sources.1",reason => unknown_fields,unknown => <<"body,url">>,unmatched => none},<<"authz:http_get">> => #{kind => validation_error,path => "authorization.sources.1",reason => unknown_fields,unknown => <<"path">>,unmatched => <<"connect_timeout,enable_pipelining...">>},<<"authz:http_post">> => #{kind => validation_error,path => "authorization.sources.1",reason => unknown_fields,unknown => <<"path">>,unmatched => <<"connect_timeout,enable_pipelining...">>},<<"authz:mnesia">> => #{kind => validation_error,path => "authorization.sources.1",reason => unknown_fields,unknown => <<"body,path...">>,unmatched => none},<<"authz:mongo_rs">> => #{kind => validation_error,path => "authorization.sources.1",reason => unknown_fields,unknown => <<"body,path...">>,unmatched => <<"auth_source,collection...">>},<<"authz:mongo_sharded">> => #{kind => validation_error,path => "authorization.sources.1",reason => unknown_fields,unknown => <<"body,path...">>,unmatched => <<"auth_source,collection...">>},<<"authz:mongo_single">> => #{kind => validation_error,path => "authorization.sources.1",reason => unknown_fields,unknown => <<"body,path...">>,unmatched => <<"auth_source,collection...">>},<<"authz:mysql">> => #{kind => validation_error,path => "authorization.sources.1",reason => unknown_fields,unknown => <<"body,path...">>,unmatched => <<"auto_reconnect,database...">>},<<"authz:postgresql">> => #{kind => validation_error,path => "authorization.sources.1",reason => unknown_fields,unknown => <<"body,path...">>,unmatched => <<"auto_reconnect,database...">>},<<"authz:redis_cluster">> => #{kind => validation_error,path => "authorization.sources.1",reason => unknown_fields,unknown => <<"body,path...">>,unmatched => <<"auto_reconnect,cmd...">>},<<"authz:redis_sentinel">> => #{kind => validation_error,path => "authorization.sources.1",reason => unknown_fields,unknown => <<"body,path...">>,unmatched => <<"auto_reconnect,cmd...">>},<<"authz:redis_single">> => #{kind => validation_error,path => "authorization.sources.1",reason => unknown_fields,unknown => <<"body,path...">>,unmatched => <<"auto_reconnect,cmd...">>}},path => "authorization.sources.1",reason => matched_no_union_member}
eb_server-emqx-1  | ERROR: call_hocon_failed: -v -t 2022.08.24.11.26.22 -s emqx_conf_schema -c /opt/emqx/etc/emqx.conf -d /opt/emqx/data/configs generate
</details>
