### ISSUE TITLE
EMQx handles EMQX_TELEMETRY env variable incorrectly

### ISSUE THREAD

**Issue by GunnarPieter** [emqx/emqx#8881]
### What happened?

EMQx does not start with docker-compose script on latest 5.0.7 docker container.

Using the below docker compose file EMQX does not start and emits:
```
Recreating emqx ... done
Attaching to emqx
emqx    | 2022-09-02T09:24:26.308579+00:00 [error] failed_to_check_schema: emqx_conf_schema
emqx    | 2022-09-02T09:24:26.310887+00:00 [error] #{kind => validation_error,location => #{from_env => "EMQX_TELEMETRY"},path => "telemetry",reason => bad_value_for_struct,value => false}
emqx    | ERROR: call_hocon_failed: -v -t 2022.09.02.09.24.25 -s emqx_conf_schema -c /opt/emqx/etc/emqx.conf -d /opt/emqx/data/configs generate
emqx    | 2022-09-02T09:24:30.911766+00:00 [error] failed_to_check_schema: emqx_conf_schema
emqx    | 2022-09-02T09:24:30.914099+00:00 [error] #{kind => validation_error,location => #{from_env => "EMQX_TELEMETRY"},path => "telemetry",reason => bad_value_for_struct,value => false}
emqx    | ERROR: call_hocon_failed: -v -t 2022.09.02.09.24.30 -s emqx_conf_schema -c /opt/emqx/etc/emqx.conf -d /opt/emqx/data/configs generate
emqx exited with code 1
```

```
version: "3"
services:
  emqx:
    image: emqx/emqx:5.0.7
    container_name: emqx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      # General
      - EMQX_MQTT__MAX_PACKET_SIZE=1MB
      - EMQX_ALLOW_ANONYMOUS=false
      # Plugins
      - EMQX_LOADED_PLUGINS="emqx_recon, emqx_retainer, emqx_management, emqx_dashboard, emqx_telemetry"
      # Dashboard
      - EMQX_DASHBOARD__DEFAULT_USERNAME=username
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=NoStealingPassword
      # Management
      - EMQX_MANAGEMENT__DEFAULT_APPLICATION__ID=username
      - EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET=NoStealingPassword
      # Telemetry
      - EMQX_TELEMETRY=false
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: 1
    ports:
      - 1883:1883
      - 8883:8883
      - 18083:18083
    restart: unless-stopped
```

### What did you expect to happen?

For the docker container to start with out telemetry. 

### How can we reproduce it (as minimally and precisely as possible)?

Use the above docker compose file and run it

### Anything else we need to know?
I tried with both emqx_telemetry module and without, it leads to the same result.

_No response_

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
docker container crashes can't get output:

Docker container emqx/emqx:5.0.7
```

</details>

### OS version

<details>

```
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
BuildNumber  Caption                          OSArchitecture  Version
19044        Microsoft Windows 10 Enterprise  64-bit          10.0.19044
```

</details>

### Log files

<details>

</details>
