### ISSUE TITLE
bootstrap user data of the authentication 

### ISSUE THREAD

**Issue by lafirest** [emqx/emqx#9148]
### Discussed in https://github.com/emqx/emqx/discussions/9142

<div type='discussions-op-text'>

<sup>Originally posted by **slaesh** October 12, 2022</sup>
It would be great to init a fully runnable container just via env-variables.

Using this works fine, but we need an additional initial user to have a working instance without the need to login to the dashboard.

```yaml
version: '3'

services:
  emqx:
    image: emqx/emqx:5.0.8
    container_name: emqx
    environment:
      # cookie secret
      - EMQX_NODE__COOKIE=super-secret-cookie-secret

      # dashboard credentials
      - EMQX_DASHBOARD__DEFAULT_USERNAME=admin
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=secret-pass
     
      # basic authentication, username/password
      - EMQX_AUTHENTICATION__1__MECHANISM=password_based
      - EMQX_AUTHENTICATION__1__BACKEND=built_in_database

      # TODO: maybe add something like this?
      - EMQX_AUTHENTICATION__1__USER__1__USERNAME=test
      - EMQX_AUTHENTICATION__1__USER__1__PASSWORD=pass
 
    healthcheck:
      test: [ "CMD", "/opt/emqx/bin/emqx_ctl", "status" ]
      interval: 5s
      timeout: 25s
      retries: 5

    ports:
      - 1883:1883
      - 18083:18083
```

How can we achieve this right now? :)</div>
