### ISSUE TITLE
set ZONES__SESSION_EXPIRY_INTERVAL env bad_value_for_struct

### ISSUE THREAD

**Issue by jiyoungdream** [emqx/emqx#9284]
### What happened?

I want to set session_expiry_interval 1m.

```yaml
version: '3'

services:
  emqx1:
    image: emqx/emqx:5.0.4
    container_name: emqx1
    environment:
      - 'EMQX_NODE_NAME=emqx@node1.emqx.io'
      - 'EMQX_CLUSTER__DISCOVERY_STRATEGY=static'
      - 'EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]'
      - EMQX_ZONES__SESSION_EXPIRY_INTERVAL=60s
```

### What did you expect to happen?

session_expiry_interval is 1m.

### How can we reproduce it (as minimally and precisely as possible)?

use env `EMQX_ZONES__SESSION_EXPIRY_INTERVAL=60s`.

### Anything else we need to know?

emqx log is

```go
emqx1  | 2022-11-01T23:55:14.110220+00:00 [error] failed_to_check_schema: emqx_conf_schema
emqx1  | 2022-11-01T23:55:14.112550+00:00 [error] #{kind => validation_error,location => #{from_env => "EMQX_ZONES__SESSION_EXPIRY_INTERVAL"},path => "zones.session_expiry_interval",reason => bad_value_for_struct,value => <<"60s">>}
```

### EMQX version

5.0.4

### OS version

macOS 12.6

### Log files

```go
emqx1  | 2022-11-01T23:55:14.110220+00:00 [error] failed_to_check_schema: emqx_conf_schema
emqx1  | 2022-11-01T23:55:14.112550+00:00 [error] #{kind => validation_error,location => #{from_env => "EMQX_ZONES__SESSION_EXPIRY_INTERVAL"},path => "zones.session_expiry_interval",reason => bad_value_for_struct,value => <<"60s">>}
```
