### ISSUE TITLE
Cannot get connection id for node 'emqx@node2.emqx.io

### ISSUE THREAD

**Issue by jumpingliu** [emqx/emqx#9454]
### What happened?

I'm using docker to set up emqx. Here are my docker-compose.yml and haproxy config file. The strangest thing is that I have tried this docker-compose.yml and haproxy.cfg for a week and it suddenly cannot work.

After `docker-compose up -d` and the logs show:
```
Starting emqx on node emqx@node2.emqx.io
Start mqtt:tcp:internal listener on 127.0.0.1:11883 successfully.
Start mqtt:tcp:external listener on 0.0.0.0:1883 successfully.
Start mqtt:ws:external listener on 0.0.0.0:8083 successfully.
Start mqtt:ssl:external listener on 0.0.0.0:8883 successfully.
Start mqtt:wss:external listener on 0.0.0.0:8084 successfully.
Start http:management listener on 8081 successfully.
2022-11-30T08:42:40.119894+00:00 [warning] [Dashboard] Using default password for dashboard 'admin' user. Please use './bin/emqx_ctl admins' command to change it. NOTE: the default password in config file is only used to initialise the database record, changing the config file after database is initialised has no effect.
Start http:dashboard listener on 18083 successfully.
EMQ X Broker 4.4.10 is running now!
2022-11-30T08:42:41.313499+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:42:41.820789+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
```

```
version: '3'

services:
  emqx1:
    image: emqx/emqx:4.4.10
    container_name: emqx_node1
    restart: always
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=:node1.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io,emqx@node2.emqx.io,emqx@node3.emqx.io"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
        - node1.emqx.io

  emqx2:
    image: emqx/emqx:4.4.10
    container_name: emqx_node2
    restart: always
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node2.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io,emqx@node2.emqx.io,emqx@node3.emqx.io"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
        - node2.emqx.io
  
  emqx3:
    image: emqx/emqx:4.4.10
    container_name: emqx_node3
    restart: always
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node2.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io,emqx@node2.emqx.io,emqx@node3.emqx.io"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
        - node3.emqx.io

  haproxy:
    image: haproxy:2.4
    container_name: emqx_haproxy
    restart: always
    ports:
      - 18083:18083
      - 1883:1883
      - 8083:8083

     
    volumes:
      - ./haproxy.cfg:/haproxy.cfg
    command: ["haproxy", "-f", "/haproxy.cfg"]

    networks:
      emqx-bridge:
        aliases:
        - haproxy.emqx.io

networks:
  emqx-bridge:
    driver: bridge
```
```
global
    log stdout format raw daemon debug
    nbthread 3

defaults
    log global
    mode tcp
    option tcplog
    maxconn 1024000
    timeout connect 30000
    timeout client 600s
    timeout server 600s

frontend emqx_tcp
   mode tcp
   option tcplog
   bind *:1883
   default_backend emqx_tcp_back

backend emqx_tcp_back
    mode tcp
    server emqx1 node1.emqx.io:1883 
    server emqx2 node2.emqx.io:1883   
    server emqx3 node3.emqx.io:1883   

frontend frontend_emqx_dashboard
    bind *:18083
    option tcplog
    mode tcp
    default_backend backend_emqx_dashboard

backend backend_emqx_dashboard
    mode tcp
    balance roundrobin
    server emqx1 node1.emqx.io:18083 
    server emqx2 node2.emqx.io:18083
    server emqx3 node3.emqx.io:18083

```

### What did you expect to happen?

It's supposed to be served as MQTT-Broker and received the message.

### EMQX version

4.4.10

### OS version

ubuntu 20.04

### Log files

<details>
Starting emqx on node emqx@node2.emqx.io
Start mqtt:tcp:internal listener on 127.0.0.1:11883 successfully.
Start mqtt:tcp:external listener on 0.0.0.0:1883 successfully.
Start mqtt:ws:external listener on 0.0.0.0:8083 successfully.
Start mqtt:ssl:external listener on 0.0.0.0:8883 successfully.
Start mqtt:wss:external listener on 0.0.0.0:8084 successfully.
Start http:management listener on 8081 successfully.
2022-11-30T08:42:40.119894+00:00 [warning] [Dashboard] Using default password for dashboard 'admin' user. Please use './bin/emqx_ctl admins' command to change it. NOTE: the default password in config file is only used to initialise the database record, changing the config file after database is initialised has no effect.
Start http:dashboard listener on 18083 successfully.
EMQ X Broker 4.4.10 is running now!
2022-11-30T08:42:41.313499+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:42:41.820789+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:42:48.821365+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx@node1.emqx.io','emqx@node3.emqx.io']
2022-11-30T08:42:48.821810+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-11-30T08:42:55.126060+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:43:01.309064+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:43:08.309207+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx@node1.emqx.io','emqx@node3.emqx.io']
2022-11-30T08:43:08.309805+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-11-30T08:43:15.986460+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:43:16.410867+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:43:22.986114+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx@node1.emqx.io','emqx@node3.emqx.io']
2022-11-30T08:43:22.986455+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-11-30T08:43:29.680104+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:43:36.596397+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:43:36.680182+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx@node1.emqx.io','emqx@node3.emqx.io']
2022-11-30T08:43:36.680576+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-11-30T08:43:50.440181+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:43:57.441007+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx@node1.emqx.io','emqx@node3.emqx.io']
2022-11-30T08:43:57.441160+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-11-30T08:43:57.516529+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:44:11.231262+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:44:18.232215+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx@node1.emqx.io','emqx@node3.emqx.io']
2022-11-30T08:44:18.232602+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-11-30T08:44:18.752941+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:44:32.351367+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:44:32.747427+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:44:39.747306+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx@node1.emqx.io','emqx@node3.emqx.io']
2022-11-30T08:44:39.747736+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-11-30T08:44:46.141637+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:44:52.013909+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:44:59.014028+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx@node1.emqx.io','emqx@node3.emqx.io']
2022-11-30T08:44:59.014274+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-11-30T08:45:06.252165+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:45:06.355326+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:45:13.252960+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx@node1.emqx.io','emqx@node3.emqx.io']
2022-11-30T08:45:13.253083+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-11-30T08:45:18.655342+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:45:25.591676+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:45:32.593353+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx@node1.emqx.io','emqx@node3.emqx.io']
2022-11-30T08:45:32.593889+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-11-30T08:45:39.737011+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:45:47.583167+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:45:54.584025+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx@node1.emqx.io','emqx@node3.emqx.io']
2022-11-30T08:45:54.584129+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-11-30T08:46:00.096329+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:46:01.113802+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:46:07.097027+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx@node1.emqx.io','emqx@node3.emqx.io']
2022-11-30T08:46:07.097125+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-11-30T08:46:15.666455+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:46:19.486201+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:46:26.486943+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx@node1.emqx.io','emqx@node3.emqx.io']
2022-11-30T08:46:26.487049+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-11-30T08:46:29.084442+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:46:31.695312+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'
2022-11-30T08:46:38.695990+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx@node1.emqx.io','emqx@node3.emqx.io']
2022-11-30T08:46:38.696103+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-11-30T08:46:43.090487+00:00 [error] ** Cannot get connection id for node 'emqx@node2.emqx.io'

</details>
