### ISSUE TITLE
Helm chart uses default credentials in secret when configured with non-default credentials

### ISSUE THREAD

**Issue by juusujanar** [emqx/emqx#9466]
### What happened?

When installing emqx from a helm chart with `metrics.enabled: true` and non-default dashboard username and password, it creates a secret for basic-auth with default username and password (admin/public) due to faulty if-not-empty condition.

If dashboard username and password fields are empty, the basic-auth secret fields end up empty and not with default credentials for the dashboard.

### What did you expect to happen?

Basic-auth secret is generated with the given non-default credentials if credentials are provided. If credentials are not provided, use default admin/public.

### How can we reproduce it (as minimally and precisely as possible)?

Configure the Helm chart values to the following:

```yaml
metrics:
  enabled: true
emqxConfig:
  EMQX_DASHBOARD__DEFAULT_USERNAME: "userX"
  EMQX_DASHBOARD__DEFAULT_PASSWORD: "passwordY"
```

### EMQX version

<details>

emqx chart version 5.0.11, emqx-enterprise chart version 5.0.0. Likely also affects previous versions. Application version is irrelevant.

</details>

### OS version

<details>

Irrelevant to the issue.

</details>

### Log files

<details>

</details>
