### ISSUE TITLE
Cannot parse jwt verify claims with placeholder from environment vairiable

### ISSUE THREAD

**Issue by lantica** [emqx/emqx#9880]
### What happened?

I would like to set jwt verify claims from environment variables and below is my docker-compose file
```
version: '3.8'

services:
  emqx:
    image: emqx:5.0.15
    ports:
      - 18083:18083
      - 1883:1883
    environment:
      - EMQX_AUTHENTICATION__1__ENABLE=true
      - |
        EMQX_AUTHENTICATION__1__PUBLIC_KEY=
        -----BEGIN PUBLIC KEY-----
        -----END PUBLIC KEY-----
      - EMQX_AUTHENTICATION__1__ALGORITHM=public-key
      - EMQX_AUTHENTICATION__1__MECHANISM=jwt
      - EMQX_AUTHENTICATION__1__USE_JWKS=false
      - EMQX_AUTHENTICATION__1__VERIFY_CLAIMS=clientId:$${clientId}
      - EMQX_LOG__CONSOLE_HANDLER__ENABLE=true
      - EMQX_LOG__CONSOLE_HANDLER__LEVEL=debug
```

However, there is parsing error and the whole program crashed.
Here is the error message
```
emqx-emqx-1  | 2023-02-01T12:39:25.192871+00:00 [error] line: 71, mfa: emqx_authn_app:initialize/0, msg: failed_to_initialize_authentication, reason: {emqx_authn_jwt,[#{kind => validation_error,mismatches => #{"authn-jwt:hmac-based" => #{kind => validation_error,path => "authentication",reason => unknown_fields,unknown => "public_key",unmatched => "acl_claim_name,from,..."},"authn-jwt:jwks" => #{kind => validation_error,path => "authentication",reason => unknown_fields,unknown => "algorithm,public_key",unmatched => "acl_claim_name,endpoint,..."},"authn-jwt:public-key" => #{exception => {error,{badmap,"clientId:${clientId}"}},kind => validation_error,path => "authentication.verify_claims",reason => converter_crashed,stacktrace => [{maps,to_list,["clientId:${username}"],[{file,"maps.erl"},{line,517},{error_info,#{module => erl_stdlib_errors}}]},{emqx_authn_jwt,'-verify_claims/1-fun-2-',1,[{file,"emqx_authn_jwt.erl"},{line,149}]},{hocon_tconf,map_field_maybe_convert,5,[{file,"hocon_tconf.erl"},{line,523}]},{hocon_tconf,map_one_field,4,[{file,"hocon_tconf.erl"},{line,487}]},{hocon_tconf,map_fields_cont,4,[{file,"hocon_tconf.erl"},{line,451}]},{hocon_tconf,do_map_union,4,[{file,"hocon_tconf.erl"},{line,766}]},{hocon_tconf,map_field,4,[{file,"hocon_tconf.erl"},{line,587}]},{hocon_tconf,map_one_field,4,[{file,"hocon_tconf.erl"},{line,487}]},{hocon_tconf,map_fields_cont,4,[{file,"hocon_tconf.erl"},{line,451}]},{hocon_tconf,map,4,[{file,"hocon_tconf.erl"},{line,306}]},{hocon_tconf,do_check,4,[{file,"hocon_tconf.erl"},{line,265}]},{emqx_authn,check_config,2,[{file,"emqx_authn.erl"},{line,56}]},{emqx_authn,check_configs,2,[{file,"emqx_authn.erl"},{line,50}]},{emqx_authn_app,'-initialize/0-fun-0-',1,[{file,"emqx_authn_app.erl"},{line,59}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{emqx_authn_app,initialize,0,[{file,"emqx_authn_app.erl"},{line,57}]},{emqx_authn_app,start,2,[{file,"emqx_authn_app.erl"},{line,40}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,293}]}]}},path => "authentication",reason => matched_no_union_member}]}
```

### What did you expect to happen?

EMQX should parse the environment variable and setup the verify claims as `clientId:${clientid}`.

### How can we reproduce it (as minimally and precisely as possible)?

Spin up container for emqx image with the docker-compose file provided.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.0.15
datetime  : 2023-02-01T12:43:35.785917909+00:00
uptime    : 8 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux eb2b3bba90ef 5.15.49-linuxkit #1 SMP Tue Sep 13 07:51:46 UTC 2022 x86_64 GNU/Linux

```

</details>

### Log files

<details>

</details>
