### ISSUE TITLE
EMQX is not able to connect to Postgres since version 5.0.14

### ISSUE THREAD

**Issue by rubengees** [emqx/emqx#9907]
### What happened?

In version 5.0.13 EMQX was able to connect to Postgres with the following configuration (k8s):

```yaml
- name: EMQX_AUTHENTICATION__1__MECHANISM
  value: password_based
- name: EMQX_AUTHENTICATION__1__BACKEND
  value: postgresql
- name: EMQX_AUTHENTICATION__1__ENABLE
  value: "true"
- name: EMQX_AUTHENTICATION__1__DATABASE
  value: emqx
- name: EMQX_AUTHENTICATION__1__POOL_SIZE
  value: "2"
- name: EMQX_AUTHENTICATION__1__USERNAME
  value: user
- name: EMQX_AUTHENTICATION__1__PASSWORD
  valueFrom:
    secretKeyRef:
      name: secret
      key: password
- name: EMQX_AUTHENTICATION__1__PASSWORD_HASH_ALGORITHM__NAME
  value: bcrypt
- name: EMQX_AUTHENTICATION__1__SERVER
  value: '"some-complicated-hostname-1234-0.b.db.ondigitalocean.com:25060"'
- name: EMQX_AUTHENTICATION__1__QUERY
  value: "SELECT password, is_superuser FROM mqtt_user where username = ${username} LIMIT 1"
- name: EMQX_AUTHENTICATION__1__SSL__ENABLE
  value: "true"
- name: EMQX_AUTHENTICATION__1__SSL__CACERTFILE
  value: /etc/ca-certificate-postgresql.crt
```

As of version 5.0.14 this does not work anymore. Same for the latest version 5.0.16. The logs are:

```
emqx 2023-02-03T12:24:02.199598+00:00 [error] REPORT_CB/2 CRASH: [{mfa,["supervisor",":","start_children","/2"]},{line,392},{label,{supervisor,start_error}},{report,[{
supervisor,{<0.3204.0>,ecpool_pool_sup}},{errorContext,start_error},{reason,{shutdown,{failed_to_start_child,{worker,1},invalid_authorization_specification}}},{offende
r,[{pid,undefined},{id,worker_sup},{mfargs,{ecpool_worker_sup,start_link,['emqx_connector_pgsql:9:10',emqx_connector_pgsql,[{host,"some-complicated-hostname-1234-0.b.db.ondig
italocean.com"},{port,25060},{username,<<"user">>},{password,#Fun<emqx_secret.0.22610105>},{database,<<"emqx">>},{auto_reconnect,2},{pool_size,3
},{ssl,required},{ssl_opts,[{cacertfile,"/etc/ca-certificate-postgresql.crt"},{verify,verify_none},{versions,['tlsv1.3','tlsv1.2','tlsv1.1',tlsv1]},{ciphers,["TLS_AES_
256_GCM_SHA384","TLS_AES_128_GCM_SHA256","TLS_CHACHA20_POLY1305_SHA256","TLS_AES_128_CCM_SHA256","TLS_AES_128_CCM_8_SHA256","ECDHE-ECDSA-AES256-GCM-SHA384","ECDHE-RSA-
AES256-GCM-SHA384","ECDHE-ECDSA-AES256-SHA384","ECDHE-RSA-AES256-SHA384","ECDH-ECDSA-AES256-GCM-SHA384","ECDH-RSA-AES256-GCM-SHA384","ECDH-ECDSA-AES256-SHA384","ECDH-R
SA-AES256-SHA384","DHE-DSS-AES256-GCM-SHA384","DHE-DSS-AES256-SHA256","AES256-GCM-SHA384","AES256-SHA256","ECDHE-ECDSA-AES128-GCM-SHA256","ECDHE-RSA-AES128-GCM-SHA256"
,"ECDHE-ECDSA-AES128-SHA256","ECDHE-RSA-AES128-SHA256","ECDH-ECDSA-AES128-GCM-SHA256","ECDH-RSA-AES128-GCM-SHA256","ECDH-ECDSA-AES128-SHA256","ECDH-RSA-AES128-SHA256",
"DHE-DSS-AES128-GCM-SHA256","DHE-DSS-AES128-SHA256","AES128-GCM-SHA256","AES128-SHA256","ECDHE-ECDSA-AES256-SHA","ECDHE-RSA-AES256-SHA","DHE-DSS-AES256-SHA","ECDH-ECDS
A-AES256-SHA","ECDH-RSA-AES256-SHA","ECDHE-ECDSA-AES128-SHA","ECDHE-RSA-AES128-SHA","DHE-DSS-AES128-SHA","ECDH-ECDSA-AES128-SHA","ECDH-RSA-AES128-SHA","RSA-PSK-AES256-
GCM-SHA384","RSA-PSK-AES256-CBC-SHA384","RSA-PSK-AES128-GCM-SHA256","RSA-PSK-AES128-CBC-SHA256","RSA-PSK-AES256-CBC-SHA","RSA-PSK-AES128-CBC-SHA"]},{reuse_sessions,tru
e},{depth,10},{secure_renegotiate,true}]}]]}},{restart_type,transient},{significant,false},{shutdown,infinity},{child_type,supervisor}]}]}]; Reason: {error,function_cl
ause,[{supervisor,format_log_multi,[[{mfa,["supervisor",":","start_children","/2"]},{line,392},{label,{supervisor,start_error}},{report,[{supervisor,{<0.3204.0>,ecpool
_pool_sup}},{errorContext,start_error},{reason,{shutdown,{failed_to_start_child,{worker,1},invalid_authorization_specification}}},{offender,[{pid,undefined},{id,worker
_sup},{mfargs,{ecpool_worker_sup,start_link,['emqx_connector_pgsql:9:10',emqx_connector_pgsql,[{host,"some-complicated-hostname-1234-0.b.db.ondigitalocean.com"},{port,25060},
{username,<<"user">>},{password,#Fun<emqx_secret.0.22610105>},{database,<<"emqx">>},{auto_reconnect,2},{pool_size,3},{ssl,required},{ssl_opts,[{
cacertfile,"/etc/ca-certificate-postgresql.crt"},{verify,verify_none},{versions,['tlsv1.3','tlsv1.2','tlsv1.1',tlsv1]},{ciphers,["TLS_AES_256_GCM_SHA384","TLS_AES_128_
GCM_SHA256","TLS_CHACHA20_POLY1305_SHA256","TLS_AES_128_CCM_SHA256","TLS_AES_128_CCM_8_SHA256","ECDHE-ECDSA-AES256-GCM-SHA384","ECDHE-RSA-AES256-GCM-SHA384","ECDHE-ECD
SA-AES256-SHA384","ECDHE-RSA-AES256-SHA384","ECDH-ECDSA-AES256-GCM-SHA384","ECDH-RSA-AES256-GCM-SHA384","ECDH-ECDSA-AES256-SHA384","ECDH-RSA-AES256-SHA384","DHE-DSS-AE
S256-GCM-SHA384","DHE-DSS-AES256-SHA256","AES256-GCM-SHA384","AES256-SHA256","ECDHE-ECDSA-AES128-GCM-SHA256","ECDHE-RSA-AES128-GCM-SHA256","ECDHE-ECDSA-AES128-SHA256",
"ECDHE-RSA-AES128-SHA256","ECDH-ECDSA-AES128-GCM-SHA256","ECDH-RSA-AES128-GCM-SHA256","ECDH-ECDSA-AES128-SHA256","ECDH-RSA-AES128-SHA256","DHE-DSS-AES128-GCM-SHA256","
DHE-DSS-AES128-SHA256","AES128-GCM-SHA256","AES128-SHA256","ECDHE-ECDSA-AES256-SHA","ECDHE-RSA-AES256-SHA","DHE-DSS-AES256-SHA","ECDH-ECDSA-AES256-SHA","ECDH-RSA-AES25
6-SHA","ECDHE-ECDSA-AES128-SHA","ECDHE-RSA-AES128-SHA","DHE-DSS-AES128-SHA","ECDH-ECDSA-AES128-SHA","ECDH-RSA-AES128-SHA","RSA-PSK-AES256-GCM-SHA384","RSA-PSK-AES256-C
BC-SHA384","RSA-PSK-AES128-GCM-SHA256","RSA-PSK-AES128-CBC-SHA256","RSA-PSK-AES256-CBC-SHA","RSA-PSK-AES128-CBC-SHA"]},{reuse_sessions,true},{depth,10},{secure_renegot
BC-SHA384","RSA-PSK-AES128-GCM-SHA256","RSA-PSK-AES128-CBC-SHA256","RSA-PSK-AES256-CBC-SHA","RSA-PSK-AES128-CBC-SHA"]},{reuse_sessions,true},{depth,10},{secure_renegot
iate,true}]}]]}},{restart_type,transient},{significant,false},{shutdown,infinity},{child_type,supervisor}]}]}],#{chars_limit => unlimited,depth => 100,encoding => utf8
,single_line => true}],[{file,"supervisor.erl"},{line,1657}]},{supervisor,format_log,2,[{file,"supervisor.erl"},{line,1619}]}]}
emqx 2023-02-03T12:24:02.203864+00:00 [error] msg: start_ecpool_error, mfa: emqx_plugin_libs_pool:start_pool/3, line: 48, pool_name: 'emqx_connector_pgsql:9:10', reason: invalid_authorization_specification
emqx 2023-02-03T12:43:03.134463+00:00 [warning] msg: start_resource_failed, mfa: emqx_resource_manager:start_resource/2, line: 494, id: <<"emqx_connector_pgsql:9">>, reason: {start_pool_failed,'emqx_connector_pgsql:9:10',invalid_authorization_specification}
```

### What did you expect to happen?

EMQX connects to Postgres.

### Anything else we need to know?

This may be related to https://github.com/emqx/emqx/pull/9614. I tried to configure the host in both these ways:

```yaml
- name: EMQX_AUTHENTICATION__1__SERVER
  value: '"some-complicated-hostname-1234-0.b.db.ondigitalocean.com:25060"'
```

```yaml
- name: EMQX_AUTHENTICATION__1__SERVER
  value: "some-complicated-hostname-1234-0.b.db.ondigitalocean.com:25060"
```

None worked or changed the logs.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.0.16
datetime  : 2023-02-03T12:44:45.431454132+00:00
uptime    : 20 minutes, 48 seconds
```

</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
$ uname -a
Linux emqx-core-2 5.10.0-0.bpo.15-amd64 #1 SMP Debian 5.10.120-1~bpo10+1 (2022-06-13) x86_64 GNU/Linux
```

</details>

### Log files

See above.
