### ISSUE TITLE
how to make the client only can publish messages to self

### ISSUE THREAD

**Issue by wunengbiao** [emqx/emqx#9969]
### What would you like to be added or enhanced?

 client_id: sn100000 可以向sensor/sn100000/ctr 发布消息，其他用户都不能向这个主题发布消息， 权限该怎么设置呢？

### Why is this needed?

数据安全性

**Comment by lafirest** [comment]
@wunengbiao,
Hi, I assume you are using the EMQX version 4, so you can find the [ACL](https://www.emqx.io/docs/en/v4.4/advanced/acl.html) feature here

**Comment by Kakomis** [comment]
I'm encountering an issue while using ACL with MongoDB in my project. My clients are ESP32 S3 devices. Within a MongoDB Collection, I've set up publish and subscribe fields. However, the issue I'm facing is that only the allowed topics for subscription are being verified. Strangely, my devices are able to publish to any topic without undergoing topic verification. Additionally, I've implemented a superuser role. When I connect via the EMQX Dashboard, I can see the messages from my devices. The puzzling part is that the ACL doesn't seem to be verifying the allowed topics for publishing.

Here's a snippet of my EMQX configuration from a Docker file:

```yaml
# Enable ACL query
# ACCESS CONTROL LIST
EMQX_AUTH__MONGO__ACL_QUERY: 'on'
EMQX_AUTH__MONGO__ACL_QUERY__COLLECTION: 'emqxauthrules'
EMQX_AUTH__MONGO__ACL_QUERY__SELECTOR: 'username=%u'
```

Any insights into why the ACL isn't properly verifying allowed publishing topics would be greatly appreciated!
